lib/active_record/connection_adapters/oracle_enhanced_oci_connection.rb

While I had the ruby-oci8 library already installed, I was puzzled by this error:
> ERROR: ActiveRecord oracle_enhanced adapter could not load ruby-oci8 library. Please install ruby-oci8 gem.
After revealing the original load error received, I discovered that the original message was:
> LoadError: libaio.so.1: cannot open shared object file: No such file or directory
So I got rid of this (on Travis CI), by installing `libaio1` via `sudo apt-get install libaio1`

Show original error message when loading ruby-oci8 library fails

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

This pull request addresses a following failure.
```ruby
$ ARCONN=oracle ruby -Itest test/cases/adapter_test.rb -n test_log_invalid_encoding
Using oracle
Run options: -n test_log_invalid_encoding --seed 36946
F
Finished in 0.004685s, 213.4363 runs/s, 213.4363 assertions/s.
1) Failure:
ActiveRecord::AdapterTest#test_log_invalid_encoding [test/cases/adapter_test.rb:221]:
[ActiveRecord::StatementInvalid] exception expected, not
Class: <ArgumentError>
Message: <"wrong number of arguments (1 for 2..3)">
/home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:1288:in `log'
test/cases/adapter_test.rb:222:in `block in test_log_invalid_encoding'
---------------
1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
$
```

Change log method signiture to support Rails 4.2

---

lib/active_record/connection_adapters/oracle_enhanced_schema_statements.rb
spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb

`:if_exists` option introduced by https://github.com/rails/rails/pull/18597.
And it is used by test case already. https://github.com/rails/rails/commit/7675364
How about this pull request?

Add `:if_exists` option to `drop_table` for compatibility with other adapters

---

.gitignore
spec/spec_config.yaml.template
spec/spec_helper.rb

This patch adds the ability to load spec configuration from a file instead of env variables. This is easier to share in our team and I could imagine other scenarios where it is useful.
ENV based configuration still works too, of course.

Rails42 configurable spec

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Fixes https://github.com/rsim/oracle-enhanced/issues/548
According to http://edgeguides.rubyonrails.org/4_2_release_notes.html#active-record-notable-changes
(3rd point, "ActiveRecord::Dirty now detects in-place changes to mutable values.")
it should be no longer necessary to check whether the attribute is serialized.
Note: this change is probably incompatible with rails prior 4.2.0.

Remove call to deprecated `serialized_attributes`.

---

lib/active_record/connection_adapters/oracle_enhanced_database_tasks.rb
spec/active_record/connection_adapters/oracle_enhanced_database_tasks_spec.rb

Right now, when you run `rake db:structure:dump` the schema information (i.e. which migrations have been run) are dumped twice when using sql as the schema format. This prevents you from loading the `structure.sql` file since it will try to run inserts that violate the uniqueness constraint on the `schema_migrations` table.
This happens because Rails is calling `connection.dump_schema_information` after we also call it in `connection.structure_dump`.
This change removes our call to `connection.dump_schema_information` so it is only called once, by Rails.
This fixes #460. This is the same change as in #470 but with tests.

Do not dump schema information during structure dump

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

Database links, unlike column names, CAN contain periods, which were not being handled properly by the `quote_table_name` method (#556).
This PR:
- adds a spec demonstrating the bug
- adds a new `quote_database_link` method to be used only for database links (since link quoting follows different rules)
- reworks the existing `quote_table_name` method to differentiate between tables/schemas, and links

Properly quote database links

---

lib/active_record/connection_adapters/oracle_enhanced_schema_dumper.rb

This pull request removes duplicate `alias_method_chain :indexes, :oracle_enhanced` introduced by 
0fda4af27e22df654d67684c6c4fa8001c10ec04

Remove duplicate alias_method_chain for indexes

---

activerecord-oracle_enhanced-adapter.gemspec
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
lib/active_record/connection_adapters/oracle_enhanced_schema_definitions.rb
lib/active_record/connection_adapters/oracle_enhanced_schema_statements.rb
lib/active_record/type/timestamp.rb

This pull request addresses #542 by supporting timestamp datatype in Rails 4.2.  
Due to current implementation restriction, it needs to override `aliased_types` method. Then those who uses Oracle and non-Oracle adapters at the same time c1722f0001a894d2f9899038e999ab41acebbe3b should be reverted when we support `create_table_definition` method.

Support :timestamp datatype in Rails 4.2

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
lib/active_record/connection_adapters/oracle_enhanced_column.rb
lib/active_record/connection_adapters/oracle_enhanced_column_dumper.rb
lib/active_record/connection_adapters/oracle_enhanced_dirty.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_dirty_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb

This pull request reverts #418 at rails42 branch. There are some reasons:
- Rails `:float` datatype should be mapped to Oracle `BINARY_FLOAT` or `BINARY_DOUBLE` datatype
- There are some technical difficulties such as #514
Discussed with @rsim and we agreed to revert this change.
This reverts commit f275bc74855c93ce1e0f686aa2dc9a9f4da02efb.
Conflicts:
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
lib/active_record/connection_adapters/oracle_enhanced_column.rb
lib/active_record/connection_adapters/oracle_enhanced_column_dumper.rb
lib/active_record/connection_adapters/oracle_enhanced_dirty.rb
spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb

Revert "Implement possibility of handling of NUMBER columns as :float"

---

lib/active_record/connection_adapters/oracle_enhanced_schema_statements.rb

This pull request addresses the following failure. Also use same method argument names as Rails.
```ruby
$ ARCONN=oracle ruby -Itest test/cases/migration/index_test.rb -n test_rename_index_too_long
Using oracle
Run options: -n test_rename_index_too_long --seed 11559
F
Finished in 0.045530s, 21.9635 runs/s, 21.9635 assertions/s.
1) Failure:
ActiveRecord::Migration::IndexTest#test_rename_index_too_long [test/cases/migration/index_test.rb:43]:
[ArgumentError] exception expected, not
Class: <ActiveRecord::StatementInvalid>
Message: <"OCIError: ORA-00972: identifier is too long: ALTER INDEX \"OLD_IDX\" rename to \"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\"">
stmt.c:250:in oci8lib_220.so
/home/yahonda/.rvm/gems/ruby-2.2.2@rails42/gems/ruby-oci8-2.1.8/lib/oci8/cursor.rb:129:in `exec' …
```

Raise a better exception for renaming long indexes

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

This pull request addresses #542 and following 3 errors.
```ruby
$ ARCONN=oracle ruby -Itest test/cases/base_test.rb
Using oracle
Run options: --seed 64413
......E............E......................................................................................E........................................
Finished in 2.806855s, 52.3718 runs/s, 119.3507 assertions/s.
... snip ...
2) Error:
BasicsTest#test_big_decimal_conditions:
RangeError: 6000000000 is out of range for ActiveRecord::Type::Integer with limit 4
/home/yahonda/git/rails/activerecord/lib/active_record/type/integer.rb:45:in `ensure_in_range'
/home/yahonda/git/rails/activerecord/lib/active_record/type/integer.rb:23:in `type_cast_for_database'
/home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/quotin …
```

Address RangeError: <m> is out of range for ActiveRecord::Type::Integer with limit <n>

---

lib/active_record/connection_adapters/oracle_enhanced_schema_statements.rb

This pull request addresses this error by supporting `:cascade` option for `drop_table`.
```ruby
$ ARCONN=oracle ruby -Itest test/cases/migration/change_schema_test.rb -n test_create_table_with_force_cascade_drops_dependent_objects
Using oracle
Run options: -n test_create_table_with_force_cascade_drops_dependent_objects --seed 64310
E
Finished in 0.081517s, 12.2673 runs/s, 12.2673 assertions/s.
1) Error:
ActiveRecord::Migration::ChangeSchemaWithDependentObjectsTest#test_create_table_with_force_cascade_drops_dependent_objects:
ActiveRecord::StatementInvalid: OCIError: ORA-02449: unique/primary keys in table referenced by foreign keys: DROP TABLE "TRAINS"
stmt.c:250:in oci8lib_220.so
/home/yahonda/.rvm/gems/ruby-2.2.2@rails42/gems/ruby-oci8-2.1.8/lib/oci8/cursor.rb:129:in `exec' …
```

Support :cascade option for drop_table

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

refer https://github.com/rails/rails/commit/574234be
`:bigint` mapped to `NUMBER(8)`. Here is a example.
```sql
(10.1ms)  CREATE TABLE "TESTINGS" ("ID" NUMBER(38) NOT NULL PRIMARY KEY, "EIGHT_INT" NUMBER(8))
```
This pull request also address this error.
```ruby
$ ARCONN=oracle ruby -Itest test/cases/migration/change_schema_test.rb -n test_create_table_with_bigint
Using oracle
Run options: -n test_create_table_with_bigint --seed 10139
E
Finished in 0.010570s, 94.6097 runs/s, 0.0000 assertions/s.
1) Error:
ActiveRecord::Migration::ChangeSchemaTest#test_create_table_with_bigint:
ActiveRecord::StatementInvalid: OCIError: ORA-00942: table or view does not exist: DROP TABLE "TESTINGS"
stmt.c:250:in oci8lib_220.so
/home/yahonda/.rvm/gems/ruby-2.2.2@rails42/gems/ruby-oci8-2.1.8/lib/oci8/cursor.rb …
```

Support :bigint datatype

---

lib/active_record/connection_adapters/oracle_enhanced_schema_definitions.rb

since Rails 4.2 supports native foreign key. References can create foreign keys.
Also this pull request addresses following errors and failures.
```ruby
$ ARCONN=oracle ruby -Itest test/cases/migration/references_foreign_key_test.rb -n test_foreign_keys_can_be_created_while_changing_the_table
Using oracle
Run options: -n test_foreign_keys_can_be_created_while_changing_the_table --seed 25024
E
Finished in 0.076251s, 13.1147 runs/s, 0.0000 assertions/s.
1) Error:
ActiveRecord::Migration::ReferencesForeignKeyTest#test_foreign_keys_can_be_created_while_changing_the_table:
NoMethodError: undefined method `split' for nil:NilClass
/home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:593:in `quote_table_name' …
```

Remove alias_method_chain :references, :foreign_keys

---

lib/active_record/connection_adapters/oracle_enhanced_schema_dumper.rb

Return foreign_keys_without_oracle_enhanced when non Oracle database used

---

lib/active_record/connection_adapters/oracle_enhanced/schema_creation.rb

This reverts commit 480a30f443bb3777bf600bab99d562780b4e6225.
Refer #384 we can remove this method since `rails42` branch just supports Rails 4.2.

Revert "Add options_include_default!"

---

lib/activerecord-oracle_enhanced-adapter.rb

There was a typo in the load statement for the database tasks, fixed the load path.
rake aborted!
LoadError: cannot load such file -- active_record/connection_adapters/oracle_enhanced_database_tasks.rb

Fixed typo in the rake tasks load statement

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

This pull request should address #563 and addresses these 3 failures.
```ruby
$ ARCONN=oracle ruby -Itest test/cases/serialized_attribute_test.rb -n /test_serialized/
Using oracle
Run options: -n /test_serialized/ --seed 8214
.......FF......F
Finished in 0.510452s, 31.3448 runs/s, 66.6076 assertions/s.
1) Failure:
SerializedAttributeTest#test_serialized_boolean_value_false [test/cases/serialized_attribute_test.rb:194]:
Expected: "N"
Actual: false
2) Failure:
SerializedAttributeTest#test_serialized_boolean_value_true [test/cases/serialized_attribute_test.rb:187]:
Expected: "Y"
Actual: true
3) Failure:
SerializedAttributeTest#test_serialized_time_attribute [test/cases/serialized_attribute_test.rb:118]:
--- expected
+++ actual
@@ -1 +1 @@
-2008-01-01 01:00:00 +0000
+"01-JAN-08 …
```

Call super when column typs is serialized

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb

This pull request addresses following failure.
```ruby
$ ARCONN=oracle ruby -Itest test/cases/query_cache_test.rb -n test_query_cache_doesnt_leak_cached_results_of_rolled_back_queries
Using oracle
Run options: -n test_query_cache_doesnt_leak_cached_results_of_rolled_back_queries --seed 23558
F
Finished in 0.339571s, 2.9449 runs/s, 5.8898 assertions/s.
1) Failure:
QueryCacheTest#test_query_cache_doesnt_leak_cached_results_of_rolled_back_queries [test/cases/query_cache_test.rb:226]:
Expected: 0
Actual: 1
1 runs, 2 assertions, 1 failures, 0 errors, 0 skips
$
```
Refer https://github.com/rails/rails/pull/17820 for detail.

Clear query cache on rollback

---

lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb

Refer https://github.com/rails/rails/pull/18082
This pull request addresses following failure.
```ruby
$ ARCONN=oracle ruby -Itest test/cases/schema_dumper_test.rb -n test_schema_dump_uses_force_cascade_on_create_table
Using oracle
Run options: -n test_schema_dump_uses_force_cascade_on_create_table --seed 29245
F
Finished in 1.403931s, 0.7123 runs/s, 1.4246 assertions/s.
1) Failure:
SchemaDumperTest#test_schema_dump_uses_force_cascade_on_create_table [test/cases/schema_dumper_test.rb:45]:
Expected /create_table "authors", force: :cascade/ to match "# encoding: UTF-8\n# This file is auto-generated from the current state of the database. Instead\n# of editing this file, please use the migrations feature of Active Record to\n# incrementally modify your database, and then regenerate this …
```

New db/schema.rb files will be created with force: :cascade

---

lib/active_record/connection_adapters/oracle_enhanced/column.rb
lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Use `new_column` method instaead of `OracleEnhancedColumn.new`
Add handling Oracle enhanced specific datatype changes such as `emulate_dates_by_column_name`
This pull request addresses these 4 failures.
```ruby
$ rspec ./spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb
==> Effective ActiveRecord version 4.2.2.beta
..............F............F........F...FF........................DEPRECATION WARNING: `serialized_attributes` is deprecated without replacement, and will be removed in Rails 5.0. (called from block in write_lobs at /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:825)
..DEPRECATION …
```

Removed `forced_column_type` by using `cast_type`

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

This pull request addresses following failure.
```ruby
$ rspec ./spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb:437
==> Effective ActiveRecord version 4.2.2.beta
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb"=>[437]}}
F
Failures:
1) OracleEnhancedAdapter boolean type detection based on string column types and names should get default value from VARCHAR2 boolean column if emulate_booleans_from_strings is true
Failure/Error: columns.detect{|c| c.name == 'manager_yn'}.default.should be_false
expected: falsey value
got: "N"
Deprecation Warnings:
`be_false` is deprecated. Use …
```

Modify default to `false` if database default value is "N"

---

lib/active_record/connection_adapters/oracle_enhanced/schema_definitions.rb

This pull request changes OracleEnhancedIndexDefinition as subclass of IndexDefinition.
It is necessary for further refactoring.

Make OracleEnhancedIndexDefinition as subclass of IndexDefinition

---

activerecord-oracle_enhanced-adapter.gemspec

#605 has missed adding the integer.rb to the gemspec.

Add integer.rb to gemspec

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

by specifying `:limit => 19`
Bigint should be mapped to NUMBER(19,0) not NUMBER(8,0)
since it is not enough to store the maximum number of bigint.
Oracle NUMBER(p,0) as handled as integer
because there is no dedicated integer sql data type exist in Oracle database.
Also NUMBER(p,s) precision can take up to 38. p means the number of digits, not the byte length.
bigint type needs 19 digits as follows.
```ruby
$ irb
2.2.2 :001 > limit = 8
=> 8
2.2.2 :002 > maxvalue_of_bigint = 1 << ( limit * 8 - 1)
=> 9223372036854775808
2.2.2 :003 > puts maxvalue_of_bigint.to_s.length
19
=> nil
2.2.2 :004 >
```

Map :bigint as NUMBER(19) sql_type not NUMBER(8)

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb

Closed #598 by mistake.
This pull request changes mapping for Rails :float type from Oracle NUMBER to BINARY_FLOAT.
* Based on this document `BINARY_FLOAT` is supported from 10.1 (aka 10gR1).
http://docs.oracle.com/cd/B14117_01/server.101/b10759/wnsql.htm#sthref11
9iR2 or lower version cannot work but it should not be a problem since it was released on 2003.
* binary_float or binary_double
Based on Rails 4.2 implementation, `binary` is configured as a alias for `float`. Then it should be enough to support `BINARY_FLOAT` which should be corresponding to `float` in other databases.
https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb#L390-L419
* Compatibility
This pull request is for rails42 branch only. It should be released …

Use Oracle BINARY_FLOAT datatype for Rails :float type

---

lib/active_record/connection_adapters/oracle_enhanced/schema_creation.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_definitions.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

This pull request supports Rails native foreign key syntax.
Oracle enhanced adapter already has implemented its own foreign key support. These syntax and support feature is similar but some of them are not compatible with Rails implementation. 
* Foreign key name syntax is now `"fk_rails_#{hashed_identifier}"`
Also these tests are getting fail so far. I have been working to support both syntax but it is quite difficult for me, then I have decided to merge Rails native feature support first. 
These failing tests show some of incompatibilities. 
```ruby
rspec ./spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb:179 # OracleEnhancedAdapter schema dump foreign key constraints should include foreign key in schema dump
rspec …
```

Support Rails native foreign key syntax

---

lib/active_record/connection_adapters/oracle_enhanced/schema_definitions.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

```ruby
$ rspec ./spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb:684
==> Effective ActiveRecord version 4.2.2.beta
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb"=>[684]}}
F
Failures:
1) OracleEnhancedAdapter schema definition foreign key constraints should add foreign key with very long name which is shortened
Failure/Error: add_foreign_key :test_comments, :test_posts, :name => "long_prefix_test_comments_test_post_id_foreign_key"
OCIError: ORA-00972: identifier is too long: ALTER …
```

Shorten foreign key name if it is longer than 30 byte

---

lib/active_record/connection_adapters/oracle_enhanced/structure_dump.rb

On the rails42 branch, a text search for foreign_key_definition yields only one result. Should we remove it? Resolves #623 
±  || → ag foreign_key_definition
lib/active_record/connection_adapters/oracle_enhanced/structure_dump.rb
130:              sql << "#{foreign_key_definition(fk.to_table, fk.options)}"
Edit: It's required to produce structure.sql correctly, bringing back the deleted definition

Restore foreign_key_definition

---

lib/active_record/connection_adapters/oracle_enhanced/schema_definitions.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

This pull request addresses following failures.
```ruby
$ rspec ./spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb:848
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb"=>[848]}}
F
Failures:
1) OracleEnhancedAdapter schema definition foreign key in table definition should add foreign key in change_table
Failure/Error: t.foreign_key :test_posts
NoMethodError:
undefined method `foreign_key' for #<ActiveRecord::ConnectionAdapters::Table:0x00000002ffc948>
Finished in 0.18946 seconds
1 example, 1 failure
Failed examples:
rspec …
```

Rails 4.2 support foreign_key and remove_foreign_key in create_table

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

This pull request addresses following failures.
```ruby
$ rspec ./spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb:703
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb"=>[703]}}
F
Failures:
1) OracleEnhancedAdapter schema definition foreign key constraints should add foreign key with delete dependency
Failure/Error: TestPost.delete(p.id)
OCIError: ORA-02292: integrity constraint (ORACLE_ENHANCED.FK_RAILS_CC939FC91F) violated - child record found: DELETE FROM "TEST_POSTS" WHERE "TEST_POSTS"."ID" = …
```

Support add_foreign_key option :dependent => :delete and :nullify

---

lib/active_record/connection_adapters/oracle_enhanced/schema_definitions.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

To keep Rails compatibility refer #625 and #626

Add deprecation warnings for Oracle enhanced specific foreign key methods

---

spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb

Refer https://github.com/rsim/oracle-enhanced/pull/631
:dependent option will be deprecated.

Schema dump uses `:on_delete` option instead of `:dependent`

---

spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb

Refer https://github.com/rails/rails/pull/18791
Also this pull request addresses following failures.
```ruby
$ rspec ./spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb:629
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb"=>[629]}}
F
Failures:
1) OracleEnhancedAdapter schema definition foreign key constraints should add foreign key
Failure/Error: lambda do
expected: /ORA-02291.*\.TEST_COMMENTS_TEST_POST_ID_FK/
got: "OCIError: ORA-02291: integrity constraint (ORACLE_ENHANCED.FK_RAILS_CC939FC91F) violated - parent key not found: …
```

Use Rails foreign key name

---

lib/active_record/connection_adapters/oracle_enhanced/schema_definitions.rb

This pull request adds deprecate warning if foreign key name length is longer than 30 byte.
In next version of Oracle enhanced adapter (1.7 or later) it will get simple 'it is too long' kind of error messages.

Add deprecate warning if foreign key name length is longer than 30 byte

---

spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb

Refer #621 and #636 
It addresses following failure.
```ruby
$ rspec ./spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb:677
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb"=>[677]}}
DEPRECATION WARNING: Foreign key name test_comments_test_post_id_foreign_key is too long. It will not get shorten in later version of Oracle enhanced adapter. (called from name at /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/schema_definitions.rb:17)
F
Failures:
1) OracleEnhancedAdapter schema definition …
```

Foreign key name longer than 30 byte will be shortened using Digest::SHA1.hexdigest

---

spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb

Refer #605
```ruby
$ rspec ./spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb:406
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb"=>[406]}}
F
Failures:
1) OracleEnhancedAdapter schema dump virtual columns should dump correctly
Failure/Error: standard_dump.should =~ /t\.virtual "full_name_length",(\s*)precision: 38,(\s*)scale: 0,(\s*)as:(.*),(\s*)type: :integer/
expected: /t\.virtual "full_name_length",(\s*)precision: 38,(\s*)scale: 0,(\s*)as:(.*),(\s*)type: :integer/
got: "# encoding: UTF-8\n# This file is auto-generated from the current …
```

Schema dumper for :integer will not dump :precision 0

---

Gemfile

First pull request for `rails5` branch to start developing to support Rails 5.

Use arel master branch for rails5 development

---

lib/active_record/connection_adapters/oracle_enhanced/column.rb

This pull request addresses following NameError.
```ruby
$ rake spec
rake aborted!
NameError: uninitialized constant ActiveRecord::ConnectionAdapters::OracleEnhancedColumn::TRUE_VALUES
/home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/column.rb:8:in `<class:OracleEnhancedColumn>'
/home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/column.rb:3:in `<module:ConnectionAdapters>'
/home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/column.rb:2:in `<module:ActiveRecord>'
/home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/column.rb:1 …
```

Remove TRUE_VALUES from OracleEnhancedColumn

---

lib/active_record/connection_adapters/oracle_enhanced/schema_creation.rb

This pull request addresses following error.
```ruby
$ rake test_oracle
... snip ...
/home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/schema_creation.rb:55:in `add_column_options!': undefined method `quote_value' for #<ActiveRecord::ConnectionAdapters::OracleEnhanced::SchemaCreation:0x00000004669a28> (NoMethodError)
from /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/schema_creation.rb:32:in `visit_ColumnDefinition'
from /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/schema_creation.rb:12:in `visit_ColumnDefinition'
from /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/schema_creation.rb:14:in `accept'
from …
```

Address `add_column_options!': undefined method `quote_value'

---

spec/active_record/connection_adapters/oracle_enhanced_procedures_spec.rb

This pull request temporary addresses following failure.
```ruby
$ rspec ./spec/active_record/connection_adapters/oracle_enhanced_procedures_spec.rb:321
==> Effective ActiveRecord version 4.2.3
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_procedures_spec.rb"=>[321]}}
F
Failures:
1) OracleEnhancedAdapter custom methods for create, update and destroy should log create record
Failure/Error: @logger.logged(:debug).last.should match(/^TestEmployee Create \(\d+\.\d+(ms)?\)  custom create method$/)
expected "(57.1ms)  SELECT DECODE(table_name, UPPER(table_name), LOWER(table_name), table_name) FROM all_tables WHERE owner = …
```

Update matcher to skip sql statements to get `table` metadata

---

lib/active_record/connection_adapters/oracle_enhanced/schema_creation.rb

This pull request reverts #647 and renames `quote_value` to `quote_default_expression`.
refer rails/rails#17799

Rename quote_value to quote_default_expression.

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb

Unique constraints not created when function unique index created due to it causes ORA-00904 reported in #662
Note: This attribute cannot be referenced by foreign key since it requires unique constraints created.

Unique constraints not created when function unique index created

---

lib/active_record/connection_adapters/oracle_enhanced/schema_creation.rb
spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb

Applying  #667 to master.
I couldn't do a bundle install using rails trunk:
```
└─╼ bundle update
Updating git://github.com/rails/rails.git
Updating git://github.com/rails/arel.git
Updating git://github.com/rails/journey.git
Updating git://github.com/kubo/ruby-oci8.git
Fetching gem metadata from http://rubygems.org/.........
Fetching version metadata from http://rubygems.org/...
Fetching dependency metadata from http://rubygems.org/..
Resolving dependencies...
Bundler could not find compatible versions for gem "arel":
In Gemfile:
arel (= 7.0.0.alpha) java
activerecord (>= 0) ruby depends on
arel (= 7.0.0.alpha) ruby
arel (>= 0) java
arel (>= 0) ruby
```
I ran tests against 4-2-stable:
```
gem 'activerecord',   github: 'rails/rails', branch: '4-2-stable'
gem 'activemodel',    github: …
```

create_table should use default tablespace values for lobs

---

lib/active_record/connection_adapters/oracle_enhanced/connection.rb
lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

when Oracle server version is 12c
https://github.com/rails/arel/pull/337 has been merged to master.

Use Arel::Visitors::Oracle12 to use better top-N query support

---

activerecord-oracle_enhanced-adapter.gemspec

This pull request follows up #652 since it added incorrect dependency. It requires activerecord, not activemodel.

Requires activerecord 4.2.1 or higher, not activemodel

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb

This pull request is based on #475 since it requires to change file name to `schema_statements.rb`
It also addresses #547 and #588

Set sequence name automatically when new table name is longer than 26 bytes

---

lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

by starting variable name as understore for Ruby 2.0 and above
```ruby
/home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:865: warning: assigned but unused variable - owner
/home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:865: warning: assigned but unused variable - db_link
/home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb:53: warning: assigned but unused variable - pk_seq
/home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb:124: warning: assigned but unused variable - pk_seq
```
Refer https://bugs.ruby-lang.org/issues/6693

Suppress `warning: assigned but unused variable`

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

This pull request suppress the warning message below.
```ruby
/home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb:77: warning: assigned but unused variable - tablespace
```

Suppress `warning: assigned but unused variable - tablespace`

---

lib/active_record/connection_adapters/oracle_enhanced/procedures.rb

This pull request removes `serialized_attributes` method which has been deprecated in Rails 4.2 and will be removed in Rails 5.

Remove `serialized_attributes` which is removed in Rails 5

---

Gemfile

since it will not be supported in Rails 5

Remove activerecord-deprecated_finders

---

spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb
spec/spec_helper.rb

This pull request removes `RAILS_GEM_VERSION` because of these reasons:
* It did not show correct Rails and/or ActiveRecord version tested. Also `Effective ActiveRecord version` shows the correct one.
```ruby
$ rake spec
==> Running specs with MRI version 2.2.3
==> Selected Rails version master
==> Effective ActiveRecord version 5.0.0.alpha
```
* All of `end if ENV['RAILS_GEM_VERSION']` statements are not necessary since these versions are 3.2 or older.

Remove RAILS_GEM_VERSION

---

Gemfile
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_connection_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_context_index_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_cpk_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_database_tasks_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_dbms_output_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_dirty_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_emulate_oracle_adapter_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_procedures_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_structure_dump_spec.rb

This pull request updates RSpec version from 2 to 3. Thanks to https://github.com/yujinakayama/transpec only 3 specs need update manually.
* How to use transpec
```ruby
$ transpec
Copying the project for dynamic analysis...
Running dynamic analysis with command "bundle exec rspec"...
==> Running specs with MRI version 2.2.3
==> Effective ActiveRecord version 4.2.4
........................................................................................................................................................................................................................`raise_error` was called with non-proc object true
....F...........................DEPRECATION WARNING: `:dependent` option will be …
```

Use RSpec 3

---

spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb

This pull request cleans up database objects after Oracle enhanced adapter unit tests executed.
```sql
SQL>  select object_name,object_type from user_objects;
OBJECT_NAME                    OBJECT_TYPE
------------------------------ -----------------------
AAAAAAAAAAAAAAAAAAAAAAAAAAA    TABLE
AAAAAAAAAAAAAAAAAAAAAAAAAA_SEQ SEQUENCE
SYS_C001451650                 INDEX
SQL>  select table_name,index_name from user_indexes
2  ;
TABLE_NAME                     INDEX_NAME
------------------------------ ------------------------------
AAAAAAAAAAAAAAAAAAAAAAAAAAA    SYS_C001451650
SQL>
```
`drop_table` method removes related sequence. Index will be dropped by drop table sql statement itself.

Clean up database objects after unit tests executed

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements_ext.rb
lib/active_record/connection_adapters/oracle_enhanced/structure_dump.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

This pull request uses all_* dictionary replacing user_* ones to keep consistency.
As an exception, `all_users` view does not have `default_tablespace` column then it cannot be changed from `user_users` to `all_users`. Also `user_users` always return one row based on the current database user session, then where clause removed.

Use all_* dictionary replacing user_* ones

---

lib/active_record/connection_adapters/oracle_enhanced/column.rb

This pull request addresses following NameError.
```ruby
$ rake spec
==> Running specs with MRI version 2.3.0
rake aborted!
NameError: uninitialized constant ActiveRecord::ConnectionAdapters::OracleEnhancedColumn::FALSE_VALUES
/home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/column.rb:7:in `<class:OracleEnhancedColumn>'
/home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/column.rb:3:in `<module:ConnectionAdapters>'
/home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/column.rb:2:in `<module:ActiveRecord>'
/home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/column.rb:1:in `<top (required)>' …
```

Remove FALSE_VALUES

---

activerecord-oracle_enhanced-adapter.gemspec

http://guides.rubygems.org/specification-reference/#rubygems_version
```
RUBYGEMS_VERSION
The version of RubyGems used to create this gem.
Do not set this, it is set automatically when the gem is packaged.
```

Remove required_rubygems_version

---

spec/active_record/connection_adapters/oracle_enhanced_connection_spec.rb

This pull request suppress these warnings.
```ruby
$ rspec ./spec/active_record/connection_adapters/oracle_enhanced_connection_spec.rb:268
==> Running specs with MRI version 2.2.3
==> Effective ActiveRecord version 5.0.0.alpha
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_connection_spec.rb"=>[268]}}
WARNING: Using the `raise_error` matcher without providing a specific error or message risks false positives, since `raise_error` will match when Ruby raises a `NoMethodError`, `NameError` or `ArgumentError`, potentially allowing the expectation to pass without even executing the method you are intending to call. Instead consider providing a specific error class or message. This message can be supressed …
```

Supress WARNINGs using `raise_error` without specific errors

---

README.md

@yahonda I anticipate this will come up more and more. Would you consider adding a note about it in the README?

Add note to readme about adapter name when using DATABASE_URL

---

spec/active_record/connection_adapters/oracle_enhanced_structure_dump_spec.rb

This pull request addresses a following failure tested with Oracle Database 10gR2 since it uses virtual columns syntax introduced in 11gR1 http://docs.oracle.com/cd/B28359_01/server.111/b28279/chapter1.htm
```ruby
$ rspec ./spec/active_record/connection_adapters/oracle_enhanced_structure_dump_spec.rb:165
==> Running specs with MRI version 2.2.3
==> Effective ActiveRecord version 4.2.4
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_structure_dump_spec.rb"=>[165]}}
F
Failures:
1) OracleEnhancedAdapter structure dump structure dump should dump RAW virtual columns
Failure/Error: @conn.execute <<-SQL
OCIError: ORA-00907: missing right …
```

Pending a test using virtual columns features introduced in 11gR1

---

lib/active_record/connection_adapters/oracle_enhanced/column_dumper.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb
lib/active_record/connection_adapters/oracle_enhanced/structure_dump.rb
spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_structure_dump_spec.rb

This PR addresses #259. I don't personally use comments, but it makes sense that if they're accepted in migrations that they should also appear in the dumps. Thoughts?

Include table/column comments in schema and structure dumps

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

This pull request handles Rails :datetime as Oracle TIMESTAMP to support subsecond precision,
which has been mapped to Oracle DATE.
It also addresses the following error.
```
$ rake test_oracle
...
OCIError: ORA-00907: missing right parenthesis: CREATE TABLE "DEVELOPERS" ("ID" NUMBER(38) NOT NULL PRIMARY KEY, "NAME" VARCHAR2(255), "FIRST_NAME" VARCHAR2(255), "SALARY" NUMBER(38) DEFAULT 70000, "FIRM_ID" NUMBER(38), "MENTOR_ID" NUMBER(38), "CREATED_AT" DATE(6), "UPDATED_AT" DATE(6), "CREATED_ON" DATE(6), "UPDATED_ON" DATE(6))  (ActiveRecord::StatementInvalid)
...rake aborted!
```
* Rails 5 will support subsecond precision https://github.com/rails/rails/pull/18914
* Oracle Timestamp data type has been introduced in 9.0.1 aka 9iR1
* Modify Oracle `date` to `timestamp` is straightforward …

Rails :datetime as Oracle TIMESTAMP to support subsecond precision

---

.gitignore

This pull request adds Oracle JDBC drivers to .gitignore since they should not be included to the repository.
If Oracle JDBC driver is copied, it appears as untracked files.
```
$ git status
On branch ignore_jdbc_drivers
Untracked files:
(use "git add <file>..." to include in what will be committed)
lib/ojdbc7.jar
nothing added to commit but untracked files present (use "git add" to track)
$
```
This commit will avoid this entry.

Ignore JDBC Drivers

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

Refer https://github.com/rails/rails/pull/22214
This pull request addresses following error.
```ruby
$ rake test_oracle
...
Using oracle
/home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/schema_definitions.rb:383: warning: previous definition of aliased_types was here
/home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/schema_creation.rb:36:in `visit_TableDefinition': undefined method `[]' for nil:NilClass (NoMethodError)
from /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/schema_creation.rb:14:in `accept'
from …
```

Not passing `native_database_types` to `TableDefinition`

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Refer https://github.com/rails/rails/commit/cbcdecd2
https://github.com/rails/rails/issues/21992
This pull request addresses the following error.
```ruby
]$ ARCONN=oracle ruby -Itest test/cases/log_subscriber_test.rb -n test_basic_query_doesnt_log_when_level_is_not_debug
Using oracle
Run options: -n test_basic_query_doesnt_log_when_level_is_not_debug --seed 61000
E
Finished in 0.240198s, 4.1632 runs/s, 0.0000 assertions/s.
1) Error:
LogSubscriberTest#test_basic_query_doesnt_log_when_level_is_not_debug:
NoMethodError: undefined method `preparable' for #<Arel::Visitors::Oracle12:0x0055a67e7b4560>
/home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:36:in `select_all'
/home/yahonda/git/rails/activerecord/lib/active_record/connection_adapte …
```

Do not cache prepared statements that are unlikely to have cache hits

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb

Fixes #750 
This is not the prettiest fix, but it does fix the problem. And it adds tests to catch the various cases of default values and the emulate_booleans_from_strings setting.

Set default value of Booleans correctly

---

activerecord-oracle_enhanced-adapter.gemspec

Rails 5.0.0.beta1 is out. http://weblog.rubyonrails.org/2015/12/18/Rails-5-0-beta1/

Bump activerecord version to 5.0.0.beta1

---

spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

My apologies for such a tiny pull request. I am new to this project, and I'm just trying to dip my toe in to make sure I have the correct protocol for contributions. Please let me know if I have done something incorrectly here.
This pull request fixes a single spec that started failing in the rails 5 branch because it used some deprecated ActiveRecord syntax. Thanks.

ActiveRecord::Calculations#count no longer accepts an options hash argument

---

RUNNING_TESTS.md
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_connection_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_context_index_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_cpk_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_database_tasks_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_dirty_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_emulate_oracle_adapter_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_procedures_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_structure_dump_spec.rb
spec/spec_config.yaml.template
spec/spec_helper.rb

The specs had deprecation warnings and dead code in a few places, so I resolved them. It looks like RAILS_GEM_VERSION isn't needed anymore, so I removed that and updated RUNNING_TESTS to remove that and include info on YAML config.
One question I have is which Ruby versions 1.6.x officially supports. RUNNING_TESTS.md was way out of date and I needed to edit it anyway. so I took a guess but might be wrong, e.g. MRI 1.9.3 compatibility might still be good to test, but probably not 1.8.7 :smile: 
WDYT?

Clean up specs and test documentation

---

lib/active_record/connection_adapters/oracle_enhanced/context_index.rb
spec/active_record/connection_adapters/oracle_enhanced_context_index_spec.rb

This pull request addresses #667 when CONTAINS have `table_name.column_name` style syntax. It should also address #463.

Address ORA-00904 when context index CONTAINS has `table_name.column_name`

---

README.md

These changes are only documentation, and describe how to enable read, write and connect timeouts using `TNSNAMES` options. Also adds a tentative description on how to deal with *stuck* applications due to timeouts not being set on underlying sockets.
Originally in #730, applies to #419

Add documentation on setting read, write and connect timeouts

---

activerecord-oracle_enhanced-adapter.gemspec
lib/active_record/connection_adapters/oracle_enhanced/connection.rb
lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/quoting.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

Since Rails 5 requires a lot of changes for type casting, this pull request extracts quoting related method into  ActiveRecord::ConnectionAdapters::OracleEnhanced::Quoting

Extract ActiveRecord::ConnectionAdapters::OracleEnhanced::Quoting

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

This pull request addresses "warning: (...) interpreted as grouped expression" reported when tested with jruby.
```
$ ruby -v
jruby 9.0.4.0 (2.2.2) 2015-11-12 b9fb7aa Java HotSpot(TM) 64-Bit Server VM 25.71-b15 on 1.8.0_71-b15 +jit [linux-amd64]
```
```ruby
Using oracle
/home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:811: warning: (...) interpreted as grouped expression
/home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:812: warning: (...) interpreted as grouped expression
/home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb:126: warning: (...) interpreted as grouped expression …
```

Remove "warning: (...) interpreted as grouped expression"

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements_ext.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Migrate from ActiveRecord::ConnectionAdapters::OracleEnhancedSchemaStatementExt
to ActiveRecord::ConnectionAdapters::OracleEnhanced::SchemaStatementsExt
Also removed 'digest/sha1' had been used for generating foreign key name

Migrate from OracleEnhancedSchemaStatementExt to OracleEnhanced::SchemaStatementsExt

---

lib/activerecord-oracle_enhanced-adapter.rb

This logic was used to check if Rails 3 or lower version.

Remove version check to see if ::Rails::Railtie exists

---

activerecord-oracle_enhanced-adapter.gemspec

since Rails 5 requires ruby 2.2 or higher version
whose default source file encoding is utf-8

Remove magic comment for utf-8

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

ActiveRecord::ConnectionAdapters::DatabaseStatements#select does the same thing

Remove select method from Oracle enhanced adapter

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb

https://github.com/rsim/oracle-enhanced/issues/777
- Use code from current Rails master branch for type casting (https://github.com/rails/rails/blob/1e92fe73522b58c353746aef30c395574ec1cdaf/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L589 and https://github.com/rails/rails/blob/4d7e96910f7704e08eb193ddf47323cc71a8ab11/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb)
- Reduces test failures to 103

Fix cast_type issue

---

lib/active_record/connection_adapters/oracle_enhanced/quoting.rb

This pull request addresses ORA-01830 errors since somehow `quoted_date(value)` now includes fractional seconds. It would cause some regression since Oracle enhanced adapter needs to use : . Which will be fixed later.
```ruby
$ bundle exec rake test_oracle
...
2) Error:
RelationTest#test_first_or_create_with_invalid_array:
ActiveRecord::StatementInvalid: OCIError: ORA-01830: date format picture ends before converting entire input string: INSERT INTO "TOPICS" ("ID", "TITLE", "AUTHOR_NAME", "AUTHOR_EMAIL_ADDRESS", "WRITTEN_ON", "LAST_READ", "BONUS_TIME", "CONTENT", "APPROVED", "REPLIES_COUNT", "CREATED_AT", "UPDATED_AT") VALUES (1, 'The First Topic', 'David', 'david@loudthinking.com', TO_TIMESTAMP('2003-07-16 14:28:11.223300:223300','YYYY-MM-DD HH24:MI:SS:FF6'), …
```

Address ORA-01830 errors

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Refer https://github.com/rails/rails/pull/22620
This pull request addresses this kind of errors.
```ruby
$ bundle exec rake test_oracle
... snip ...
4) Error:
RelationTest#test_update_all_with_scope:
ArgumentError: wrong number of arguments (given 3, expected 2)
/home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:1081:in `join_to_update'
/home/yahonda/git/rails/activerecord/lib/active_record/relation.rb:384:in `update_all'
/home/yahonda/git/rails/activerecord/test/cases/relations_test.rb:1112:in `test_update_all_with_scope'
```

join_to_update argument changed to take 3rd argument

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

This pull request addresses these errors. 
Reason why it just calls super instead of removing this method itself is Oracle enhanced adapter may need to implement its own method for older version of Oracle 11gR2 or lower.
This test has been addressed when tested with Oracle database 12c, which has its own Arel visitor called Oracle12.
```ruby
$ ARCONN=oracle bundle exec ruby -W -w -I"lib:test"  test/cases/relations_test.rb
... snip ...
3) Error:
RelationTest#test_update_all_with_joins_and_offset_and_order:
NoMethodError: undefined method `name' for nil:NilClass
/home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:1087:in `join_to_update'
/home/yahonda/git/rails/activerecord/lib/active_record/relation.rb:384:in `update_all' …
```

Use Abstract adapter join_to_update

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb

This pull request addresses this kind of errors when `ActiveRecord::ConnectionAdapters::OracleEnhancedColumn` does not have `value_for_database` method.
It uses Abstract adapter's method modified in https://github.com/rails/rails/pull/23067, it may cause some regressions to Oracle enhanced adapter, then just call super instead of removing it.
```ruby
$ ARCONN=oracle bundle exec ruby -W -w -I"lib:test"  test/cases/associations/has_many_associations_test.rb
... snip ...
4) Error:
HasManyAssociationsTest#test_building_the_association_with_an_array:
NoMethodError: undefined method `value_for_database' for #<Array:0x00563b4d965e40>
/home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb:114:in `block in exec_insert' …
```

Use Abstract adapter sql_for_insert

---

lib/active_record/connection_adapters/oracle_enhanced/quoting.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

This pull request addresses this kind of ORA-01756 errors when inserting blob values.
It currently removes other type casting for timestamp. I wanted to see how Rails abstract _cast works then will update Oracle enhanced _cast method to support these types if necessary.
```ruby
$ ARCONN=oracle bundle exec ruby -W -w -I"lib:test"  test/cases/fixtures_test.rb -n test_create_symbol_fixtures
Using oracle
/home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/schema_definitions.rb:384: warning: previous definition of aliased_types was here
Run options: -n …
```

Handle BLOB type correctly

---

lib/active_record/connection_adapters/oracle_enhanced/procedures.rb

This pull request addresses these 4 failures.
```
rspec ./spec/active_record/connection_adapters/oracle_enhanced_procedures_spec.rb:193
rspec ./spec/active_record/connection_adapters/oracle_enhanced_procedures_spec.rb:207
rspec ./spec/active_record/connection_adapters/oracle_enhanced_procedures_spec.rb:226
rspec ./spec/active_record/connection_adapters/oracle_enhanced_procedures_spec.rb:305
```
```ruby
2.3.0 [ rails5 ~/git/oracle-enhanced]$ rspec ./spec/active_record/connection_adapters/oracle_enhanced_procedures_spec.rb:193
==> Running specs with MRI version 2.3.0
==> Effective ActiveRecord version 5.0.0.beta3
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_procedures_spec.rb"=>[193]}}
F
Failures:
1) …
```

Address undefined method `cast_type'

---

lib/active_record/connection_adapters/oracle_enhanced/quoting.rb

This pull request addresses this failure.
```ruby
$ rspec ./spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb:732
==> Running specs with MRI version 2.3.0
==> Effective ActiveRecord version 5.0.0.beta3
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb"=>[732]}}
F
Failures:
1) OracleEnhancedAdapter date and timestamp with different NLS date formats should quote Date values with TO_DATE
Failure/Error: expect(@conn.quote(@today)).to eq("TO_DATE('#{@today.year}-#{"%02d" % @today.month}-#{"%02d" % @today.day}','YYYY-MM-DD HH24:MI:SS')")
expected: "TO_DATE('2008-06-28','YYYY-MM-DD HH24:MI:SS')"
got: "'2008-06-28'"
(compared using ==)
Finished in 0.16617 seconds (files …
```

Restore necessary quote for Date

---

lib/active_record/connection_adapters/oracle_enhanced/column.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

Fixes #802 
3a8c0a9 addresses the undefined method error that was getting returned as a result of `@types` getting dropped.
c1856de addresses a bug caused by active record's column initialize method setting @table_name to nil.
With these changes, the schema_dumper_spec now passes.

Fix schema dumper errors

---

lib/active_record/connection_adapters/oracle_enhanced/column.rb

it had been removed from Rails before Rails 4.2.
Refer these commits:
https://github.com/rails/rails/commit/748f070895dc0d76a02a45e1be5c50ea67a79e85
https://github.com/rails/rails/commit/e781aa31fc52a7c696115302ef4d4e02bfd1533b

Remove type_cast from Column

---

Gemfile

rails5 branch still requires a lot of debug work, `byebug` should be bundled by default.

Add byebug for ruby platform

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

refer https://github.com/rails/rails/pull/18914 and https://github.com/rsim/oracle-enhanced/pull/739
This pull request supports TIME with precision and fixes these errors.
```ruby
$ ARCONN=oracle bundle exec ruby -W -w -I"lib:test" test/cases/time_precision_test.rb
Using oracle
/home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/schema_definitions.rb:384: warning: previous definition of aliased_types was here
Run options: --seed 53044
EE.EE
Finished in 0.044924s, 111.2997 runs/s, 22.2599 assertions/s.
1) Error:
TimePrecisionTest#test_formatting_time_according_to_precision: …
```

Rails :time as Oracle TIMESTAMP to support subsecond precision

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb

Refer https://github.com/rails/rails/commit/b06f64c3480cd389d14618540d62da4978918af0
This pull request addresses these ActiveRecord unit test failures and errors.
```ruby
31) Failure:
ActiveRecord::BindParameterTest#test_binds_are_logged [/home/yahonda/git/rails/activerecord/test/cases/bind_parameter_test.rb:50]:
--- expected
+++ actual
@@ -1 +1 @@
-[#<ActiveRecord::Relation::QueryAttribute:0xXXXXXX @name="id", @value_before_type_cast=1, @type=#<ActiveModel::Type::Value:0xXXXXXX @precision=nil, @scale=nil, @limit=nil>, @original_attribute=nil, @value=1, @value_for_database=1>]
+[1]
32) Error:
ActiveRecord::BindParameterTest#test_find_one_uses_binds:
NoMethodError: undefined method `value' for 1:Fixnum
/home/yahonda/git/rails/activerecord/test/cases/bind_parameter_test.rb:55:in `block (2 …
```

log binds should not be type_casted

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Since Oracle database itself does not support comment when creating table
Not implemented `supports_comments_in_create?` method, which inherits
AbstractAdapter value `false` .
Refer https://github.com/rails/rails/pull/22911 and https://github.com/rails/rails/commit/485e7f25
Note: At first this enables to run ActiveRecord tests for comments feature, it does not implement any features yet.

Enable `support_comments?` to support AR native database comment

---

lib/active_record/connection_adapters/oracle_enhanced/schema_creation.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_definitions.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

refer https://github.com/rails/rails/commit/485e7f25f29ca1ca23bb214b802cf68840dabbb6
https://github.com/rails/rails/commit/485e7f25f29ca1ca23bb214b802cf68840dabbb6
This pull request addresses this error.
```ruby
$ bundle exec rake test_oracle
... snip ...
/home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/schema_definitions.rb:212:in `initialize': unknown keyword: force (ArgumentError)
from /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb:97:in `new'
from /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb:97:in `create_table_definition'
from /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/schema_statem …
```

Use keyword arguments for new table options

---

lib/active_record/connection_adapters/oracle_enhanced/schema_definitions.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Removed duplicate instance variables called in super `ActiveRecord::ConnectionAdapters::IndexDefinition` and change the order to follow super class initialize method.

Clean up IndexDefinition to prepare comment support

---

lib/active_record/connection_adapters/oracle_enhanced/column.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb

This pull request supports ActiveRecord native comment feature.
It addresses regressions introduced by #820.
```ruby
rspec ./spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb:490 # OracleEnhancedAdapter schema dump table comments should dump table comments
rspec ./spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb:530 # OracleEnhancedAdapter schema dump table comments should dump table comments
rspec ./spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb:347 # OracleEnhancedAdapter schema definition table and column comments should create table with table comment
rspec ./spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb:369 # OracleEnhancedAdapter schema definition table and column …
```

Support ActiveRecord native comment feature

---

lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/quoting.rb

because Rails 5 will not give column to bind_param method it should be type casted here.
This pull request addreses these 7 failures in Oracle enhanced adapter unit tests and 4 errors in ActiveRecord unit tests.
```ruby
rspec ./spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb:1188 # OracleEnhancedAdapter handling of BLOB columns should create record with BLOB data
rspec ./spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb:1198 # OracleEnhancedAdapter handling of BLOB columns should update record with BLOB data
rspec ./spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb:1211 # OracleEnhancedAdapter handling of BLOB columns should update record with zero-length BLOB data
rspec …
```

Handle ActiveModel::Type::Binary::Data type cast in _type_cast

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

and supress `DEPRECATION WARNING: Passing #original_exception is deprecated and has no effect. Exceptions will automatically capture the original exception. `
Refer:
https://github.com/rails/rails/pull/23522
https://github.com/rails/rails/pull/18774
This pull request addresses this failure.
```ruby
$ ARCONN=oracle bundle exec ruby -W -w -I"lib:test" test/cases/adapter_test.rb -n test_value_limit_violations_are_translated_to_specific_exception
Using oracle
/home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:148: warning: assigned but unused variable - col_type …
```

Add `ActiveRecord::ValueTooLong` exception class

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

to support `OFFSET ... FETCH FIRST n ROWS ONLY` syntax
Refer https://github.com/rails/rails/commit/96f3f3d8267167d5d4c5697f2299756cfa7e37d4
https://github.com/rails/rails/issues/24775
It addresses 1 failure in Oracle enhanced adapter unit tests:
```ruby
2.3.1 [ rails5 ~/git/oracle-enhanced]$ rspec ./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb:741
==> Effective ActiveRecord version 5.0.0.beta4
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb"=>[741]}}
F
Failures:
1) OracleEnhancedAdapter using offset and limit should return the records starting from offset n with offset(n)
Failure/Error: …
```

Change bind parameters order to come offset first then limit next

---

lib/active_record/connection_adapters/oracle_enhanced/schema_creation.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

Refer https://github.com/rails/rails/pull/18220
https://github.com/rails/rails/pull/21614
This pull request addresses 3 failures and 3 errors of ActiveRecord unit tests.
```ruby
9) Error:
HasAndBelongsToManyAssociationsTest#test_join_table_composite_primary_key_should_not_warn:
ActiveRecord::StatementInvalid: OCIError: ORA-01400: cannot insert NULL into ("ARUNIT"."COUNTRIES_TREATIES"."[:country_id, :treaty_id]"): INSERT INTO "COUNTRIES_TREATIES" ("COUNTRY_ID", "TREATY_ID") VALUES (:a1, :a2)
stmt.c:243:in oci8lib_230.so
/home/yahonda/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/ruby-oci8-2.2.2/lib/oci8/cursor.rb:129:in `exec'
/home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:168:in `exec_update' …
```

Support for any type primary key

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Refer https://github.com/rails/rails/pull/23345
This pull request addresses this failure.
```ruby
$ ARCONN=oracle bundle exec ruby -W -w -I"lib:test" test/cases/primary_keys_test.rb -n test_primary_key_issues_warning
... snip ...
F
Finished in 1.547723s, 0.6461 runs/s, 1.9383 assertions/s.
1) Failure:
CompositePrimaryKeyTest#test_primary_key_issues_warning [test/cases/primary_keys_test.rb:268]:
Expected /WARNING: Rails does not support composite primary key\./ to match "".
1 runs, 3 assertions, 1 failures, 0 errors, 0 skips
$
```

Warn if `AR.primary_key` is called for a table with composite primary key

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

Refer https://github.com/rails/rails/pull/20018
This pull request addresses these two errors.
```ruby
$ ARCONN=oracle bundle exec ruby -W -w -I"lib:test" test/cases/invertible_migration_test.rb -n test_migrate_revert_change_column_default
... snip ...
E
Finished in 0.096858s, 10.3244 runs/s, 10.3244 assertions/s.
1) Error:
ActiveRecord::InvertibleMigrationTest#test_migrate_revert_change_column_default:
TypeError: can't quote Hash
/home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/quoting.rb:177:in `_quote'
/home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/quoting.rb:98:in `_quote'
/home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/quoting.rb:22:in `quote' …
```

Add reversible syntax for change_column_default

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

Refer
https://github.com/rails/rails/pull/19456
https://github.com/rails/rails/pull/24507
https://github.com/rails/rails/commit/c41ef01a
This pull request addresses one failure and one error:
```ruby
$ ARCONN=oracle bundle exec ruby -W -w -I"lib:test" test/cases/adapter_test.rb -n test_remove_index_when_name_and_wrong_column_name_specified
... snip 
F
Finished in 0.041258s, 24.2379 runs/s, 24.2379 assertions/s.
1) Failure:
ActiveRecord::AdapterTest#test_remove_index_when_name_and_wrong_column_name_specified [test/cases/adapter_test.rb:94]:
ArgumentError expected but nothing was raised.
1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
$
```
```ruby
$ ARCONN=oracle bundle exec ruby -W -w -I"lib:test" test/cases/migration/index_test.rb -n test_remove_named_index
... snip ...
E
Finished in …
```

Ignore index name in `index_exists?` when not passed a name to check for

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

also deprecate `#table_exists?`, `#tables` and passing arguments to `#tables`
Refer https://github.com/rails/rails/pull/21601
https://github.com/rails/rails/issues/21509
This pull request addresses these 2 failures:
```ruby
$ ARCONN=oracle bundle exec ruby -W -w -I"lib:test" test/cases/adapter_test.rb -n test_passing_arguments_to_tables_is_deprecated
/home/yahonda/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/lib/bundler/rubygems_integration.rb:468: warning: method redefined; discarding old find_spec_for_exe
/home/yahonda/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems.rb:241: warning: previous definition of find_spec_for_exe was here
Using oracle
/home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:148: warning: …
```

Introduce `data_source_exists?` to return tables and views

---

lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

This pull request follows up #841 to avoid this deprecation warning.
```ruby
DEPRECATION WARNING: #table_exists? currently checks both tables and views. This behavior is deprecated and will be changed with Rails 5.1 to only check tables. Use #data_source_exists? instead. (called from table_exists? at /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:740)
```

Replace `table_exists?` with `data_source_exists?`

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

if OracleEnhancedAdapter.emulate_booleans
This pull request addresses these 15 failures of ActiveRecord unit tests.
```ruby
4) Failure:
HasManyAssociationsTest#test_build_and_create_from_association_should_respect_passed_attributes_over_default_scope [/home/yahonda/git/rails/activerecord/test/cases/associations/has_many_associations_test.rb:221]:
Expected: false
Actual: 0
5) Failure:
HasManyThroughAssociationsTest#test_create_with_conditions_hash_on_through_association [/home/yahonda/git/rails/activerecord/test/cases/associations/has_many_through_associations_test.rb:1019]:
Expected: true
Actual: 1
17) Failure:
SchemaDumperTest#test_schema_dump_should_use_false_as_default [/home/yahonda/git/rails/activerecord/test/cases/schema_dumper_test.rb:222]:
Expected …
```

Register `NUMBER(1)` sql_type to `Type::Boolean`

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

to support fractional seconds and have better compatibility with Rails
by using Abstract Adapter implementations.
```
register_class_with_precision m, %r(datetime)i,  Type::DateTime
m.alias_type %r(timestamp)i, 'datetime'
```
Before this commit Oracle DATE sql type is associated with Rails DateTime
which does not supports fractional seconds.
* ActiveRecord unit test status:
* Fixed 3 failures
```
22) Failure:
BasicsTest#test_preserving_date_objects [/home/yahonda/git/rails/activerecord/test/cases/base_test.rb:161]:
The last_read attribute should be of the Date class.
Expected 2004-04-15 00:00:00 UTC to be a kind of Date, not Time.
25) Failure:
ActiveRecord::ConnectionAdapters::TypeLookupTest#test_date_types [/home/yahonda/git/rails/activerecord/test/cases/connection_adapters/type_lookup_te …
```

Oracle TIMESTAMP sql type is associated with Rails `DateTime` type

---

spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

https://github.com/rails/rails/pull/23048 removes `substitute_at` method from Abstract adapter.
Also bind value needs to be `ActiveRecord::Relation::QueryAttribute`.
This pull request addresses these 3 failures.
```ruby
$ rspec ./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb:630
==> Effective ActiveRecord version 5.0.0.rc1
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb"=>[630]}}
F
Failures:
1) OracleEnhancedAdapter with statement pool should clear older cursors when statement limit is reached
Failure/Error: sub = @conn.substitute_at(pk, 0).to_sql
NoMethodError:
undefined method `substitute_at' for …
```

substitute_at has been removed from Rails

---

spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb

Rails 5 introduces attribute API then column itself does not have type_cast_from_database.
It needs to be attribute which belongs to models.
Note: This commit just addresses undefined method `type_cast_from_database'.
Each failure due to expected class name difference needs addressed later.
This pull request addresses 7 undefined method `type_cast_from_database' errors.
```ruby
$ rspec ./spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb:65
==> Effective ActiveRecord version 5.0.0.rc1
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb"=>[65]}}
F
Failures:
1) OracleEnhancedAdapter date type detection based on column names …
```

Address undefined method `type_cast_from_database' 

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Follow up for #853 since `visitor` instance variable is set at AbstractAdapter initialize method.

No need to set @visitor instance variable here

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Refer https://github.com/rails/rails/pull/21720/

Deprecate `ignore_table_columns` to use Rails native `ignored_columns`

---

spec/active_record/connection_adapters/oracle_enhanced_connection_spec.rb

```ruby
$ rspec ./spec/active_record/connection_adapters/oracle_enhanced_connection_spec.rb:252
==> Effective ActiveRecord version 5.0.0.rc1
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_connection_spec.rb"=>[252]}}
F
Failures:
1) OracleEnhancedConnection SQL with bind parameters when NLS_NUMERIC_CHARACTERS is set to ', ' should execute prepared statement with decimal bind parameter
Failure/Error: @object_type = sql_type_metadata.sql_type.include? '.'
NoMethodError:
undefined method `sql_type' for #<ActiveModel::Type::Decimal:0x0056245d23d868>
Finished in 0.0809 seconds (files took 0.92262 seconds to load)
1 …
```

OracleEnhancedColumn.new needs sql_type_metadata including sql_type

---

spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb

This pull request reverts #850 and use `lookup_cast_type_from_column` to get the expected type.
* <Model>.type_for_attribute(column) is not the expected type, `ActiveModel::Type::Value`
```ruby
[82, 91] in /home/yahonda/git/oracle-enhanced/spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb
82:     ActiveRecord::ConnectionAdapters::OracleEnhancedAdapter.emulate_dates_by_column_name = true
83:     columns = @conn.columns('test_employees')
84:     column = TestEmployee.columns.detect{|c| c.name == "hire_date"}
85:     require 'byebug'
86:     byebug
=> 87:     expect(TestEmployee.type_for_attribute(column).cast(Time.now).class).to eq(Date)
88:   end
89:
90:   it "should typecast DateTime value to Date value from DATE column if column name contains 'date' and …
```

Use `lookup_cast_type_from_column` to get the expected type

---

lib/active_record/connection_adapters/oracle_enhanced/schema_creation.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

This pull request support creating foreign keys in create table statement. Refer https://github.com/rails/rails/pull/20009
Due to Oracle implementation differences with other Rails bundled adapter supported databases, it needs separate 'create sequence' then this test still shows a failure but number of sql statement executed changed from 3 to 2.
* Without this commit. There is a separate "ALTER TABLE ... ADD CONSTRAINT ... FOREIGN KEY" sql statement executed.
```ruby
$ ARCONN=oracle bundle exec ruby -W -w -I"lib:test" test/cases/migration/references_foreign_key_test.rb -n test_foreign_keys_can_be_created_in_one_query_when_index_is_not_added
... snip ...
F
Finished in 0.103950s, 9.6200 runs/s, 9.6200 assertions/s.
1) Failure:
ActiveRecord::Migration::ReferencesForeignKeyTest#test_foreign_k …
```

Support creating foreign keys in create table

---

lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb

Follow up #695. alias_method_chain here has been unnecessary since #695.

Remove alias_method_chain and rename oracle_enhanced_table to table

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb

Refer https://github.com/rails/rails/pull/23086
This pull request addresses some part of this error.
* Without this commit
```ruby
$ ARCONN=oracle bundle exec ruby -W -w -I"lib:test" test/cases/database_statements_test.rb -n test_insert_update_delete_sql_is_deprecated
... Snip ...
E
Finished in 0.003506s, 285.2287 runs/s, 0.0000 assertions/s.
1) Error:
DatabaseStatementsTest#test_insert_update_delete_sql_is_deprecated:
NoMethodError: protected method `insert_sql' called for #<ActiveRecord::ConnectionAdapters::OracleAdapter:0x00562ad52a5c00>
Did you mean?  insert
test/cases/database_statements_test.rb:17:in `block in test_insert_update_delete_sql_is_deprecated'
/home/yahonda/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.rc2/lib/active_support/testing/deprecation.rb:29:i …
```

Rename `insert_sql` to `exec_insert`

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

forcing cast_type will not work in Rails 5 since cast_type is replaced with type_metadata
Similar features will be available using Rails 5 Attribute API
http://edgeapi.rubyonrails.org/classes/ActiveRecord/Attributes/ClassMethods.html#method-i-attribute

Remove cast_type to support Rails 5 Attribute API

---

spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb

to support Rails 5 Attribute API.
- skip (xit) specs checking columns (not attributes) without creating models
- Use attribute method to set non default type
- Remove `emulate_dates_by_column_name` from specs
- Remove `set_date_columns` from specs
- Remove `set_datetime_columns` from specs
It addresses following failures.
```ruby
$ rspec spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb:3
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb"=>[3]}}
F.FFF..F..F...FF
Failures:
1) OracleEnhancedAdapter date type detection based on column names should set DATE column type as datetime …
```

Update "OracleEnhancedAdapter date type detection based on column names"

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb

Follow up for #868 which has removed `set_date_columns and `set_datetime_columns` from specs

Deprecate `set_date_columns` and `set_datetime_columns`

---

spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb

to support Rails 5 Attribute API.
- skip (xit) specs checking columns (not attributes) without creating models
- Use attribute method to set non default type
- Remove `emulate_integers_by_column_name` from specs
- Remove `emulate_booleans` from specs
It addresses following failures.
```ruby
$ rspec ./spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb:206
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb"=>[206]}}
.F..F.F..F.FF
Failures:
1) OracleEnhancedAdapter integer type detection based on column names should set NUMBER column type as integer if …
```

Update "OracleEnhancedAdapter integer type detection based on column names"

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Use Rails attribute API for each model.
Follow up for #871

Deprecate `set_integer_columns

---

spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb

to support Rails 5 Attribute API.
- skip (xit) specs checking columns (not attributes) without creating models
- Use attribute method to set non default type
- Remove `set_string_columns` from specs
- Remove `set_boolean_columns` from specs
- Partially removed `emulate_booleans_from_strings` from specs
since `quoted_true` and `quoted_false` rely on it yet
Without this commit:
```ruby
$ rspec ./spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb:367
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb"=>[367]}}
.F..F....F.F.F.
Failures:
1) OracleEnhancedAdapter boolean type detection …
```

Update "OracleEnhancedAdapter boolean type detection based on stringcolumn types and names"

---

spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb

* In Rails 5.0
Oracle TIMESTAMP sql type is associated with Rails `DateTime` type.
also Oracle DATE sql type is associated with Rails `Date` type
by inheriting Abstract adapter implementation.
Refer https://github.com/rsim/oracle-enhanced/pull/845
* In Rails 4.2 or lower version it was
Oracle DATE sql type is associated with Rails `DateTime` type.
This pull request addresses following failures:
```ruby
$ rspec ./spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb:792
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb"=>[792]}}
....FFFFF
Failures:
1) OracleEnhancedAdapter assign …
```

Explicitly set :datetime for an attribute

---

lib/active_record/connection_adapters/oracle_enhanced/quoting.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_definitions.rb
lib/active_record/oracle_enhanced/type/raw.rb

This pull request addresses these failures.
```ruby
$ rspec ./spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb:1327
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb"=>[1327]}}
FF.FFFF
Failures:
1) OracleEnhancedAdapter handling of RAW columns should create record with RAW data
Failure/Error: @raw_cursor.exec
OCIError: ORA-01465: invalid hex number: INSERT INTO "TEST_EMPLOYEES" ("FIRST_NAME", "LAST_NAME", "BINARY_DATA", "EMPLOYEE_ID") VALUES (:a1, :a2, :a3, :a4)
2) OracleEnhancedAdapter handling of RAW columns should update record with RAW data …
```

Support RAW sql data type in Rails 5

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

This pull request addresses these 2 failures:
It is kind of follow up for #804 which removed this logic since `column` itself does not have `cast_type` method. 
```ruby
$ rspec ./spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb:1162 
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb"=>[1162]}}
F
Failures:
1) OracleEnhancedAdapter handling of CLOB columns should store serializable ruby data structures
Failure/Error: expect(@employee.comments).to eq(ruby_data2)
expected: {"arbitrary2"=>["ruby", :data, 123]}
got: "{\"arbitrary2\"=>[\"ruby\", :data, 123]}\n"
(compared using ==) …
```

Serialize value for lob columns

---

lib/active_record/connection_adapters/oracle_enhanced/quoting.rb
spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb

This pull request reverts #799 and #808. 
Also deprecate `quote_date_with_to_date` and `quote_timestamp_with_to_timestamp` methods. Since these two methods are not called from [`_quote`](https://github.com/rails/rails/blob/5-0-stable/activerecord/lib/active_record/connection_adapters/abstract/quoting.rb#L163-L179)

deprecate `quote_date_with_to_date` and `quote_timestamp_with_to_timestamp`

---

lib/active_record/connection_adapters/oracle_enhanced/schema_creation.rb

for `quote_default_expression`
No need to separate for :text which is mapped for CLOB sql data type.
This pull request addresses this error:
```ruby
$ ARCONN=oracle bundle exec ruby -W -w -I"lib:test" test/cases/migration/change_schema_test.rb -n test_create_table_with_defaults
... snip ...
E
Finished in 0.101438s, 9.8582 runs/s, 0.0000 assertions/s.
1) Error:
ActiveRecord::Migration::ChangeSchemaTest#test_create_table_with_defaults:
ArgumentError: wrong number of arguments (given 1, expected 2)
/home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/quoting.rb:105:in `quote_default_expression'
/home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/schema_creation.rb:17:in `quote_default_expression' …
```

Address ArgumentError: wrong number of arguments (given 1, expected 2)

---

spec/active_record/connection_adapters/oracle_enhanced_procedures_spec.rb

This reverts commit 110db8180d9e6af8759d71a6139ab7a7b1038f56.
It addresses this failure by reverting #653. Due to rspec 3 upgrade this revert needed to address conflicts.
```ruby
$ rspec ./spec/active_record/connection_adapters/oracle_enhanced_procedures_spec.rb:320
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_procedures_spec.rb"=>[320]}}
F
Failures:
1) OracleEnhancedAdapter custom methods for create, update and destroy should log create record
Failure/Error: expect(@logger.logged(:debug)[-2]).to match(/^TestEmployee Create \(\d+\.\d+(ms)?\)  custom create method$/)
expected "(19.3ms)  SELECT cols.column_name AS …
```

Revert "Update matcher to skip sql statements to get `table` metadata"

---

activerecord-oracle_enhanced-adapter.gemspec
lib/active_record/connection_adapters/oracle_enhanced/column.rb
lib/active_record/connection_adapters/oracle_enhanced/quoting.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
lib/active_record/oracle_enhanced/type/national_character_string.rb
spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb

```ruby
$ rspec ./spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb:1493
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb"=>[1493]}}
DEPRECATION WARNING: Passing a column to `quote` has been deprecated. It is only used for type casting, which should be handled elsewhere. See https://github.com/rails/arel/commit/6160bfbda1d1781c3b08a33ec4955f170e95be11 for more information. (called from quote at /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/quoting.rb:88)
F
Failures:
1) OracleEnhancedAdapter quoting …
```

Support Oracle national character set NCHAR, NVARCHAR2

---

activerecord-oracle_enhanced-adapter.gemspec
lib/active_record/connection_adapters/oracle_enhanced/quoting.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_creation.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
lib/active_record/oracle_enhanced/type/text.rb

This pull request addresses these 4 failures:
```ruby
rspec ./spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb:1096 # OracleEnhancedAdapter handling of CLOB columns should update record with zero-length CLOB data
rspec ./spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb:1135 # OracleEnhancedAdapter handling of CLOB columns should update record that has existing CLOB data with zero-length CLOB data
rspec ./spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb:1148 # OracleEnhancedAdapter handling of CLOB columns should update record that has zero-length CLOB data with non-empty CLOB data
rspec ./spec/active_record/connection_adapters/oracle_enhanced_dirty_spec.rb:83 # OracleEnhancedAdapter dirty object tracking should …
```

Use ActiveRecord::OracleEnhanced::Type::Text

---

lib/active_record/oracle_enhanced/type/text.rb

```ruby
2.3.1 [ rails5 ~/git/oracle-enhanced]$ rspec ./spec/active_record/connection_adapters/oracle_enhanced_dirty_spec.rb:74
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_dirty_spec.rb"=>[74]}}
F
Failures:
1) OracleEnhancedAdapter dirty object tracking should not mark empty text (stored as empty_clob()) as changed when reassigning it
Failure/Error: expect(@employee).not_to be_changed
expected `#<TestEmployee id: #<BigDecimal:55a5b39a75a0,'0.1E1',9(27)>, first_name: nil, last_name: nil, job_id: nil, salary: nil, comments: "", hire_date: nil>.changed?` to return false, got true …
```

Address dirty object tracking should not mark empty text as changed

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb

This pull request reverts #866 and remove `exec_insert` method, which is not used (at least) Rails 4.2.

Remove insert_sql method

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb

This pull request addresses these 4 failures:
```ruby
rspec ./spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb:206 # OracleEnhancedAdapter schema definition create table with primary key trigger with default primary key should return new key value using connection insert method
rspec ./spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb:245 # OracleEnhancedAdapter schema definition create table with primary key trigger with separate creation of primary key trigger should return new key value using connection insert method
rspec ./spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb:278 # OracleEnhancedAdapter schema definition create table with primary key trigger with non-default primary key and …
```

Support "limited" :returning_id

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb

This pull request addresses this failure when tested with `jruby-9.1.2.0` .
```ruby
$ rspec ./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb:684 # OracleEnhancedAdapter explain should explain query with binds
==> Running specs with JRuby version 9.1.2.0
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb"=>[684]}}
F
Failures:
1) OracleEnhancedAdapter explain should explain query with binds
Failure/Error: Unable to find oracle.jdbc.driver.OraclePreparedStatement.setLongInternal(oracle/jdbc/driver/OraclePreparedStatement.java to read failed line
Java::JavaSql::SQLException: Invalid column index: …
```

Support explain for jruby

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb

This reverts commit aaa7d4fc9eed65f3bed1157a0483ab258afae972.
Since it causes this regression:
```ruby
jruby-9.1.2.0 [ rails5 ~/git/oracle-enhanced]$ rspec ./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb:678
uri:classloader:/jruby/kernel/jruby/process_manager.rb:28: warning: executable? does not in this environment and will return a dummy value
uri:classloader:/jruby/kernel/jruby/process_manager.rb:28: warning: executable? does not in this environment and will return a dummy value
uri:classloader:/jruby/kernel/jruby/process_manager.rb:28: warning: executable? does not in this environment and will return a dummy value
uri:classloader:/jruby/kernel/jruby/process_manager.rb:28: warning: executable? does not in this environment and will return a dummy value …
```

Revert "Support explain for jruby"

---

spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb
spec/spec_helper.rb

Since Rails 4 this value changed from :local to :utc
https://github.com/rails/rails/pull/4573
There are 7 specs which explicitly need
to set `ActiveRecord::Base.default_timezone = :local`

Remove `ActiveRecord::Base.default_timezone = :local` from spec_helper

---

activerecord-oracle_enhanced-adapter.gemspec

This pull request adddresses this build errror when `bundle` executed using jruby
```ruby
$ ruby -v
jruby 9.1.2.0 (2.3.0) 2016-05-26 7357c8f Java HotSpot(TM) 64-Bit Server VM 25.92-b14 on 1.8.0_92-b14 +jit [linux-x86_64]
$ bundle
...
Installing ruby-oci8 2.2.2 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
current directory: /home/yahonda/.rbenv/versions/jruby-9.1.2.0/lib/ruby/gems/shared/gems/ruby-oci8-2.2.2/ext/oci8
/home/yahonda/.rbenv/versions/jruby-9.1.2.0/bin/jruby -r ./siteconf20160715-24905-1we1ee5.rb extconf.rb
NotImplementedError: C extensions are not supported
<top> at /home/yahonda/.rbenv/versions/jruby-9.1.2.0/lib/ruby/stdlib/mkmf.rb:1
require at org/jruby/RubyKernel.java:944
(root) at …
```

add_dependency with ruby-oci8 only if it runs cruby, not jruby

---

lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/jdbc_quoting.rb

This pull request addresses these 7 failures:
```ruby
$ rspec ./spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb:1213
uri:classloader:/jruby/kernel/jruby/process_manager.rb:28: warning: executable? does not in this environment and will return a dummy value
uri:classloader:/jruby/kernel/jruby/process_manager.rb:28: warning: executable? does not in this environment and will return a dummy value
uri:classloader:/jruby/kernel/jruby/process_manager.rb:28: warning: executable? does not in this environment and will return a dummy value
uri:classloader:/jruby/kernel/jruby/process_manager.rb:28: warning: executable? does not in this environment and will return a dummy value
uri:classloader:/jruby/kernel/jruby/process_manager.rb:28: warning: executable? does not in this …
```

Move `ruby_to_java_value` logic to `_type_cast`

---

activerecord-oracle_enhanced-adapter.gemspec

to meet the same ruby version as Rails 5.0.0 does.

Set required_ruby_version  = '>= 2.2.2'

---

Gemfile

then it should point `5-0-stable` branch

Oracle enhanced adapter 1.7 target version is Rails 5.0

---

lib/active_record/connection_adapters/oracle_enhanced/schema_definitions.rb

It is kind of reverting https://github.com/rsim/oracle-enhanced/commit/c1722f0001a894d2f9899038e999ab41acebbe3b done in #575
Since Oracle enhanced adapter 1.7 does not have its own :timestamp datatype implementation by #815
this overriding code is not necessary anymore.
It eliminates these warnings.
```ruby
/home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/schema_definitions.rb:390: warning: previous definition of aliased_types was here
```

Remove ActiveRecord::ConnectionAdapters::TableDefinition#aliased_types

---

spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_structure_dump_spec.rb

This pull request removes specs for composite primary keys skipped in #632
```ruby
$ rake spec
... snip ...
2) OracleEnhancedAdapter schema dump foreign key constraints should include composite foreign keys
3) OracleEnhancedAdapter schema definition foreign key constraints should add a composite foreign key
4) OracleEnhancedAdapter schema definition foreign key constraints should add a composite foreign key with name
5) OracleEnhancedAdapter structure dump structure dump should dump composite foreign keys
```

Remove specs for composite primary keys, which is not supported

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

refer https://github.com/rails/rails/pull/25578
```ruby
$ ARCONN=oracle bundle exec ruby -W -w -I"lib:test" test/cases/primary_keys_test.rb -n test_primary_key_issues_warning
... snip ...
F
Finished in 0.125439s, 7.9720 runs/s, 23.9161 assertions/s.
1) Failure:
CompositePrimaryKeyTest#test_primary_key_issues_warning [test/cases/primary_keys_test.rb:274]:
Expected /WARNING: Active Record does not support composite primary key\./ to match "WARNING: Rails does not support composite primary key.\n\nbarcodes has composite primary key. Composite primary key is ignored.\n".
1 runs, 3 assertions, 1 failures, 0 errors, 0 skips
$
```

Update waning message for composite primary keys

---

lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb

This pull request removes this warning by folllowing `OracleEnhancedJDBCConnection` style for `bind_param` method implementation.
```ruby
/home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:148: warning: assigned but unused variable - col_type
```

Remove unused col_type to avoid warnings

---

spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb

```ruby
warning: `+' after local variable or literal is interpreted as binary operator
warning: even though it seems like unary operator
```

Remove warnings for + when tested with JRuby 9.1.2

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb

This pull request follows up #894 which just supported returning_id only for CRuby.
It addresses these 5 failures below:
```ruby
$ rspec ./spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb:206
==> Running specs with JRuby version 9.1.2.0
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb"=>[206]}}
F
Failures:
1) OracleEnhancedAdapter schema definition create table with primary key trigger with default primary key should return new key value using connection insert method
Failure/Error: Unable to find oracle.jdbc.driver.OraclePreparedStatement.setupDbaBindBuffers(oracle/jdbc/driver/OraclePreparedStatement.java …
```

Call `bind_returning_param` when sql has returning_id and using JRuby

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb

This pull request addresses 4 failures. The error messages of CRuby and JRuby are different then it will show both output. It addresses #907 and #912 
```ruby
rspec ./spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb:211 # OracleEnhancedAdapter schema definition create table with primary key trigger with default primary key should create new record for model
rspec ./spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb:250 # OracleEnhancedAdapter schema definition create table with primary key trigger with separate creation of primary key trigger should create new record for model
rspec ./spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb:283 # OracleEnhancedAdapter schema definition create table with …
```

Use binds.size to set returning_id_index for returning_id

---

spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb

This pull request suppresses these 6 RSpec warnings:
```ruby
WARNING: Using the `raise_error` matcher without providing a specific error or message risks false positives, since `raise_error` will match when Ruby raises a `NoMethodError`, `NameError` or `ArgumentError`, potentially allowing the expectation to pass without even executing the method you are intending to call. Actual error raised was #<ArgumentError: New table name 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' is too long; the limit is 30 characters>. Instead consider providing a specific error class or message. This message can be suppressed by setting: `RSpec::Expectations.configuration.on_potential_false_positives = :nothing`. Called from /home/yahonda/git/oracle-enhanced/spec/active_record/connection_adapters/oracle_enhanced_schema_st …
```

Address RSpec WARNINGS for using the `raise_error` matcher without providing a specific error or message

---

lib/active_record/connection_adapters/oracle_enhanced/procedures.rb

This pull request addresses 2 of 3 failures reported in #906 .
```ruby
rspec ./spec/active_record/connection_adapters/oracle_enhanced_procedures_spec.rb:239 # OracleEnhancedAdapter custom methods for create, update and destroy should update record if nothing is changed and partial writes are disabled
rspec ./spec/active_record/connection_adapters/oracle_enhanced_procedures_spec.rb:331 # OracleEnhancedAdapter custom methods for create, update and destroy should log update record
```
```ruby
$ rspec ./spec/active_record/connection_adapters/oracle_enhanced_procedures_spec.rb:239
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced …
```

Use attributes.keys to update all attributes when partial_write is disabled

---

spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

Skip one spec until #848 fixed.

Skip `using offset and limit should return the records` when database version is 11gR2 or lower

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb

These methods should not be executed since setting specific attributes for columns.
They have been replaced by Rails attribute API for attributes, not for columns.

Deprecate `set_type_for_columns`, `set_type_for_columns` and `clear_types_for_columns`

---

lib/active_record/connection_adapters/oracle_enhanced/quoting.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb

It addresses some of #942. since specs itself need changed but this setting is working by creating new application.

Support `emulate_booleans_from_strings` in Rails 5

---

lib/active_record/connection_adapters/oracle_enhanced/quoting.rb

refer rails/rails#25408
This pull request addresses a following failure.
```ruby
$ ARCONN=oracle bundle exec ruby -W -w -I"lib:test" test/cases/quoting_test.rb -n test_quote_returns_frozen_string
... snip ...
Using oracle
Run options: -n test_quote_returns_frozen_string --seed 8961
F
Finished in 0.003497s, 285.9946 runs/s, 285.9946 assertions/s.
1) Failure:
ActiveRecord::ConnectionAdapters::QuoteBooleanTest#test_quote_returns_frozen_string [test/cases/quoting_test.rb:159]:
Expected "1" to be frozen?.
1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
$
```
* Environment
```
* Rails master branch
* Oracle enhanced adapter `rails51` branch
* Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
* ruby 2.4.0dev (2016-08-04 trunk 55812) [x86_64-linux]
```

Quoting booleans should return a frozen string

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

for logging bind values properly
refer rails/rails#25886
This pull request addresses these 3 failures:
```ruby
$ ARCONN=oracle bundle exec ruby -W -w -I"lib:test" test/cases/log_subscriber_test.rb
... snip ...
Using oracle
Run options: --seed 62600
.....FF..F......
Finished in 0.268538s, 59.5819 runs/s, 521.3415 assertions/s.
1) Failure:
LogSubscriberTest#test_binary_data_hash [test/cases/log_subscriber_test.rb:222]:
Expected /<7 bytes of binary data>/ to match "(5.7ms)  SELECT cols.column_name AS name, cols.data_type AS sql_type, cols.data_default, cols.nullable, cols.virtual_column, cols.hidden_column, cols.data_type_owner AS sql_type_owner, DECODE(cols.data_type, 'NUMBER', data_precision, 'FLOAT', data_precision, 'VARCHAR2', DECODE(char_used, 'C', char_length, data_length), 'RAW', …
```

Pass `type_casted_binds` to log subscriber

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

- Methods removed:
`self.set_date_columns`
`self.set_datetime_columns`
`self.set_boolean_columns`
`self.set_integer_columns`
`self.set_string_columns`
`set_type_for_columns`
`get_type_for_column`

Remove deprecated methods to get and set columns

---

lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced_procedures_spec.rb

Although no deprecate message shown but it should not be necessary anymore
after Rails 5 by using Rails attribute API.

Remove `self.emulate_dates` and `self.emulate_dates_by_column_name`

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

Remove `dump_schema_information` and `initialize_schema_migrations_table` from Oracle enhanced adapter since they just call super.

Remove `dump_schema_information` and `initialize_schema_migrations_table`

---

lib/active_record/connection_adapters/oracle_enhanced/column.rb

and `string_to_date_or_time_using_format` from Oracle enhanced adapter
Since rails/rails#15207 first of these two methods have gone from `ActiveRecord::ConnectionAdapters::Column` in Rails 4.2. The third one is called from first two.

Deprecate `fallback_string_to_date`, `fallback_string_to_time`

---

lib/active_record/connection_adapters/oracle_enhanced/column.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb

and `string_to_date_or_time_using_format` from Oracle enhanced adapter
Also removed these variables:
`ActiveRecord::ConnectionAdapters::OracleEnhancedAdapter.string_to_date_format`
`ActiveRecord::ConnectionAdapters::OracleEnhancedAdapter.string_to_date_format`
Refer #974

Remove `fallback_string_to_date`, `fallback_string_to_time`

---

lib/active_record/connection_adapters/oracle_enhanced/quoting.rb
spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb

also removed Oracle enhanced own `quote` method which just calls super.

Address DEPRECATION WARNING: Passing a column to `quote` has been deprecated.

---

spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

Oracle enhanced adapter itself does not have implementation anymore.
It can be validated by running Rails ActiveRecord unit tests.
Refer https://github.com/rsim/oracle-enhanced/commit/5845789a0ffc555fe28131333d5e23af4c345588

Remove specs testing Rails `self.ignored_columns` features

---

spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb

They have been tested at ActiveRecord unit tests:
ActiveRecord::Migration::ForeignKeyTest#test_add_foreign_key_with_prefix
ActiveRecord::Migration::ForeignKeyTest#test_add_foreign_key_with_suffix
Refer #639 rails/rails#20689 and rails/rails#20699

Remove `add_foreign_key` specs with `table_name_prefix` and `table_name_suffix`

---

spec/active_record/connection_adapters/oracle_enhanced_dirty_spec.rb

Use Rails migration `create_table` to create table and sequence for dirty object tracking specs.
Not executing SQL statements to create table and sequence.
* SQL statements executed after this commit:
```sql
CREATE TABLE "TEST_EMPLOYEES" ("ID" NUMBER(38) NOT NULL PRIMARY KEY, "FIRST_NAME" VARCHAR2(20), "LAST_NAME" VARCHAR2(25), "JOB_ID" NUMBER(6) NULL, "SALARY" DECIMAL(8,2), "COMMENTS" CLOB, "HIRE_DATE" DATE)
CREATE SEQUENCE "TEST_EMPLOYEES_SEQ" START WITH 10000
```
* SQL statements executed before this commit:
```sql
CREATE TABLE test_employees (
id            NUMBER PRIMARY KEY,
first_name    VARCHAR2(20),
last_name     VARCHAR2(25),
job_id        NUMBER(6,0) NULL,
salary        NUMBER(8,2),
comments      CLOB,
hire_date     DATE
)
CREATE SEQUENCE test_employees_seq  MINVALUE 1 …
```

Use Rails migration `create_table` to create table and sequence

---

README.md
activerecord-oracle_enhanced-adapter.gemspec

This pull request addresses #992

Remove ruby oci8 runtime dependency from gemfile

---

lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb
spec/active_record/connection_adapters/oracle_enhanced_connection_spec.rb
spec/spec_helper.rb

This pull request addresses #755 .
Also it addressed these 3 failures:
```ruby
$ ARCONN=oracle bundle exec ruby -Itest test/cases/finder_test.rb -n test_hash_condition_local_time_interpolation_with_default_timezone_utc
Using oracle
Run options: -n test_hash_condition_local_time_interpolation_with_default_timezone_utc --seed 33869
F
Finished in 0.906743s, 1.1028 runs/s, 1.1028 assertions/s.
1) Failure:
FinderTest#test_hash_condition_local_time_interpolation_with_default_timezone_utc [test/cases/finder_test.rb:847]:
--- expected
+++ actual
@@ -1 +1 @@
-#<Topic id: 1, title: "The First Topic", author_name: "David", author_email_address: "david@loudthinking.com", written_on: "2003-07-16 14:28:11", bonus_time: "2005-01-30 14:28:00", last_read: "2004-04-15", content: "Have a nice day", …
```

Respect `default_timezone = :utc` rather than connection `time_zone` value

---

Gemfile

This pull request addresses these git warnings since `Bundler version 1.13.1`.
```ruby
The git source `git://github.com/rails/rails.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
```
Refer https://github.com/bundler/bundler/pull/4127 for this fix.

Address git warnings:

---

Gemfile
activerecord-oracle_enhanced-adapter.gemspec

to include this fix https://github.com/rails/arel/commit/8813ad86caec6ba8cfe0ff0c13a8cfdb7a2e8ba5
Also Refer
https://github.com/rails/arel/pull/450
https://github.com/rails/arel/issues/438
https://github.com/rsim/oracle-enhanced/issues/848
This fix itself has been available since Arel 7.1.3 but the latest version of Arel is 7.1.4.

Bump Arel 7.1.4 or higher

---

Gemfile

It removes dependency with json 1.8.3, which is not compatible
with ruby 2.4.0.

Use rdoc 5.0.0.beta2 or higher to support ruby 2.4.0.preview2

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb

* With this commit:
```sql
ALTER TABLE "FK_TEST_HAS_FK" DISABLE CONSTRAINT "FK_NAME"
ALTER TABLE "FK_TEST_HAS_FK" ENABLE CONSTRAINT "FK_NAME"
```
* Without this commit:
```sql
ALTER TABLE FK_TEST_HAS_FK DISABLE CONSTRAINT FK_NAME
ALTER TABLE FK_TEST_HAS_FK ENABLE CONSTRAINT FK_NAME
```
Refer #1012

Quote table name in disable_referential_integrity

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Dump schema migration versions with multiple SQL statement. Otherwise rails default adapter tries to add all version to single SQL statement which does not work with Oracle.
Should not affect any other functionality.

Multi insert is not supported

---

spec/active_record/connection_adapters/oracle_enhanced_procedures_spec.rb

Since #756 b9e79a6774f3b8d213412971bc06e50677b07b09 has overwritten by #707 when rails5 merged to master branch
```ruby
$ rspec ./spec/active_record/connection_adapters/oracle_enhanced_procedures_spec.rb:177
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_procedures_spec.rb"=>[177]}}
F
Failures:
1) OracleEnhancedAdapter custom methods for create, update and destroy should rollback record when exception is raised in after_create callback
Failure/Error: expect(@employee.id).to eq(nil)
expected: nil
got: 1
(compared using ==)
Finished in 0.41609 seconds (files took 1.11 seconds to …
```

Address #955

---

spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb

Since Rails 5 and Oracle enhanced adapter
Oracle `DATE` columns are mapped to Rails `:date` attribute by default.
No need to set attribute explicitly and no need to test here.

Remove specs which set `attribute :hire_date, :date`

---

lib/activerecord-oracle_enhanced-adapter.rb

I'm using this gem in a sinatra app with ActiveRecord out of the Rails box.
I think it's worth to keep a `if defined?(Rails)` condition before `OracleEnhancedRailtie` definition for those like me who want to use this great gem in non-rails apps.

Using the gem in non-rails apps

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

This pull request address `Java::JavaSql::SQLException: Missing IN or OUT parameter at index:: 3:` when `offset` and `limit` used at the same time with JRuby and Oracle 11gR2 or lower.
Since https://github.com/rails/arel/pull/450 needs 3 bind variables,
`:a1`, `:a2` and `:a1` again. It is probably due to Oracle enhanced adapter
JDBC implementation handles bind variables by their order, not their name.
Then we need to handle first `:a1` for `offset` and last `:a1` separately.
It addresses #1030 and this spec failure.
```ruby
rspec ./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb:742 # OracleEnhancedAdapter using offset and limit should return the records starting from offset n with offset(n)
```
```ruby
2) OracleEnhancedAdapter using offset and limit should return …
```

Address `Java::JavaSql::SQLException: Missing IN or OUT parameter at index:: 3:`

---

.travis.yml
spec/support/create_oracle_enhanced_users.sql

and set `database default tablespace` to USERS, not SYSTEM

Remove DATABASE_NON_DEFAULT_TABLESPACE from travis.yml

---

README.md
RUNNING_TESTS.md
lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb
spec/active_record/connection_adapters/oracle_enhanced_connection_spec.rb

We are trying to move our Rails apps to stick to using environment variables for configuration, and noticed that we could not put a connection string in the url.
To solve this, I added a simple addition to support putting a connection-string in the URL (as the path), when the host is `connection-string`. This change seemed fairly simple and unlikely to break existing configurations, but I'm open to other ways to pick up on the connection string from there.

Support connection strings in DATABASE_URL

---

spec/active_record/connection_adapters/oracle_enhanced_connection_spec.rb

Follow up for #1032 to support non-default  `DATABASE_HOST`, `DATABASE_PORT` and `DATABASE_NAME` values.
i.e this pull request addresses this failure when `DATABASE_NAME` is `ORCL` not `xe`
```ruby
[yahonda@li127-48 oracle-enhanced (master)]$ rspec ./spec/active_record/connection_adapters/oracle_enhanced_connection_spec.rb:146
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_connection_spec.rb"=>[146]}}
F
Failures:
1) OracleEnhancedConnection with host="connection-string" uses the database param as the connection string
Failure/Error: conn = OCI8.new username, password, connection_string, privilege
OCIError:
ORA-12514: …
```

Use `DATABASE_HOST`, `DATABASE_PORT` and `DATABASE_NAME` for specs

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb

Fix #1027 
This product code fix the additional following error.
```
Failures:
1) OracleEnhancedAdapter context index Use ActiveRecord::ConnectionAdapters::OracleEnhancedAdapter.default_tablespaces should store index
of primary key to TS_INDEX
Failure/Error: expect(@conn.select_value("SELECT tablespace_name FROM user_indexes WHERE index_name = '#{index_name}'")).to
eq('TS_INDEX')
expected: "TS_INDEX"
got: "TS_DATA"
```

Alter primary key rebuild tablespace

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

This pull request addresses #942 . To use attribute API in each model, the type needs registered explicitly.  Thanks @sgrif for your support.
```ruby
$ rspec ./spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb:355
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb"=>[355]}}
.F.F.
Failures:
1) OracleEnhancedAdapter boolean type detection based on string column types and names / VARCHAR2 boolean values from ActiveRecord model should return boolean value from VARCHAR2 boolean column if emulate_booleans_from_strings is true
Failure/Error: expect(@employee3.send(col.to_sym).class).to …
```

Register `:boolean` type for Attribute API

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

This pull request implements a workaround for #920 by allowing Rails 5 and Oracle database 12 users to fall back to use old Oracle visitor by setting this line in their initializer file.
```ruby
ActiveRecord::ConnectionAdapters::OracleEnhancedAdapter.use_old_oracle_visitor = true
```

Introduce `use_old_oracle_visitor` to choose old Oracle visitor

---

lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb
spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb

Ruby 2.4.0 unifies Fixnum and Bignum into Integer.
https://bugs.ruby-lang.org/issues/12005
Fix following deprecated warnings in Ruby 2.4.0-preview3.
```
warning: constant ::Fixnum is deprecated
warning: constant ::Bignum is deprecated
```
Thanks.

Fix deprecated warnings in Ruby 2.4.0+

---

spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb

This pull request addresses failures #1048 when tested with Ruby 2.3 or lower.
```ruby
$ ruby -v
ruby 2.3.2p217 (2016-11-15 revision 56796) [x86_64-linux]
$ rspec ./spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb
==> Running specs with MRI version 2.3.2
.........FF.F.FF........-- create_table(:posts, {:force=>true})
-> 0.0849s
.*...........................................DEPRECATION WARNING: Passing a column to `quote` has been deprecated. It is only used for type casting, which should be handled elsewhere. See https://github.com/rails/arel/commit/6160bfbda1d1781c3b08a33ec4955f170e95be11 for more information. (called from quote at …
```

Address failures when tested with Ruby 2.3 or lower

---

lib/active_record/oracle_enhanced/type/boolean.rb

Oracle enhanced adapter also needs to handle 'n' and 'N' as `FALSE`.

Refactor Boolean type by removing duplicate code

---

.rubocop.yml
activerecord-oracle_enhanced-adapter.gemspec
guides/bug_report_templates/active_record_gem.rb
lib/active_record/connection_adapters/oracle_enhanced/column.rb
lib/active_record/connection_adapters/oracle_enhanced/connection.rb
lib/active_record/connection_adapters/oracle_enhanced/cpk.rb
lib/active_record/connection_adapters/oracle_enhanced/procedures.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_creation.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_definitions.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced/structure_dump.rb
lib/active_record/oracle_enhanced/type/integer.rb
spec/active_record/connection_adapters/oracle_enhanced_cpk_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_database_tasks_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_dbms_output_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_dirty_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_procedures_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_structure_dump_spec.rb

At first it is very conservertive ones to remove trailing white space and trailing blank lines
to avoid future pull request and commit diff to show only their concern, not format.
Initial version of .rubocop.yml has been created based on the initial version of Rails.
https://github.com/rails/rails/commit/7d883b829307944f6d7c273f3915ee7059ee3771

Enable rubocop

---

.rubocop.yml

To avoid these warnings:
```ruby
Warning: unrecognized parameter Style/TrailingWhitespace:enabled found in /home/yahonda/git/oracle-enhanced/.rubocop.yml
Warning: unrecognized parameter Style/TrailingBlankLines:enabled found in /home/yahonda/git/oracle-enhanced/.rubocop.yml
```

Enabled needs capitalized

---

spec/active_record/connection_adapters/oracle_enhanced_connection_spec.rb

This pull request suppresses this `create_table` message when rspec runs.
```ruby
$ rspec spec/active_record/connection_adapters/oracle_enhanced_connection_spec.rb
==> Running specs with MRI version 2.3.3
.............-- create_table(:posts, {:force=>true})
-> 0.0702s
....................
Finished in 4.2 seconds (files took 1.3 seconds to load)
33 examples, 0 failures
```

Suppress `create_table(:posts, {:force=>true})` message

---

spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb

This pull request drops leftover InternalMetadata tables with prefixes or suffixes when this spec executed.
```ruby
$ rspec ./spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb
```
* Without this commit:
```sql
$ sqlplus oracle_enhanced/oracle_enhanced
SQL> select table_name from user_tables;
TABLE_NAME
--------------------------------------------------------------------------------
XXX$AR_INTERNAL_METADATA
AR_INTERNAL_METADATA
XXX_AR_INTERNAL_METADATA
AR_INTERNAL_METADATA_XXX
AR_INTERNAL_METADATA$XXX
SQL>
```
* With this commit
```sql
SQL> select table_name from user_tables;
TABLE_NAME
--------------------------------------------------------------------------------
AR_INTERNAL_METADATA
SQL>
```

Drop `ActiveRecord::InternalMetadata.table_name` after each spec

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
spec/active_record/connection_adapters/oracle_enhanced_structure_dump_spec.rb

This pull request updates #1017 to avoid these 3 failures.
```ruby
OCIError: ORA-00942: table or view does not exist: SELECT "XXX_SCHEMA_MIGRATIONS"."VERSION" FROM "XXX_SCHEMA_MIGRATIONS" ORDER BY version
```

Separate schema migration insert statements correctly

---

lib/active_record/connection_adapters/oracle_enhanced/column_dumper.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_definitions.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

Since Oracle enhanced adapter already handles Rails primary keys as NUMBER(38) Oracle data type.
Here 38 means precision, not bytes to store.
Also Rails :bigint data type is handled as NUMBER(19) Oracle data type which has less precision
than Oracle enhanced adapter :integer. Then this pull request falls back :bigint for primary keys
to Rails :integer.
Refer rails/rails#26266

Fallback :bigint to :integer for primary keys

---

spec/active_record/connection_adapters/oracle_enhanced_dirty_spec.rb

This pull request suppresses `create_table(:test_employees, {:force=>true})` message.
```ruby
$ rspec ./spec/active_record/connection_adapters/oracle_enhanced_dirty_spec.rb
... snip ...
-- create_table(:test_employees, {:force=>true})
-> 0.3052s
...
Finished in 0.98271 seconds (files took 1.82 seconds to load)
11 examples, 0 failures
$
```

Suppress `create_table(:test_employees, {:force=>true})` message

---

lib/active_record/connection_adapters/oracle_enhanced/schema_definitions.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

These modules and classes will be prepared for future `:auto_increment` support
ActiveRecord::ConnectionAdapters::OracleEnhanced::ColumnMethods
ActiveRecord::ConnectionAdapters::OracleEnhanced::AlterTable
ActiveRecord::ConnectionAdapters::OracleEnhanced::Table

Introduce OracleEnhanced `ColumnMethods` module and `AlterTable` `Table` classes

---

spec/active_record/connection_adapters/oracle_enhanced_dirty_spec.rb

This pull request addresses these failures:
```ruby
$ rake spec
...
Failures:
1) OracleEnhancedAdapter schema definition sequence creation parameters should use default sequence start value 10000
Got 0 failures and 2 other errors:
1.1) Failure/Error: @connection.exec(sql, *bindvars, &block)
OCIError: ORA-00955: name is already used by an existing object: CREATE SEQUENCE "TEST_EMPLOYEES_SEQ" START WITH 10000
1.2) Failure/Error: Object.send(:remove_const, "TestEmployee")
NameError:
constant Object::TestEmployee not defined
Deprecation Warnings:
Using `should` from rspec-expectations' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` with `config.expect_with(:rspec) { |c| …
```

Perform `drop_table :test_employees`

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb

This pull request addresses #988 by passing nil value as `pk` to `sql_for_insert` if `id_value` exists.
Thanks @kamipo for your work.

Rails 5.1 : Address #988

---

spec/active_record/connection_adapters/oracle_enhanced_context_index_spec.rb

This pull request removes a rspec deprecation warning below.
```ruby
$ rspec spec/active_record/connection_adapters/oracle_enhanced_context_index_spec.rb:175
==> Running specs with MRI version 2.3.3
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_context_index_spec.rb"=>[175]}}
.
Deprecation Warnings:
Using `should` from rspec-expectations' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` with `config.expect_with(:rspec) { |c| c.syntax = :should }` instead. Called from /home/yahonda/git/oracle-enhanced/spec/active_record/connection_adapters/oracle_enhanced_context_index_sp …
```

Address rspec deprecation warning

---

spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

Skip `explain should explain query with bind` with JRuby

---

spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

This reverts commit 2588a80bea095e9cc1dc9522db7e0aae0d5d7e2e.
Reverts #1091

Revert "Skip `explain should explain query with bind` with JRuby"

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

not `NativeException` by JRuby
00942, 00000, "table or view does not exist"
00955, 00000, "name is already used by an existing object"
Since rails/rails#27341 changes `translate_exception` to handle `RuntimeError` as exception.
This pull request addresses these two failures when tested with JRuby.
```ruby
$ rspec ./spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb:393
==> Running specs with JRuby version 9.1.6.0
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb"=>[393]}}
F
Failures:
1) OracleEnhancedAdapter schema definition drop tables should drop table with :if_exists option no raise error …
```

Handle ORA-00942 and ORA-00955 as `ActiveRecord::StatementInvalid`

---

.travis.yml

[Ruby 2.4.0 released](http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-core/78822). Then this Ruby version is available on Travis CI.
http://rubies.travis-ci.org

CI against ruby 2.4.0

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_structure_dump_spec.rb

ORA-00933 error occurred when executing `rails db:schema:load`.
I think that it is probably due to not being able to process `/` by ruby-oci8. In this PR it is a proposal to insert multiple lines without using `/`.
I'm added a reproduction test in active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb.
This PR passed the following reproduction test.
```sh
Failures:
1) OracleEnhancedAdapter schema definition load schema should loads the migration schema table from insert versions sql
Failure/Error:
expect {
@conn.execute insert_versions_sql
}.not_to raise_error
expected no Exception, got #<ActiveRecord::StatementInvalid: OCIError: ORA-00933: SQL command not properly ended:
INSERT INTO sc...on) VALUES ('20160102000000')
/
INSERT INTO schema_migrations (version) VALUES …
```

Fix ORA-00933 error when executing `rails db:schema:load`

---

spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_context_index_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_database_tasks_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb

This pull request addresses these deprecate warnings:
```ruby
[yahonda@li127-48 oracle-enhanced (suppress_tables_warnings)]$ rake spec
DEPRECATION WARNING: #tables currently returns both tables and views. This behavior is deprecated and will be changed with Rails 5.1 to only return tables. Use #data_sources instead. (called from block (3 levels) in <top (required)> at /home/yahonda/git/oracle-enhanced/spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb:377)
DEPRECATION WARNING: #tables currently returns both tables and views. This behavior is deprecated and will be changed with Rails 5.1 to only return tables. Use #data_sources instead. (called from block (3 levels) in <top (required)> at /home/yahonda/git/oracle-enhanced/spec/active_record/connection_adapters/oracle_enh …
```

Remove deprecated `table_exists?` and `tables` 

---

spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb

This pull request addresses this rspec warning below:
```ruby
[yahonda@li127-48 oracle-enhanced (master)]$ rspec spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb:494
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb"=>[494]}}
.
Deprecation Warnings:
Using `should` from rspec-expectations' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` with `config.expect_with(:rspec) { |c| c.syntax = :should }` instead. Called from /home/yahonda/git/oracle-enhanced/spec/active_record/connection_adapters/ …
```

Suppress rspec warning

---

spec/active_record/connection_adapters/oracle_enhanced_database_tasks_spec.rb

This pull request suppress `Dropped database 'ORCL'` messages while running rspec.
* Rails master branch
* Oracle enhanced adapter master branch
* Oracle Database 12c 12.1.0.2
* Ruby 2.4.0
```ruby
$ rspec spec/active_record/connection_adapters/oracle_enhanced_database_tasks_spec.rb 
.Dropped database 'ORCL'
...Dropped database 'ORCL'
.
Finished in 4.69 seconds (files took 1.48 seconds to load)
5 examples, 0 failures
$
``` 
Referred https://github.com/rails/rails/pull/24551 implementation.

Suppress `Dropped database 'ORCL'` messages while running rspec

---

spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_structure_dump_spec.rb

This pull request addresses 6 spec warnings by checking with `raise_errors_for_deprecations!`.
* `raise_errors_for_deprecations!`
```ruby
$ git diff
diff --git a/spec/spec_helper.rb b/spec/spec_helper.rb
index ff594c4..44fb69a 100644
--- a/spec/spec_helper.rb
+++ b/spec/spec_helper.rb
@@ -14,6 +14,9 @@ else
end
require 'rspec'
+RSpec.configure do |config|
+  config.raise_errors_for_deprecations!
+end
if !defined?(RUBY_ENGINE) || RUBY_ENGINE == 'ruby'
puts "==> Running specs with MRI version #{RUBY_VERSION}"
$
```
This rspec helper code is not included this pull request since it looks it makes spec test slower.
```ruby
$ rake spec
Resolving dependencies... …
```

Address rspec warnings by checking with `raise_errors_for_deprecations!`

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

since `rubocop -a` creates these offenses, which cannot be fixed by `rubocop -a`.
Follow up for #1111.

Address `Lint/EndAlignment` offences by changing code ifself

---

.travis.yml

'--dev -J-Xmx1024M' to follow Rails .travis.yml configuration
'--debug' to show simplecov accurate coverage warned below.
```
Coverage may be inaccurate; set the "--debug" command line option, or do JRUBY_OPTS="--debug" or set the "debug.fullTrace=true" option in your .jrubyrc
```
By overriding the default JRUBY_OPTS value, this warning should be addressed by this commit.
`jruby: warning: unknown property jruby.cext.enabled`

Modify JRUBY_OPTS for Travis CI

---

activerecord-oracle_enhanced-adapter.gemspec

This reverts commit f218f6ec0c88fd8ddfd941c90d593a20987cd316.
As explained in rails/rails#27497 . Rails master branch is not ready for Arel 8 yet.

Revert "Bump Arel to 8.0"

---

lib/active_record/connection_adapters/oracle_enhanced/database_tasks.rb

Refer rails/rails#27343
This pull request addresses these two failures.
```ruby
$ bundle exec rake spec
...
Failures:
1) Oracle Enhanced adapter database tasks with test table structure structure_dump dumps the database structure to a file without the schema information
Failure/Error:
def structure_dump(filename)
establish_connection(@config)
File.open(filename, "w:utf-8") { |f| f << connection.structure_dump }
if @config["structure_dump"] == "db_stored_code"
File.open(filename, "a") { |f| f << connection.structure_dump_db_stored_code }
end
ArgumentError:
wrong number of arguments (given 2, expected 1)
2) Oracle Enhanced adapter database tasks with test table structure structure_load loads the database structure from a file
Failure/Error:
def structure_dump(filename) …
```

ActiveRecord structure_dump and structure_load signature changes

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb

Refer rails/rails#25522
This pull request addresses (about) 166 errors like this:
```ruby
$ ARCONN=oracle bundle exec ruby -Itest test/cases/autosave_association_test.rb -n test_should_destroy_habtm_as_part_of_the_save_transaction_if_they_were_marked_for_destruction
Using oracle
... snip ...
Run options: -n test_should_destroy_habtm_as_part_of_the_save_transaction_if_they_were_marked_for_destruction --seed 31131
E
Finished in 0.549146s, 1.8210 runs/s, 3.6420 assertions/s.
1) Error:
TestDestroyAsPartOfAutosaveAssociation#test_should_destroy_habtm_as_part_of_the_save_transaction_if_they_were_marked_for_destruction:
ActiveRecord::StatementInvalid: TypeError: no implicit conversion of Parrot::ActiveRecord_Relation into String: #<Parrot::ActiveRecord_Relation:0x0055e62d142eb8> …
```

Use Abstract `select_rows(arel, name = nil, binds = [])`

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

This pull request addresses #1131.
In 12c, it returns `CDB_NAME`.
https://docs.oracle.com/database/121/SQLRF/functions199.htm#SQLRF06117
```
Parameter
CDB_NAME
Return Value
If queried while connected to a CDB, returns the current container name.
Otherwise, returns the name of the database as specified in the DB_NAME initialization parameter.
```
CDB_NAME parameter does not exist 11gR2 or lower, it gets `ActiveRecord::StatementInvalid ORA-02003`
then executes the old 'DB_NAME'.

`current_database` returns the expected database name

---

.rubocop.yml

```
$ rubocop -v
0.47.1
$ rubocop
Error: obsolete parameter AlignWith (for Lint/EndAlignment) found in
/home/yahonda/git/oracle-enhanced/.rubocop.yml
`AlignWith` has been renamed to `EnforcedStyleAlignWith`
```

rubocop `AlignWith` has been renamed to `EnforcedStyleAlignWith`

---

lib/active_record/connection_adapters/oracle_enhanced/schema_creation.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Refer rails/rails#24743
This pull request addresses this error.
```ruby
$ bundle exec rake test_oracle
... snip ...
Using oracle
/home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/schema_creation.rb:26:in `visit_TableDefinition': undefined method `supports_foreign_keys?' for #<ActiveRecord::ConnectionAdapters::OracleEnhanced::SchemaCreation:0x0055ba30c6cf88> (NoMethodError)
Did you mean?  supports_foreign_keys_in_create?
from /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/schema_creation.rb:14:in `accept'
from /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb:76:in `create_table'
from /home/yahonda/git/rails/activerecord/lib/active_record/migration.rb:851:in …
```

Use `supports_foreign_keys_in_create?`

---

spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb

Refer rails/rails#27718
This pull request addresses these two failures:
```ruby
$ bundle exec rspec ./spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb
... snip ...
... snip ...
Failures:
1) OracleEnhancedAdapter schema dump table prefixes and suffixes should not include schema_migrations table with prefix in schema dump
Failure/Error: @conn.initialize_schema_migrations_table
NoMethodError:
undefined method `initialize_schema_migrations_table' for #<ActiveRecord::ConnectionAdapters::OracleEnhancedAdapter:0x0055b8f6bad808>
2) OracleEnhancedAdapter schema dump table prefixes and suffixes should not include schema_migrations table with …
```

`initialize_schema_migrations_table` method has been removed

---

.travis.yml

Test with Ruby 9.0.4.0 until #1145 is resolved.

Add JRuby 9.0.4.0 and allow JRuby 9.0.5.0 failures

---

.travis.yml

Use JRuby 9.1.x or higher
Refer jruby/jruby#4453 and #1145

Drop JRuby 9.0.x support for Rails 5.1

---

spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

Added this spec to avoid future regressions reported in #1149.

Add spec for #1149 `TypeError: can't cast Java::JavaSql::Timestamp`

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb

This PR will make it possible to change column with adding comment.
```ruby
schema_define do
change_column :test_posts, :title, :string, comment: "hello comment"
end
TestPost.reset_column_information
expect(TestPost.columns_hash["title"].comment).to eq "hello comment"
```
And, this PR fixes the following 2 failures when running AR tests of rails/rails.
https://github.com/rails/rails/blob/28934172042505156f7c60ac2534dd92f32170d9/activerecord/test/cases/comment_test.rb#L80-L88
```sh
vagrant@rails-dev-box:~/src/rails/activerecord$ ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]
vagrant@rails-dev-box:~/src/rails/activerecord$ ARCONN=oracle bundle exec ruby -w -Itest:lib test/cases/comment_test.rb -n test_add_comment_to_column …
```

Made it able to change column with adding comment

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

This PR will fix to return nil if a value of column comment is blank at table creation.
It's a code snippet from testing code.
```ruby
schema_define do
create_table :test_employees do |t|
t.string :first_name, comment: " "
end
end
class ::TestEmployee < ActiveRecord::Base; end
expect(TestEmployee.columns_hash["first_name"].comment).to be_nil
```
And, This PR fixes the following failure when running AR tests of rails/rails.
https://github.com/rails/rails/blob/28934172042505156f7c60ac2534dd92f32170d9/activerecord/test/cases/comment_test.rb#L51-L57
```sh
vagrant@rails-dev-box:~/src/rails/activerecord$ ARCONN=oracle bundle exec ruby -w -Itest:lib test/cases/comment_test.rb -n test_blank_columns_created_in_block
Ignoring jruby-launcher-1.1.1-java because its extensions are not built.  Try: gem …
```

Fix to return nil if column comment is blank at table creation

---

lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb

This PR omits table comment option of schema.rb generated by `db:schema:dump` if it is blank.
The following is a sample code of schema.rb generated by `db:schema:dump`.
```ruby
ActiveRecord::Schema.define(version: 0) do
create_table "blank_comments", comment: " ", force: :cascade do |t|
t.string "space_comment"
t.string "empty_comment"
t.string "nil_comment"
t.string "absent_comment"
end
add_index "blank_comments", ["absent_comment"], name: "i_bla_com_abs_com"
add_index "blank_comments", ["empty_comment"], name: "i_blank_comments_empty_comment"
add_index "blank_comments", ["nil_comment"], name: "i_blank_comments_nil_comment"
add_index "blank_comments", ["space_comment"], name: "i_blank_comments_space_comment"
end
```
```ruby
ActiveRecord::Schema.define(version: 0) do
create_table …
```

Omit table comment option of schema.rb if it is blank

---

spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb

It seems that [oracle_enhanced_schema_dump_spec.rb#L458-L496](https://github.com/rsim/oracle-enhanced/blob/8dda26422a352310311382b611b78ce021cd6479/spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb#L458-L496) and [oracle_enhanced_schema_dump_spec.rb#L498-L536](https://github.com/rsim/oracle-enhanced/blob/8dda26422a352310311382b611b78ce021cd6479/spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb#L498-L536) are the same.

Remove a duplicated specs

---

spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb

This spec is covered [here](https://github.com/rails/rails/blob/28934172042505156f7c60ac2534dd92f32170d9/activerecord/test/cases/comment_test.rb#L80-L88).
Fixes https://github.com/rsim/oracle-enhanced/pull/1156#issuecomment-278036280.

Remove a spec covered by Active Record

---

lib/active_record/connection_adapters/oracle_enhanced/schema_creation.rb

This pull request follows up #1167 to restore Virtual column support without type.

Add Virtual column support without type

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced/structure_dump.rb

This pull request fixes #1171 
It also removes duplicate `add_column_options!` method from `ActiveRecord::ConnectionAdapters::OracleEnhancedStructureDump`
It addresses these 7 errors:
```ruby
$ ARCONN=oracle bundle exec ruby -w -Itest test/cases/migration/change_schema_test.rb -n test_keeping_default_and_notnull_constraints_on_change
... snip ...
Run options: -n test_keeping_default_and_notnull_constraints_on_change --seed 31972
E
Finished in 0.592900s, 1.6866 runs/s, 11.8064 assertions/s.
1) Error:
ActiveRecord::Migration::ChangeSchemaTest#test_keeping_default_and_notnull_constraints_on_change:
ArgumentError: wrong number of arguments (given 2, expected 1)
/home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/quoting.rb:9:in `quote' …
```

Address change_column `ArgumentError: wrong number of arguments`

---

lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb

This PR changes the position of the table comment option backward in schema dump.
The following schema dump code is the value of `output` variable when running [this test](https://github.com/rails/rails/blob/e04de27b2fb0dffdf54316c42bc9669023877d51/activerecord/test/cases/comment_test.rb#L110).
The `comment` option of `create_table` is forward.
```ruby
ActiveRecord::Schema.define(version: 0) do
create_table "commenteds", comment: "A table with comment", force: :cascade do |t|
t.string  "name",                   comment: "Comment should help clarify the column purpose"
t.string  "obvious"
t.string  "content",                comment: "Whoa, content describes itself!"
t.integer "rating",  precision: 38, comment: "I am running out of imagination"
end
add_index "commenteds", ["name"], name: …
```

Change the position of table comment in schema dump

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Follow up to https://github.com/rails/rails/pull/25451.
This PR will fix to raise `ActiveRecord::NotNullViolation` when `OCIError: ORA-01400`.
And, This PR fixes the following 4 failures when running AR tests of rails/rails.
https://github.com/rails/rails/blob/efe121eab01d70c9da5747597d8ac6f526f2da4e/activerecord/test/cases/migration/change_schema_test.rb#L41-L49
```sh
vagrant@rails-dev-box:~/src/rails/activerecord$ ARCONN=oracle bundle exec ruby -w -Itest:lib test/cases/migration/change_schema_test.rb -n test_create_table_with_not_null_column
(snip)
Run options: -n test_create_table_with_not_null_column --seed 55458
F
Finished in 0.058355s, 17.1366 runs/s, 17.1366 assertions/s.
1) Failure:
ActiveRecord::Migration::ChangeSchemaTest#test_create_table_with_not_null_column …
```

Raise ActiveRecord::NotNullViolation when OCIError: ORA-01400

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

Refer rails/rails#26930
This pull request addresses these 1 failure and 5 errors.
```ruby
$ ARCONN=oracle bundle exec ruby -w -Itest test/cases/migration/index_test.rb
... snip ...
..EE.....E...FE..
Finished in 97.620479s, 0.1741 runs/s, 0.2663 assertions/s.
1) Error:
ActiveRecord::Migration::IndexTest#test_add_index_does_not_accept_too_long_index_names:
ArgumentError: wrong number of arguments (given 2, expected 3)
/home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb:223:in `index_name_exists?'
test/cases/migration/index_test.rb:78:in `test_add_index_does_not_accept_too_long_index_names'
2) Error:
ActiveRecord::Migration::IndexTest#test_add_index_works_with_long_index_names:
ArgumentError: wrong number of arguments (given 2, …
```

Deprecate passing `default` to `index_name_exists?`

---

lib/active_record/connection_adapters/oracle_enhanced/schema_definitions.rb
spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb

This pull request supports `:raw` type migration support.
Rails master branch
Oracle enhanced master branch
Oracle Database 12.1.0.2 Enterprise Edition
ruby 2.5.0dev (2017-02-13 trunk 57613) [x86_64-linux]
```ruby
begin
require "bundler/inline"
rescue LoadError => e
$stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
raise e
end
gemfile(true) do
source "https://rubygems.org"
gem "rails", github: "rails/rails", branch: "master"
gem "arel", github: "rails/arel", branch: "master"
gem "activerecord-oracle_enhanced-adapter",  github: "rsim/oracle-enhanced", branch: "master"
gem "ruby-oci8"
gem "minitest"
gem "byebug"
end
require "active_record"
require "minitest/autorun"
require "logger"
require "active_record/connection_adapters/oracle_enhanced_adapter" …
```

Restore :raw type migration support

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Refer rails/rails#27977
```ruby
$ ARCONN=oracle bundle exec ruby -w -Itest test/cases/primary_keys_test.rb -n test_deprecate_supports_primary_key
... snip ...
Using oracle
... snip ...
Run options: -n test_deprecate_supports_primary_key --seed 39161
F
Finished in 0.501226s, 1.9951 runs/s, 1.9951 assertions/s.
1) Failure:
PrimaryKeysTest#test_deprecate_supports_primary_key [test/cases/primary_keys_test.rb:145]:
Expected a deprecation warning within the block but received none
1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
$
```

Deprecate `supports_primary_key?`

---

spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_context_index_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_database_tasks_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb

Since all of them are checking tables, not views.
it is kind of reverting #1100 .

Use `table_exists?` and `tables`

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb

`empty_insert_statement_value_not_supported` is not implemented by Oracle database
It would be better raise `NotImplementedError` than returning Abstract adapter implementation `DEFAULT VALUES`.
These two ActiveRecord unit tests currently get error `ActiveRecord::StatementInvalid: OCIError: ORA-00926: missing VALUES keyword`.
```ruby
$ ARCONN=oracle bundle exec ruby -w -Itest test/cases/primary_keys_test.rb -n test_create_without_primary_key_no_extra_query
... snip ...
E
Finished in 0.496107s, 2.0157 runs/s, 0.0000 assertions/s.
1) Error:
PrimaryKeysTest#test_create_without_primary_key_no_extra_query:
ActiveRecord::StatementInvalid: OCIError: ORA-00926: missing VALUES keyword: INSERT INTO "DASHBOARDS" DEFAULT VALUES
stmt.c:243:in oci8lib_240.so …
```

`empty_insert_statement_value_not_supported` is not implemented

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb

Better to raise `NotImplementedError` rather than do nothing

`release_savepoint` is not supported by Oracle

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb

This reverts commit 55bf70964e41292eeb922f616cd5e9a515babc2c.
It caused these errors:
```ruby
1) Error:
ActiveRecord::AdapterTest#test_update_prepared_statement:
NotImplementedError: NotImplementedError
/opt/circleci/.rvm/gems/ruby-2.4.0/bundler/gems/oracle-enhanced-e72b434901ce/lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb:200:in `release_savepoint'
/home/ubuntu/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:117:in `commit'
/home/ubuntu/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:174:in `commit_transaction'
/home/ubuntu/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:199:in `within_new_transaction' …
```

Revert "`release_savepoint` is not supported by Oracle"

---

.travis.yml

ORACLE_COOKIE is not necessary anymore
DATABASE_VERSION is 11.2.0.1

Tiny fix for .travis.yml after migrating to docker-oracle-xe-11g

---

lib/active_record/connection_adapters/oracle_enhanced/column_dumper.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb
spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb

This pull request addresses these 3 failures:
```ruby
$ ARCONN=oracle bundle exec ruby -w -Itest test/cases/schema_dumper_test.rb -n /no_line_up/
... snip ...
Finished in 21.899343s, 0.0913 runs/s, 0.5480 assertions/s.
1) Failure:
SchemaDumperTest#test_arguments_no_line_up [test/cases/schema_dumper_test.rb:100]:
Failed assertion, no message given.
2) Failure:
SchemaDumperTest#test_types_no_line_up [test/cases/schema_dumper_test.rb:94]:
Failed assertion, no message given.
2 runs, 12 assertions, 2 failures, 0 errors, 0 skips
```
```ruby
$ ARCONN=oracle bundle exec ruby -w -Itest test/cases/migration_test.rb -n test_deprecate_migration_keys
... snip ...
F
Finished in 0.005173s, 193.2977 runs/s, 193.2977 assertions/s.
1) Failure:
CopyMigrationsTest#test_deprecate_migration_keys …
```

Refactor ColumnDumper to support consistent Virtual column with Rails

---

lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb
spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb

except for context indexes generated `add_context_index` syntax outside
of `create_table`
Refer rails/rails#23557
This pull request addresses these two errors:
```ruby
$ ARCONN=oracle bundle exec ruby -w -Itest test/cases/schema_dumper_test.rb -n /ind/
E
Finished in 2.286569s, 0.8747 runs/s, 0.0000 assertions/s.
1) Error:
SchemaDumperTest#test_schema_dumps_index_columns_in_right_order:
NoMethodError: undefined method `strip' for nil:NilClass
test/cases/schema_dumper_test.rb:181:in `test_schema_dumps_index_columns_in_right_order'
2) Error:
SchemaDumperTest#test_schema_dumps_partial_indices:
NoMethodError: undefined method `strip' for nil:NilClass
test/cases/schema_dumper_test.rb:192:in `test_schema_dumps_partial_indices'
2 runs, 0 assertions, 0 failures, 2 errors, 0 skips
$
```

Schema dumper supports `t.index`  in `create_table`

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

refer rails/rails#27503
https://github.com/rails/rails/commit/d5be101dd02
This pull request removes the deprecate warning
```ruby
$ bundle exec rspec ./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb:366
==> Running specs with MRI version 2.5.0
... snip ...
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb"=>[366]}}
DEPRECATION WARNING: #tables currently returns both tables and views. This behavior is deprecated and will be changed with Rails 5.1 to only return tables. Use #data_sources instead. (called from block (3 levels) in <top (required)> at /home/yahonda/git/oracle-enhanced/spec/active_record/connection_adapters/o …
```

Remove deprecated `name` argument from `#tables`

---

lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Refer rails/rails#21715
Since https://github.com/rsim/oracle-enhanced/pull/1192/commits/eca49387edc1eff82af7db5cce092bab7b8d20c4 caused these two regressions other two commit address these error and failure.
```ruby
35) Error:
ViewWithPrimaryKeyTest#test_does_not_dump_view_as_table:
ActiveRecord::StatementInvalid: OCIError: ORA-00911: invalid character:           SELECT trigger_name
FROM all_triggers
WHERE owner = 'ARUNIT'
AND trigger_name = 'EBOOKS'_PKT'
AND table_owner = 'ARUNIT'
AND table_name = 'ebooks''
AND status = 'ENABLED'
stmt.c:243:in oci8lib_230.so
/home/yahonda/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ruby-oci8-2.2.3/lib/oci8/cursor.rb:126:in `exec'
/home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:162:in `exec' …
```

data_sources returns tables and views

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

`DEPRECATION WARNING: Passing default to #index_name_exists? is deprecated without replacement.`
Since `index_name_for_remove` method already checks index existence then no need to take care of it here.
Related with #1193

Suppress `remove_index` method deprecation warning at remove_index

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb

This pull request suppresses the deprecation warning below.
```ruby
DEPRECATION WARNING: Passing default to #index_name_exists? is deprecated without replacement. (called from rename_index at /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb:241)
```

Suppress DEPRECATION WARNING at rename_index 

---

spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb

It suppresses the following warning message:
```
oracle_enhanced_schema_statements_spec.rb:1242: warning: method redefined; discarding old index_name_exists?
```

index_name_exists? at schema statements spec is not necessary

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb

Use Rails `table_comment(table_name)` syntax.

`Model.table_comment` syntax is not supported anymore

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

since it has been removed since Rails 3.1
https://github.com/rails/rails/commit/66c09372f3ef3d4ca2b99d44cf1859d585b9dcb3

Remove `ids_in_list_limit` alias

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Follow up to https://github.com/rails/rails/pull/28176.
It becomes the same implementation as the super class, it was removed.

Push `valid_type?` up to abstract adapter

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Follow up to https://github.com/rails/rails/pull/28172.

Deprecate `supports_migrations?` on connection adapters

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Oracle enhanced adapter 1.8.0.beta1 has been out. We can restore #1208 and #1209 to master branch.

Restore #1208 and #1209

---

spec/active_record/connection_adapters/oracle_enhanced_context_index_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_dirty_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_emulate_oracle_adapter_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_procedures_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb

This pull request suppresses following warnings.
```ruby
oracle-enhanced/spec/active_record/connection_adapters/oracle_enhanced_dirty_spec.rb:122: warning: instance variable @conn not initialized
oracle-enhanced/spec/active_record/connection_adapters/oracle_enhanced_dirty_spec.rb:122: warning: instance variable @connection not initialized
oracle-enhanced/spec/active_record/connection_adapters/oracle_enhanced_procedures_spec.rb:213: warning: assigned but unused variable - empl_id
oracle-enhanced/spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb:217: warning: assigned but unused variable - insert_id
oracle-enhanced/spec/active_record/connection_adapters/oracle_enhanced_context_index_spec.rb:82: warning: instance variable @post not initialized …
```

Suppress unused and not initialized warnings

---

activerecord-oracle_enhanced-adapter.gemspec

#1114 removed runtime dependencies also.

ruby-plsql 0.6.0 or higher version is required

---

spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb

```sh
% be rspec spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb:1103
(snip)
WARNING: Using the `raise_error` matcher without providing a specific error or message risks false positives, since `raise_error` will match wh
en Ruby raises a `NoMethodError`, `NameError` or `ArgumentError`, potentially allowing the expectation to pass without even executing the metho
d you are intending to call. Actual error raised was #<RuntimeError: No virtual column definition found.>. Instead consider providing a specif
ic error class or message. This message can be suppressed by setting: `RSpec::Expectations.configuration.on_potential_false_positives = :nothing
`. Called from …
```

Suppress `WARNING: Using the `raise_error` matcher without providing a specific error`

---

spec/active_record/connection_adapters/oracle_enhanced_dirty_spec.rb

```sh
% bundle exec rspec spec/active_record/connection_adapters/oracle_enhanced_dirty_spec.rb:128
(snip)
WARNING: Using `expect { }.not_to raise_error(SpecificErrorClass, message)` risks false positives, since literally any other error would cause 
the expectation to pass, including those raised by Ruby (e.g. NoMethodError, NameError and ArgumentError), meaning the code you are intending to t
est may not even get reached. Instead consider using `expect {}.not_to raise_error` or `expect { }.to raise_error(DifferentSpecificErrorClas
s)`. This message can be suppressed by setting: `RSpec::Expectations.configuration.on_potential_false_positives = :nothing`. Called from /home/
vagrant/src/oracle-enhanced/spec/active_record/connection_adapters/oracle_en …
```

Suppress `WARNING: Using `expect { }.not_to raise_error(...)` risks false positives`

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb

refer rails/rails#28293
This pull request addresses these failures:
```ruby
$ bundle exec rspec ./spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb:83
==> Running specs with MRI version 2.5.0
/home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/bundler/gems/ruby-oci8-0ffd0c8787bd/lib/oci8/oci8.rb:627: warning: method redefined; discarding old initialize
/home/yahonda/git/rails/activesupport/lib/active_support/core_ext/enumerable.rb:20: warning: method redefined; discarding old sum
/home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/bundler/gems/ruby-plsql-5e5761cb8e4c/lib/plsql/variable.rb:87: warning: shadowing outer local variable - column
/home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/bundler …
```

Use `ActiveRecord::SchemaMigration.table_name`

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb

to handle composite primary keys by checking if pk is Array
Follow up for #1223 and #1224

Remove CompositePrimaryKeys from `sql_for_insert`

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

They are initialized at AbstractAdapter

No need to initialize `@quoted_column_names` and `@quoted_table_names`

---

lib/active_record/connection_adapters/oracle_enhanced/quoting.rb

Since this method does not know `column` it always get rescued.

Hard code `empty_blob()` or `empty_clob()` based on types

---

RUNNING_TESTS.md

It used to be at README. RUNNING_TESTS should be a right place to show it.

Add Travis CI build status

---

lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb
spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb

This PR will eliminates unnecessary blank lines from schema.rb as follows.
```ruby
#
#
ActiveRecord::Schema.define(version: 0) do
create_table "test_comments", force: :cascade do |t|
t.string "title"
t.index ["title"], name: "index_test_comments_on_title"
end
create_table "test_posts", force: :cascade do |t|
t.string "title"
t.datetime "created_at", precision: 6
t.datetime "updated_at", precision: 6
t.index ["title"], name: "index_test_posts_on_title"
end
end
```
```ruby
#
#
ActiveRecord::Schema.define(version: 0) do
create_table "test_comments", force: :cascade do |t|
t.string "title"
t.index ["title"], name: "index_test_comments_on_title"
end
create_table "test_posts", force: :cascade do |t|
t.string "title"
t.datetime "created_at", precision: 6
t.datetime "updated_at", precision: 6 …
```

Eliminate a redundant empty lines in schema.rb generated by SchemaDumper

---

spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

It is tested at `CalculationsTest#test_apply_distinct_in_count`
```ruby
$ ARCONN=oracle bundle exec ruby -w -Itest test/cases/calculations_test.rb -n test_apply_distinct_in_count
/home/yahonda/git/rails/activesupport/lib/active_support/core_ext/enumerable.rb:20: warning: method redefined; discarding old sum
Using oracle
Run options: -n test_apply_distinct_in_count --seed 13824
.
Finished in 0.664032s, 1.5060 runs/s, 7.5298 assertions/s.
1 runs, 5 assertions, 0 failures, 0 errors, 0 skips
$
```

Remove a duplicate spec testing `Model.distinct.count`

---

activerecord-oracle_enhanced-adapter.gemspec
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
lib/active_record/oracle_enhanced/type/json.rb
spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb

This pull request adds JSON attribute support.
- Oracle Database 12c Release 1 or higher version is required
- ActiveRecord migration for json type is not supported
since there is no JSON data type in Oracle database
1. Define :string or :text in migration for columns for JSON
```ruby
create_table :test_posts, force: true do |t|
t.string  :title
t.text    :article
end
```
2. Set :json attributes
```ruby
class TestPost < ActiveRecord::Base
attribute :title, :json
attribute :article, :json
end
```
3. Add `is json` database constraints by running sql statements
```sql
alter table test_posts add constraint test_posts_title_is_json check (title is json)
alter table test_posts add constraint test_posts_article_is_json check (article is json)
```

Add JSON attribute support

---

lib/active_record/connection_adapters/oracle_enhanced/structure_dump.rb
spec/active_record/connection_adapters/oracle_enhanced_structure_dump_spec.rb

This PR will aligns columns of db/structure.sql generated by AR::ConnectionAdapters::OracleEnhancedStructureDump as follows.
The top column is not indented.
```sql
CREATE TABLE "TEST_POSTS" (
"ID" NUMBER(38,0) NOT NULL,
"TITLE" VARCHAR2(255),
"FOO" VARCHAR2(255),
"FOO_ID" NUMBER(38,0),
CONSTRAINT SYS_C00233872 PRIMARY KEY (ID)
)
```
All columns are indented.
```sql
CREATE TABLE "TEST_POSTS" (
"ID" NUMBER(38,0) NOT NULL,
"TITLE" VARCHAR2(255),
"FOO" VARCHAR2(255),
"FOO_ID" NUMBER(38,0),
CONSTRAINT SYS_C00233872 PRIMARY KEY (ID)
)
```

Align the columns of db/structure.sql

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb

backport #1248 to release18 branch.
Fixes #1246.

Fix `select_all` with legacy `binds`

---

.travis.yml

https://www.ruby-lang.org/en/news/2017/03/22/ruby-2-4-1-released/

Bump Ruby version to 2.4.1

---

lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb
spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb

Refer #1244.
This PR will return an approximate value instead of nil when using BINARY_FLOAT column type in OracleEnhancedJDBCConnection. That is the same behavior as OracleEnhancedOCIConnection.

Fix the BINARY_FLOAT column type returns nil in JRuby

---

spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb

This pull request addresses these failures.
```ruby
$ bundle exec rake spec
... snip ...
Failures:
1) OracleEnhancedAdapter attribute API support for JSON type should support attribute api for JSON
Failure/Error: @connection.exec(sql, *bindvars, &block)
OCIException: OCI8 was already closed.:       alter table test_posts add constraint test_posts_title_is_json check (title is json)
2) OracleEnhancedAdapter attribute API support for JSON type should support IS JSON
Failure/Error: @connection.exec(sql, *bindvars, &block)
OCIException: OCI8 was already closed.:       alter table test_posts add constraint test_posts_title_is_json check (title is json)
Finished in 1 minute 25.64 seconds (files took 0.91177 seconds to load)
365 …
```

Address `OCIException: OCI8 was already closed` at specs for JSON

---

spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb

Backport #1265 into release18 branch.

Address `OCIException: OCI8 was already closed` at specs for JSON at release18

---

lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/quoting.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
lib/active_record/oracle_enhanced/type/timestamptz.rb
spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb

Fixes #1206
rails/rails#27962 moves `TypeCastingTest` from sqlite3 specific one to generic then some tests are failing because `type_cast` and `quote` method both call `quoted_date` for `Date` and `Time` class objects in abstract adapter but Oracle enhanced adapter does not, using its own implementation.
This pull request lets generic `Date` and `Type` objects handled by abstract adapter implementation.
For non-generic data types including timezone `ActiveRecord::OracleEnhanced::Type::TimestampTz` type has been created and `TimestampTz` type is handled as it used to.
Oracle enhanced adapter now relies on `Time::DATE_FORMATS` defined in ActiveSupport by this change.
Therefore changing `NLS_DATE_FORMAT` and `NLS_TIMESTAMP_FORMAT` are not working and will not be supported.

Handle `TIMESTAMP WITH TIMEZONE` separately from `TIMEZONE`

---

lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/quoting.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
lib/active_record/oracle_enhanced/type/timestamptz.rb
spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb

This pull request backports #1267 into release18 branch.

Handle `TIMESTAMP WITH TIMEZONE` separately from `TIMEZONE` at release18

---

.travis.yml

https://www.ruby-lang.org/en/news/2017/03/30/ruby-2-3-4-released/

Use Ruby 2.3.4

---

lib/active_record/connection_adapters/oracle_enhanced/jdbc_quoting.rb

Refer #1267 for CRuby
This pull request addresses these 3 failures:
```ruby
$ ARCONN=oracle bundle exec ruby -w -Itest test/cases/quoting_test.rb
Using oracle
Run options: --seed 31792
..........................F....F....F
Finished in 2.771868s, 13.3484 runs/s, 17.3168 assertions/s.
1) Failure:
ActiveRecord::ConnectionAdapters::TypeCastingTest#test_type_cast_date [test/cases/quoting_test.rb:165]:
--- expected
+++ actual
@@ -1 +1 @@
-"2017-03-30"
+#<Java::OracleSql::DATE:0xXXXXXX>
2) Failure:
ActiveRecord::ConnectionAdapters::TypeCastingTest#test_type_cast_time [test/cases/quoting_test.rb:171]:
--- expected
+++ actual
@@ -1 +1 @@
-"2017-03-30 20:30:08.614795"
+#<Java::JavaSql::Timestamp:0xXXXXXX>
3) Failure:
ActiveRecord::ConnectionAdapters::QuoteARBaseTest#test_type_cast_ar_object …
```

Let abstract adapter type cast Date, DateTime and Time for JRuby

---

History.md
README.md
spec/active_record/connection_adapters/oracle_enhanced_connection_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_structure_dump_spec.rb

```ruby
$ misspell -w *
History.md:529:3: corrected "Supress" to "Suppress"
History.md:816:41: corrected "datbase" to "database"
History.md:1201:18: corrected "simultaniously" to "simultaneously"
History.md:1204:13: corrected "perfomance" to "performance"
spec/active_record/connection_adapters/oracle_enhanced_connection_spec.rb:415:72: corrected "existant" to "existent"
spec/active_record/connection_adapters/oracle_enhanced_connection_spec.rb:417:30: corrected "existant" to "existent"
README.md:473:94: corrected "overriden" to "overridden"
spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb:228:24: corrected "preceed" to "precede"
spec/active_record/connection_adapters/oracle_enhanced_structure_dump_spec.rb:246:21: corrected "stucture" to "structure" …
```

Fix typos by https://github.com/client9/misspell

---

spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb

by using `force: true` and `if_exists: true` to avoid `rescue nil`.

Clean up before(:each) and after(:each) at "rename tables and sequences"

---

spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

```ruby
$ rubocop -a
Inspecting 48 files
..............C.................................
Offenses:
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb:639:19: C: [Corrected] Put one space between the method name and the first argument.
t.string  :first_name, limit: 20
^^
48 files inspected, 1 offense detected, 1 offense corrected
$
```

rubocop 0.48.1

---

activerecord-oracle_enhanced-adapter.gemspec
lib/active_record/connection_adapters/oracle_enhanced/quoting.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_definitions.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
lib/active_record/oracle_enhanced/type/timestampltz.rb
spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb

```ruby
create_table :posts, force: true do |t|
t.timestamptz   :updated_at_tz
t.timestampltz  :updated_at_ltz
end
```
* `timestamptz` type is mapped to `TIMESTAMP WITH TIME ZONE` sql type.
* `timestampltz` type is mapped to `TIMESTAMP WITH LOCAL TIME ZONE` sql type.

Support `timestamptz` and `timestampltz` for migrations

---

activerecord-oracle_enhanced-adapter.gemspec

Add missing `timestamptz.rb` to gemspec at release18 branch

---

spec/active_record/connection_adapters/oracle_enhanced_connection_spec.rb

```sh
$ bundle exec rspec spec/active_record/connection_adapters/oracle_enhanced_connection_spec.rb
(snip)
/home/vagrant/src/oracle-enhanced/spec/active_record/connection_adapters/oracle_enhanced_connection_spec.rb:204: warning: assigned but unused variable - poolable_connection_factory
.................................
Finished in 1.4 seconds (files took 0.50948 seconds to load)
33 examples, 0 failures
```

Suppress `warning: assigned but unused variable - poolable_connection_factory`

---

spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb

```sh
$ bundle exec rspec spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb
(snip)
/home/vagrant/src/oracle-enhanced/spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb:1270: warning: assigned but unused variable - post
..................................................................**
Pending: (Failures listed here are expected and do not affect your suite's status)
1) OracleEnhancedAdapter attribute API support for JSON type should support attribute api for JSON
2) OracleEnhancedAdapter attribute API support for JSON type should support IS JSON
Finished in 2.65 seconds …
```

Suppress `warning: assigned but unused variable - post`

---

activerecord-oracle_enhanced-adapter.gemspec

It seemed that maintenance was complicated to write each file name in gemspec. As shown in the sample below, it doesn't seem to match the actual file structure.
```ruby
[
".rspec",
"Gemfile",
"History.md",
"License.txt",
"README.md",
"RUNNING_TESTS.md",
"Rakefile",
"VERSION",
"activerecord-oracle_enhanced-adapter.gemspec",
"lib/active_record/connection_adapters/emulation/oracle_adapter.rb",
"lib/active_record/connection_adapters/oracle_enhanced_adapter.rb",
"lib/active_record/connection_adapters/oracle_enhanced/column.rb",
"lib/active_record/connection_adapters/oracle_enhanced/column_dumper.rb",
"lib/active_record/connection_adapters/oracle_enhanced/connection.rb",
"lib/active_record/connection_adapters/oracle_enhanced/context_index.rb", …
```

Collapse a file specification in gemspec

---

activerecord-oracle_enhanced-adapter.gemspec

Follow up to https://github.com/rsim/oracle-enhanced/pull/1297#issuecomment-295083804.
This PR reduces 2 tasks in release work.
I made different commits on these in this PR.
It will use the version written in the VERSION file.
As a result, the description of the version becomes unified management.
I often see this technique. For example Rails does.
By not specifying `s.date`, the release date (i.e. ` gem push` date) will be displayed as rubygems.org release date. This makes it unnecessary to specify the release date for gemspec.
:warning: However, there are cautions in this. As far as I know, the date when `s.date` is not specified seems to be the date in UTC (not the local time zone). Since Oracle enhanced adapter describes the release date in `History.md`, there may be a difference from …

Reduce tasks of release work

---

History.md

This pull request is for master branch, then will backport it to release18 branch since I think History.md at master branch need to have entries for v1.8.

Prepare release v1.8.0.rc2

---

activerecord-oracle_enhanced-adapter.gemspec

There was a mistake in #1296.
[`ActiveRecord::ConnectionAdapters::OracleEnhancedAdapter::VERSION`](https://github.com/rsim/oracle-enhanced/blob/78dacb3f461809b307c319a486f41c69b2a83d11/lib/active_record/connection_adapters/oracle_enhanced/version.rb) depends on the VERSION file, but it did not include that file in gem.
This problem can be confirmed from the build result of rsim/ruby-plsql#127.
https://travis-ci.org/rsim/ruby-plsql/jobs/224701029
```sh
1) ActiveRecord connection should connect to test database
Failure/Error: ActiveRecord::Base.establish_connection(CONNECTION_PARAMS)
Errno::ENOENT:
No such file or directory @ rb_sysopen - /home/travis/.rvm/gems/ruby-2.4.1/gems/activerecord-oracle_enhanced-adapter-1.8.0.rc2/VERSION
```
This fix is also required for the `release18` branch.

Include VERSION file in gem

---

History.md

This pull request is for master branch, then will backport it to release18 branch since I think History.md at master branch need to have entries for v1.8.

[ci skip] Prepare release v1.8.0.rc3

---

History.md

Backport #1305 into release18 branch.

[skip ci] Prepare release v1.8.0.rc3

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

This test will fail at Travis CI test which running Oracle 11gR1 XE. Will update travis changes later.

Oracle Database 12.2 or higher version required for version 2

---

lib/active_record/connection_adapters/oracle_enhanced/structure_dump.rb

Each Identity datatype creates a sequence named "ISEC$$_nnnnn", which depends on the table. This sequence cannot be dropped separately and it will be dropped once the base table dropped.
Example with SQL statements:
```sql
SQL> CREATE TABLE "TEST_POSTS" ("ID" NUMBER(38) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "SUBJECT" VARCHAR2(255));
Table created.
SQL> select object_name,object_type from user_objects;
OBJECT_NAME                    OBJECT_TYPE
------------------------------ -----------------------
SYS_C00208553                  INDEX
ISEQ$$_447502                  SEQUENCE
TEST_POSTS                     TABLE
SQL> drop sequence ISEQ$$_447502;
drop sequence ISEQ$$_447502
*
ERROR at line 1:
ORA-32794: cannot drop a system-generated sequence
SQL> drop table "TEST_POSTS";
Table …
```

Address `ORA-32794: cannot drop a system-generated sequence`

---

issue_template.md

Referred the one from Rails repository https://github.com/rails/rails/blob/master/.github/issue_template.md and add necessary sections for Oracle enhanced adapter.
This time [ci skip] subject added to the commit message, not the subject of pull request. Will see how it goes.

[ci skip] Create an issue template

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb

Follow up to rails/rails#28938.

Deprecate `supports_statement_cache?`

---

lib/active_record/connection_adapters/oracle_enhanced/database_limits.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

To prepare longer identifier support in `nextval` branch.
Quoting module has implicit length information for
`NONQUOTED_OBJECT_NAME` and `NONQUOTED_DATABASE_LINK`, which will be addressed in another commit.

Introduce module `DatabaseLimits`

---

.travis.yml

CI for JRuby (jruby-9.1.8.0 and jruby-head) are slow,
taking 22 min to 24 min without this change.
This change improves CI for JRuby about 6 min to 7 min

Use Ubuntu 12.04

---

lib/active_record/connection_adapters/oracle_enhanced/database_limits.rb
lib/active_record/connection_adapters/oracle_enhanced/quoting.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb

* Refer "Oracle Database New Features Guide 12c Release 2 (12.2)"
https://docs.oracle.com/database/122/NEWFT/new-features.htm#GUID-64283AD6-0939-47B0-856E-5E9255D7246B
>> Long Identifiers
>> The maximum length of identifiers is increased to 128 bytes for most identifiers, up from 30 bytes in previous releases.
* Oracle Text Context index length is still 30 byte
* Remove `Digest::SHA1.hexdigest` for longer indexes. 128 byte length should be enough for most of cases

Support 128 byte identifiers

---

.github/stale.yml

This ticket requests to enable https://github.com/probot/stale to manage old issues.
Changed to close only stale issues, not old requests.

Install probot

---

lib/active_record/connection_adapters/oracle_enhanced/connection.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb

This commit mainly removes #{db_link} from metadata queries.
There are code remaining about db_link, other commits are coming.

Drop db_link support - remove #{db_link} from metadata queries

---

lib/active_record/connection_adapters/oracle_enhanced/connection.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

- Addresses these warnings:
```
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:577: warning: assigned but unused variable - db_link
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:692: warning: assigned but unused variable - db_link
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:841: warning: assigned but unused variable - db_link
lib/active_record/connection_adapters/oracle_enhanced/connection.rb:35: warning: assigned but unused variable - db_link
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb:218: warning: assigned but unused variable - db_link
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb:324: warning: assigned but unused variable - db_link …
```

Drop db_link support - `describe` does not return db_link

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

since it expects default value, not default sequence name.
```ruby
(byebug) row["data_default"]
"\"ORACLE_ENHANCED\".\"ISEQ$$_77358\".nextval"
```
Addresses #1318

Do not pass `sequence_name.nextval` to new_column second argument

---

.travis.yml

JRuby 9.1.9.0 has been released.
http://jruby.org/2017/05/16/jruby-9-1-9-0

CI against JRuby 9.1.9.0

---

.travis.yml

#1279 was opened while Oracle enhanced adapter was tested with jruby-head but no actions taken until JRuby 9.1.9.0 has been released.
This change may be too much but I think it is worth to try it.

Fail fast by removing ruby-head and jruby-head from allow_failures

---

.rubocop.yml

Refer https://github.com/bbatsov/rubocop/commit/54166bf76ba76b14f1bbc8a34165f175dbc3f227
```ruby
/path/to/oracle-enhanced/.rubocop.yml: Style/CaseIndentation has the wrong namespace - should be Layout
/path/to/oracle-enhanced/.rubocop.yml: Style/CommentIndentation has the wrong namespace - should be Layout
/path/to/oracle-enhanced/.rubocop.yml: Style/EmptyLines has the wrong namespace - should be Layout
/path/to/oracle-enhanced/.rubocop.yml: Style/EmptyLinesAroundClassBody has the wrong namespace - should be Layout
/path/to/oracle-enhanced/.rubocop.yml: Style/EmptyLinesAroundMethodBody has the wrong namespace - should be Layout
/path/to/oracle-enhanced/.rubocop.yml: Style/EmptyLinesAroundModuleBody has the wrong namespace - should be Layout
/path/to/oracle-enhanced/.rubocop.yml: …
```

rubocop namespace changes from `Style` to `Layout`

---

.travis.yml

JRuby 9.1.10.0 has been released.
http://jruby.org/2017/05/25/jruby-9-1-10-0.html

CI against JRuby 9.1.10.0

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

This PR will changing an error when using "nextval" with Oracle 12.1 or lower.
```console
rake aborted!
Your version of Oracle Database (11.2) is too old.
Active Record Oracle enhanced adapter 2 supports Oracle Database 12.2 or higher
/home/vagrant/src/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:229:in `initialize'
/home/vagrant/src/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:93:in `new'
/home/vagrant/src/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:93:in `oracle_enhanced_connection' …
```

Friendly "nextval" error when using Oracle 12.1 or lower

---

lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb

This pull request enables TCP keepalive for CRuby users. Thanks to ruby-oci8 2.2.4 new features.
https://github.com/kubo/ruby-oci8/blob/master/docs/hanging-after-inactivity.md

Enable TCP keepalive for CRuby

---

lib/active_record/connection_adapters/oracle_enhanced/structure_dump.rb
spec/active_record/connection_adapters/oracle_enhanced_structure_dump_spec.rb

Add min and max values, order and cycle flags.
These are sometimes needed when sequence is not solely used for id generation for example.
order flag is quite useful also sometimes for id generation.

Add sequence with settings to structure dump

---

.travis.yml

This PR backports #1359 to release18 branch.

CI against JRuby 9.1.12.0

---

lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb

Refer "Hanging After a Long Period of Inactivity"
http://www.rubydoc.info/github/kubo/ruby-oci8/file/docs/hanging-after-inactivity.md
Follow up for #1353.

Some platforms do not support `OCI8.properties[:tcp_keepalive_time]`

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb

rails/rails#29504 implements bulk insert for fixture load.
Oracle database needs another syntax.
In the mean time, this commit just falls back to conventional fixture load.
Refer rails/arel#482
This pull request addressses `ORA-00933` error.
```sql
$ ARCONN=oracle bin/test test/cases/aggregations_test.rb:126
Using oracle
Run options: --seed 3549
E
Error:
AggregationsTest#test_do_not_run_the_converter_when_nil_was_set:
ActiveRecord::StatementInvalid: OCIError: ORA-00933: SQL command not properly ended: INSERT INTO "CUSTOMERS" ("ID", "NAME", "BALANCE", "ADDRESS_STREET", "ADDRESS_CITY", "ADDRESS_COUNTRY", "GPS_LOCATION") VALUES (1, 'David', 50, 'Funny Street', 'Scary Town', 'Loony Land', '35.544623640962634x-105.9309951055148'), (2, 'Zaphod', 62, 'Avenue Road', 'Hamlet Town', 'Nation Land', …
```

Use conventional fixture load

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

This PR update documentation that Oracle enhanced adapter also work with Oracle 12c.

Update documentation that supported Oracle version [ci skip]

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Follow up of rails/rails#29869.

Make `type_map` to private because it is only used in the connection adapter

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb

Refer: https://github.com/rails/rails/commit/213796f
This pull request addresses these failures:
```ruby
$ bundle exec rspec ./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb:218
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb"=>[218]}}
F
Failures:
1) OracleEnhancedAdapter reserved words column quoting should create record
Failure/Error: super
ArgumentError:
wrong number of arguments (given 6, expected 1..5)
Finished in 0.40631 seconds (files took 0.77443 seconds to load)
1 example, 1 failure
Failed examples:
rspec ./spec/active_record/connection_adapters/oracle_enhanced_adapter …
```

Arity change in insert method

---

spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

Refer https://github.com/rails/arel/commit/db1bb4e9a728a437d16f8bdb48c3b772c3e4edb0
This pull request addresses these two failures:
```ruby
$ bundle exec rspec ./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb:525
==> Running specs with MRI version 2.5.0
/home/yahonda/git/rails/activesupport/lib/active_support/core_ext/hash/keys.rb:14: warning: method redefined; discarding old transform_keys
/home/yahonda/git/rails/activesupport/lib/active_support/core_ext/hash/keys.rb:25: warning: method redefined; discarding old transform_keys!
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb"=>[525]}}
F
Failures:
1) …
```

Arel::Nodes::BindParam#initialize introduced

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb

Follow up #1383 
This pull request addresses the following error:
```ruby
$ bundle exec rspec ./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb:573
==> Running specs with MRI version 2.5.0
/home/yahonda/git/rails/activesupport/lib/active_support/core_ext/hash/keys.rb:14: warning: method redefined; discarding old transform_keys
/home/yahonda/git/rails/activesupport/lib/active_support/core_ext/hash/keys.rb:25: warning: method redefined; discarding old transform_keys!
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb"=>[573]}}
F
Failures:
1) OracleEnhancedAdapter explain should explain query
Failure/Error: @raw_cursor.exec …
```

Address `ORA-00905: missing keyword: EXPLAIN PLAN FOR`

---

activerecord-oracle_enhanced-adapter.gemspec

Oracle enhanced adapter depends on ActiveRecord.
ActiveRecord depends on Arel which is described in activerecord/activerecord.gemspec
Related with https://github.com/rails/rails/commit/089ca520e32e8cd9ebe1075f491d7856683e6cde

Remove add_runtime_dependency with arel

---

Gemfile

This pull request implements a workaround for rails/arel#491 for Oracle Database 11gR2 or lower.
```ruby
NoMethodError:
undefined method `value_for_database' for #<Arel::Nodes::BindParam:0x000055852a3e64d0>
```
This commit will get reverted when rails/arel#491 is merged to master
or other fixes found.

Workaround rails/arel#491 for Oracle Database 11gR2 or lower

---

spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

Looks like this needs fixed at spec, not library code itself.
Refer #908 #1386

Skip `explain query with binds` for both CRuby and JRuby

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements_ext.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

This pull request moves methods for synonyms out of `SchemaStatementsExt`

Move methods for synonyms out of `SchemaStatementsExt`

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

I'm wondering why `data_sources` does not returns synonyms.
Current `data_sources` and `data_source_exist?` causes different behavior.
```ruby
conn.data_source_exist?('my_synonym') # => true
conn.data_sources.include?('my_synonym') # => false
```
I think synonyms are available as data source for AR models, so it is reasonable that `data_sources` includes synonyms.
Are there any reason to not treat synonyms as `data_sources` ?

Add synonyms in data_sources

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

```
$ grep require lib/active_record/connection_adapters/oracle_enhanced_adapter.rb | sort | uniq -c |grep 2
2 require "active_record/connection_adapters/oracle_enhanced/column_dumper"
2 require "active_record/connection_adapters/oracle_enhanced/context_index"
2 require "active_record/connection_adapters/oracle_enhanced/database_statements"
2 require "active_record/connection_adapters/oracle_enhanced/schema_statements"
```

Remove redundant requires

---

Gemfile

This reverts commit edf97598a844d530dd82446b74016197b66a5609.
rails/arel#491 has been merged to master branch. This workaround is not necessary anymore.

Revert "Workaround rails/arel#491 for Oracle Database 11gR2 or lower"

---

lib/active_record/connection_adapters/oracle_enhanced/column_dumper.rb

* `ActiveRecord::ColumnDumper` does not exist, it is harmless but should not exist.
* This module is included here:
https://github.com/rsim/oracle-enhanced/blob/master/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb#L166
```ruby
include ActiveRecord::ConnectionAdapters::OracleEnhanced::ColumnDumper
```

Remove incorrect prepend to `ActiveRecord::ColumnDumper`

---

.travis.yml

It cannot be a permanent fix since Ubuntu Presice is already EOL.
https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming

Set `dist: precise` explicitly to workaround #1397

---

lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb

It is just for context indexes. `ActiveRecord::SchemaDumper#indexes` is left just for indexes on materialized views which is not called from `ActiveRecord::SchemaDumper#tables`

Rename `SchemaDumper#indexes` to `SchemaDumper#_indexes`

---

lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb

Added gsub to handle "$" for `table_name_prefix` and `table_name_suffix`.

Rewrite `remove_prefix_and_suffix` to be similar with super

---

lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb

Implemented at Oracle enhanced locally first for rails/rails#30044 Thanks @kamipo

`remove_prefix_and_suffix` handles dollar sign by `Regexp#escape`

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb

Not sure how to test this, but seems to fix my use of activerecord-import over jruby

Fix cursor leak when using activerecord-import gem

---

lib/active_record/connection_adapters/oracle_enhanced/procedures.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

This removes deprecation warning inserted in https://github.com/rails/rails/commit/16ae3db5a5c6a08383b974ae6c96faac5b4a3c81
Deprecation warnings are now removed but smees like new methods are more recommendable.
This was problem when doublesaving like described by dhh: https://github.com/rails/rails/commit/16ae3db5a5c6a08383b974ae6c96faac5b4a3c81#commitcomment-20192607
Methods listed
https://github.com/rails/rails/pull/25337#issuecomment-225166796

Use new method name for active record dirty checks

---

spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

To avoid unnecessary stack trace. Here are differences between `pending` and `skip` of rspec.
https://relishapp.com/rspec/rspec-core/v/3-4/docs/pending-and-skipped-examples
> An example can either be marked as skipped, in which is it not executed, or pending in which it is executed but failure will not cause a failure of the entire suite.
* Without this pull request - using `skip`
```ruby
$ bundle exec rspec ./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb:579
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb"=>[579]}}
*
Pending: (Failures listed here are expected and do not …
```

Replace `pending` with `skip` not to execute the spec 

---

.travis.yml
.travis/oracle/install.sh

This pull request addresses #1397.
Open a support request with Travis CI and there is a solution provided to set disk_asynch_io=false'

Setting `disk_asynch_io` to `false` to address slow unit tests

---

.travis.yml
.travis/oracle/install.sh

Setting `disk_asynch_io` to `false` to address slow unit tests to release18 branch

---

lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb
spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb

Since rails/rails#30048 there is no Oracle enhanced specific implementation anymore.
Tests are covered by `ActiveRecord::TestCase::SchemaDumperTest`
Refer #1401 rails/rails#30044 rails/rails#30048

Remove `remove_prefix_and_suffix` and specs from Oracle enhanced adapter

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb

Follow up of rails/rails#29945.

Restore `to_sql` to return only SQL

---

spec/active_record/connection_adapters/oracle_enhanced_database_tasks_spec.rb

- `Tempfile#create` will create `File`
- `Tempfile#new` will create `Tempfile`, which "could be" deleted unexpectedly.
Refer #1427 and https://docs.ruby-lang.org/en/2.3.0/Tempfile.html

Use `Tempfile#create` instead of `Tempfile#new`

---

.travis/setup_accounts.sh
spec/support/alter_system_set_open_cursors.sql

set `open_cursor` value to `1200` which is larger than the default `:statement_limit` value `1000`

set `open_cursor` value to `1200` 

---

spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb

Remove `emulate_dates` and `emulate_dates_by_column_name` from `oracle_enhanced_data_types_spec.rb`
Also removed duplicate specs, updated spec names to use attribute API.
Refer #1449

Remove `emulate_dates` and `emulate_dates_by_column_name`

---

spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb

Remove `emulate_integers_by_column_name`  from `oracle_enhanced_data_types_spec.rb`
Also removed duplicate specs, updated spec names to use attribute API.
Refer #1449

Remove `emulate_integers_by_column_name` 

---

spec/active_record/connection_adapters/oracle_enhanced/schema_dumper_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/schema_statements_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/structure_dump_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

Actually current Oracle database does not support `drop table if exists`
sql statement like MySQL and PostgreSQL.
If you are interested in this feature implemented by Oracle database
itself please visit https://community.oracle.com/ideas/5212
Oracle enhanced adapter does not raise exceptions when `if_exists` set
to true.

Use `drop_table` if_exists: true` to avoid rescue nil

---

lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb
spec/active_record/connection_adapters/oracle_enhanced/schema_dumper_spec.rb

Oracle enhanced adapter implements table comments options
Refer rails/rails#28005 and #1439

Prefer to place a table options before `force: :cascade`

---

spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb
spec/active_record/oracle_enhanced/type/national_character_string_type_spec.rb

into `spec/active_record/oracle_enhanced/type/national_character_string_type_spec.rb`
`NationalCharacterString` may not be the best name but let's leave as it is.

Extract NationalCharacterString data type specs

---

lib/active_record/connection_adapters/oracle_enhanced/connection.rb

These 3 methods will need to move under `ActiveRecord::ConnectionAdapters::OracleEnhanced::DatabaseStatements`

Signature fix for  `select_one` `select_value` `select_values`

---

.gitignore
spec/spec_helper.rb

debug.log file will be rotated on each 100MB
Refer https://github.com/rails/rails/commit/64391cd520cd8aee2c8b9ba1b95e4aae4512a6a0

Always generate `debug.log` for unit tests

---

.codeclimate.yml

Refer https://github.com/codeclimate/codeclimate-rubocop/issues/99

Use `rubocop-0-49` channel to run rubocop 0.49

---

.travis.yml

https://github.com/rvm/rvm/pull/4159 needs merged.
Refer them for the fix included in the each release:
https://www.ruby-lang.org/en/news/2017/09/14/ruby-2-4-2-released/
https://www.ruby-lang.org/en/news/2017/09/14/ruby-2-3-5-released/
https://www.ruby-lang.org/en/news/2017/09/14/ruby-2-2-8-released/

Bump ruby versions to 2.4.2, 2.3.5 and 2.2.8 at Travis

---

lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb

Refer #1353 which was planned to support "nextval" branch. 
Since "nextval" plan has been cancelled, I think this feature can be available for 5.2.

Enable TCP keepalive for OCI connections 

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
lib/activerecord-oracle_enhanced-adapter.rb
spec/active_record/connection_adapters/oracle_enhanced/schema_dumper_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/schema_statements_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

Remove `OracleEnhancedAdapter.cache_columns` to use Rails `db:schema:cache:dump`
Oracle enhanced adapter had implemented its own `cache_columns`,
which can be replaced by Rails `db:schema:cache:dump` feature.
```ruby
$ rails -T
...
rails db:schema:cache:dump               # Creates a db/schema_cache.yml file
```
* Removed `ActiveRecord::ConnectionAdapters::OracleEnhancedAdapter.cache_columns`
* Removed `columns_without_cache` and `pk_and_sequence_for_without_cache` methods
* Skip specs for column caching

Remove `OracleEnhancedAdapter.cache_columns` 

---

README.md

`self.emulate_dates_by_column_name = true` entries from README
Both of them were removed from the code already.
https://github.com/rsim/oracle-enhanced/commit/b048415330a739e9cc5e7eed17e9883583b5b6a2

[ci skip] Remove `self.emulate_integers_by_column_name = true`

---

lib/active_record/connection_adapters/oracle_enhanced/context_index.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Oracle enhanced adapter has dropped its own column cache support.
also dropping its own caching index information which is used for schema dumper.
Unlike schema caching, index caching is not critical for applications.

Do not expose `all_schema_indexes`

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced/schema_dumper_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/schema_statements_spec.rb

The goal is to remove class variables from Oracle enhanced adapter

Remove @@do_not_prefetch_primary_key class variable

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

For larger database systems cursor_sharing has to be set to EXACT, there has been no way to run production with cursor_sharing=FORCE.
With cursor_sharing=EXACT and larger number of process starts statement execution of dictionary access SQLs without bind variables became an problem for database stability.

Using bind variables for dictionary access

---

lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb
spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb

Oracle enhanced adapter has been changing `cursor_sharing` parameter value to `force`
to share cursors between sql statements whose literal values are different.
However, prepared statements for dictionary queries will be enabled Oracle enhanced adapter 5.2 by #1498 and #1502,
Ther will be no need to change `cursor_sharing` value to `exact` anymore.
If you want to keep the current behavior in Rails 5.2, they can set `cursor_sharing: :force` explicitly in the database.yml.
Refer #1501

Respect database instance `cursor_sharing` value `exact` by default

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

This pull request addresses this error.
```ruby
$ ARCONN=oracle bin/test test/cases/comment_test.rb:152
Using oracle
Run options: --seed 49367
E
Finished in 0.155438s, 6.4334 runs/s, 0.0000 assertions/s.
1) Error:
CommentTest#test_change_table_comment_to_nil:
ActiveRecord::StatementInvalid: OCIError: ORA-01780: string literal required: COMMENT ON TABLE "COMMENTEDS" IS NULL
stmt.c:243:in oci8lib_250.so
/home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/ruby-oci8-2.2.4.1/lib/oci8/cursor.rb:130:in `exec'
/home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/ruby-oci8-2.2.4.1/lib/oci8/oci8.rb:277:in `exec_internal'
/home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/ruby-oci8-2.2.4.1/lib/oci8/oci8.rb:268:in `exec' …
```

Address `CommentTest#test_change_table_comment_to_nil` failure

---

.github/stale.yml

Created #1505 whose target is next major version which will be released
as Rails 6, It will not be likely available within 90 days.
Created `rails6` label to handle it.

Exclude `rails6` label  [skip ci]

---

lib/active_record/connection_adapters/oracle_enhanced/column.rb

Remove `value_to_boolean` which has been removed from Rails since 4.2
Refer https://github.com/rails/rails/commit/8f387995054d9ce79522da8ef65fba28c6ea0785

Remove `value_to_boolean` which has been removed from Rails

---

lib/active_record/connection_adapters/oracle_enhanced/column.rb

Refer https://github.com/rails/rails/commit/e2d19d60182b017bb092a018564d329c4f52b6a3
https://github.com/rails/rails/commit/8f387995054d9ce79522da8ef65fba28c6ea0785

Remove `string_to_date` which has been removed from Rails 4.2

---

lib/active_record/connection_adapters/oracle_enhanced/column.rb

Refer https://github.com/rails/rails/commit/8f387995054d9ce79522da8ef65fba28c6ea0785

Remove `string_to_time` which has been removed from Rails 4.2

---

lib/active_record/connection_adapters/oracle_enhanced/column.rb

since Oracle enhanced adapter 1.7
Refer #811

Remove `guess_date_or_time` which has not been called

---

spec/active_record/connection_adapters/oracle_enhanced/schema_statements_spec.rb

This pull request addresses the following warning below:
```ruby
$ bundle exec rspec spec/active_record/connection_adapters/oracle_enhanced/schema_statements_spec.rb:735
==> Running specs with MRI version 2.4.2
/home/yahonda/git/oracle-enhanced/spec/active_record/connection_adapters/oracle_enhanced/schema_statements_spec.rb:736: warning: assigned but unused variable - fk_name
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced/schema_statements_spec.rb"=>[735]}}
.
Finished in 0.46229 seconds (files took 0.91534 seconds to load)
1 example, 0 failures
Coverage report generated for RSpec to /home/yahonda/git/oracle-enhanced/coverage. 1076 / 2621 LOC (41.05%) …
```

Remove unsed `fk_name`

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Refer https://github.com/rails/rails/pull/4850 and follow-up #1516

`columns` second argument does not exist in Abstract adapter

---

lib/active_record/connection_adapters/oracle_enhanced/column.rb

Remove `ActiveRecord::ConnectionAdapter::OracleEnhanced::Column#returning_id?`
It has not been called since #795

Remove `OracleEnhanced::Column#returning_id?`

---

lib/active_record/connection_adapters/oracle_enhanced/column.rb

Remove `attr_reader :table_name` from `ActiveRecord::ConnectionAdapters::OracleEnhanced::Column`
Already set at `ActiveRecord::ConnectionAdapters::Column`

Remove `attr_reader :table_name`

---

lib/active_record/connection_adapters/oracle_enhanced/column.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb

Remove `returning_id` instance variable from `ActiveRecord::ConnectionAdapter::OracleEnhanced::Column`
Follow-up #1523

Remove `returning_id` instance variable

---

lib/active_record/connection_adapters/oracle_enhanced/column.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced/type_metadata.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb

There have been some refactoring `ActiveRecord::ConnectionAdapters::OracleEnhanced::Column` made. Now refactoring for  `virtual` type support remains.
This pull request is work in progress one. The main problem so far is `fetch_type_metadata` does not return ` ActiveRecord::ConnectionAdapters::OracleEnhanced::TypeMetadata` including `virtual` then it cannot handle `virtual` which used to be inside `ActiveRecord::ConnectionAdapters::OracleEnhanced::Column`.

Let `ActiveRecord::ConnectionAdapters::OracleEnhanced::TypeMetadata` handle `virtual` type

---

lib/active_record/connection_adapters/oracle_enhanced/schema_definitions.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Remove `lengths`, `where`, `using` from `OracleEnhanced::IndexDefinition`
because Oracle database does not support these options for indexes.
Meaning of each option from MySQL and PostgreSQL point of view:
- lengths
https://dev.mysql.com/doc/refman/5.7/en/create-index.html
> For string columns, indexes can be created that use only the leading part of column values, using col_name(length) syntax to specify an index prefix length:
- `where`
https://www.postgresql.org/docs/10/static/sql-createindex.html
> predicate
> The constraint expression for a partial index.
- `using
https://dev.mysql.com/doc/refman/5.7/en/create-index.html
> index_type
> Some storage engines permit you to specify an index type when creating an index.
Note: `orders` is not used by Oracle enhanced adapter but Oracle …

Remove `lengths`, `where`, `using` from `IndexDefinition`

---

.travis.yml

```ruby
The latest bundler is 1.16.0.pre.3, but you are currently running 1.15.4.
To update, run `gem install bundler --pre`
```
`--force` option added to replace pre-installed bundler for ruby-head

Use bundler 1.16.0.preX and update rubygems to the latest

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

```ruby
`initialize_type_map(m = type_map)`
`extract_value_from_default(default)`
`extract_limit(sql_type)`
`translate_exception(exception, message)`
```

These methods are private in `AbstractAdapter` or `PostgreSQLAdapter`

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Move `self.default_sequence_start_value` method close to other methods which can be used by the initializer.

Move `self.default_sequence_start_value` method

---

spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

Use ` ActiveRecord::OracleEnhanced::Type::Integer` not `ActiveRecord::Type::Integer`
* Steps to reproduce
```ruby
$ bundle exec rspec spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb:238
$ tail -f debug.log
```
* Without this commit:
```ruby
SQL (3.8ms)  SELECT * FROM test_posts WHERE 0=0 AND id = :a1  [[#<ActiveRecord::ConnectionAdapters::OracleEnhanced::Column:0x0000564f63b3e9b8 @name="id", @table_name="test_posts", @sql_type_metadata=#<ActiveRecord::ConnectionAdapters::SqlTypeMetadata:0x0000564f63b3eb20 @sql_type="NUMBER(38)", @type=:integer, @limit=38, @precision=38, @scale=nil>, @null=false, @default=nil, @default_function=nil, @collation=nil, @comment=nil>, 1]]
SQL (1.9ms)  SELECT * FROM test_posts WHERE 1=1 AND id = :a1 …
```

Show correct bind value information in debug.log

---

spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

Address explain with binds errors #908 #1386
Also allow "TABLE ACCESS FULL" operation since Oracle may choose this
plan as follows.
```ruby
$ bundle exec rspec spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb:318
==> Running specs with MRI version 2.4.2
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb"=>[318]}}
F
Failures:
1) OracleEnhancedAdapter explain should explain query with binds
Failure/Error: expect(explain).to include("INDEX UNIQUE SCAN")
expected EXPLAIN for: SELECT "TEST_POSTS".* FROM "TEST_POSTS" WHERE "TEST_POSTS"."ID" IS NULL
Plan hash value:...  1 - filter(NULL IS NOT NULL)
Note
-----
- dynamic …
```

Address explain with binds errors #908 #1386

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/jdbc_quoting.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_quoting.rb
lib/active_record/connection_adapters/oracle_enhanced/quoting.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
lib/active_record/type/oracle_enhanced/boolean.rb
lib/active_record/type/oracle_enhanced/integer.rb
lib/active_record/type/oracle_enhanced/json.rb
lib/active_record/type/oracle_enhanced/national_character_string.rb
lib/active_record/type/oracle_enhanced/national_character_text.rb
lib/active_record/type/oracle_enhanced/raw.rb
lib/active_record/type/oracle_enhanced/string.rb
lib/active_record/type/oracle_enhanced/text.rb
lib/active_record/type/oracle_enhanced/timestampltz.rb
lib/active_record/type/oracle_enhanced/timestamptz.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

Rename `ActiveRecord::OracleEnhanced::Type` to `ActiveRecord::Type::OracleEnhanced`
and use relative path to keep the same structure with Rails and make code shorter.
Except for specs, which would get this error:
```ruby
Failure/Error: binds = [ActiveRecord::Relation::QueryAttribute.new("id", 1, Type::OracleEnhanced::Integer.new)]
NameError:
uninitialized constant Type
```

Rename `ActiveRecord::OracleEnhanced::Type` to `ActiveRecord::Type::OracleEnhanced`

---

lib/active_record/connection_adapters/oracle_enhanced/schema_creation.rb

Address `MigrationTest#test_create_table_with_query_from_relation` error and suppress `DEPRECATION WARNING: Delegating ast to arel is deprecated
and will be removed in Rails 6.0. `
```ruby
$ ARCONN=oracle bin/test test/cases/migration_test.rb:518
Using oracle
Run options: --seed 37268
DEPRECATION WARNING: Delegating ast to arel is deprecated and will be removed in Rails 6.0. (called from visit_TableDefinition at /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/schema_creation.rb:40)
/home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:23:in `to_sql_and_binds'
/home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:13:in `to_sql' …
```

Address `MigrationTest#test_create_table_with_query_from_relation` error

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

it was added for `index_name` at e10bd49ecbaa0fb0dc0e87e6b0f6e0c7d9283354
Now `index_name` method has been migrated to `schema_statements.rb`

Remove unused `require "digest/sha1"`

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

`write_lobs` called from `insert_fixture`
then it should be better to be managed under the same module.

Move `write_lobs` under `OracleEnhanced::DatabaseStatements` module

---

lib/active_record/connection_adapters/oracle_enhanced/lob.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

To load LOB data from fixtures, Oracle enhanced adapter
has modified `ActiveRecore::Base`, which can be avoided
by introducing `OracleEnhanced::Lob` module using `ActiveSupport::Concern`
TODO:
like `ActiveRecord::ConnectionAdapters::OracleEnhanced::Lob` module
Refer http://api.rubyonrails.org/classes/ActiveSupport/Concern.html
this will be used for `insert_fixtures` which is defined in the Rails itself.

Introduce `OracleEnhanced::Lob` not to modify `ActiveRecord::Base` directly

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

* With this commit
```ruby
Foreign Keys to disable and enable (33.7ms)  SELECT constraint_name, owner, table_name FROM all_constraints WHERE constraint_type = 'R' AND status = 'ENABLED' AND owner = SYS_CONTEXT('userenv', 'session_user')
```
* Without this commit
```ruby
(35.1ms)            SELECT constraint_name, owner, table_name
FROM all_constraints
WHERE constraint_type = 'R'
AND status = 'ENABLED'
AND owner = SYS_CONTEXT('userenv', 'session_user')
```

Log the purpose of sql in `disable_referential_integrity`

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Follow up for #1550.
The following is a "Primary Key Trigger" log output by multi line.
```console
Primary Key Trigger (0.6ms)            SELECT trigger_name
FROM all_triggers
WHERE owner = :owner
AND trigger_name = :trigger_name
AND table_owner = :owner
AND table_name = :table_name
AND status = 'ENABLED'
[["owner", "ORACLE_ENHANCED"], ["trigger_name", "POSTS_PKT"],
["owner", "ORACLE_ENHANCED"], ["table_name", "POSTS"]]
```
The following is a "Primary Key Trigger" log output by single line.
```console
Primary Key Trigger (0.3ms)            SELECT trigger_name FROM
all_triggers WHERE owner = :owner AND trigger_name = :trigger_name AND
table_owner = :owner AND table_name = :table_name AND status = 'ENABLED'
[["owner", "ORACLE_ENHANCED"], ["trigger_name", "POSTS_PKT"],
["owner", …
```

Change log format of "Primary Key Trigger" to one line

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

[ci skip] No default value for `cursor_sharing`

---

lib/active_record/connection_adapters/oracle_enhanced/connection.rb

Remove `ActiveRecord ConnectionAdapters::OracleEnhanced::Connection#select_values`
to use `ActiveRecord::ConnectionAdapters::DatabaseStatements#select_values`.
As of right now, other similar methods are kept as they are.
- `ActiveRecord ConnectionAdapters::OracleEnhanced::Connection#select_one`
- `ActiveRecord ConnectionAdapters::OracleEnhanced::Connection#select_value` (without trailing `s`)
One of the reasons is when it is called
from `ActiveRecord::ConnectionAdapters::OracleEnhanced::Connection` class object as follows,
it is unable to call `ActiveRecord::ConnectionAdapters::DatabaseStatements#select_value` as super.
i.e.
```ruby
it "should use database default cursor_sharing parameter value exact by default" do
conn = ActiveRecord::ConnectionAdapters::OracleEnhanced::Connection.create( …
```

Remove `OracleEnhanced::Connection#select_values`

---

spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb

Avoid using `ActiveRecord::ConnectionAdapters::OracleEnhanced::Connection#select_value`
by not using `ActiveRecord::ConnectionAdapters::OracleEnhanced::Connection.create`
if connections made with `ActiveRecord::ConnectionAdapters::OracleEnhanced::Connection.create`
`select_value` calls `ActiveRecord::ConnectionAdapters::OracleEnhanced::Connection#select_value`.
Because `ActiveRecord::ConnectionAdapters::OracleEnhanced::Connection.create` creates
database connections with `OracleEnhanced::OCIConnection` and `OracleEnhanced::JDBConnection` classes.
Both of them do not know `ActiveRecord::ConnectionAdapters::DatabaseStatements#select_value` .

Avoid using `OracleEnhanced::Connection#select_value`

---

lib/active_record/connection_adapters/oracle_enhanced/lob.rb

Refer https://github.com/rails/rails/issues/23589
and https://github.com/plataformatec/devise/commit/c2c74b0a39238e7d997486814a1c8f75fdaf276f
Follow up #1547

Use `ActiveSupport.on_load` to hook into `ActiveRecord::Base`

---

lib/active_record/connection_adapters/oracle_enhanced/connection.rb
lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb

which is only called from its subclasses of `OracleEnhanced::Connection`
`describe` method may be appropriate to move to `OracleEnhanced::SchemaStatements`
which has `table_exists?` or similar methods.
but I'd like to postpone this decision. Just make it private now.

Make `OracleEnhanced::Connection#describe` private

---

.travis.yml

https://rubygems.org/gems/bundler/versions/1.16.0

bundler 1.16.0 is out, no more --pre

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

`VARCHAR2 columns with FLAG or YN at the end of their name` as boolean anymore since Rails 5.0.
Refer #1045 to register and use `:boolean` type explicitly.

[skip ci] `emulate_booleans_from_strings` does not handle

---

lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb

since ruby-oci8 2.0.4 returns BigDecimal.
Refer:
https://github.com/rsim/oracle-enhanced/commit/ce42b6ee9022bd0d723416440f7b447a6abe7d71
https://github.com/kubo/ruby-oci8/commit/76eb8f7b80e58e0f72a7c7d0bcdc9ecf475858f8

Remove `OCIConnection#typecast_result_value` handling `OraNumber`

---

lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb

`JDBCConnection#exec_with_returning`
Both of them have not called since https://github.com/rsim/oracle-enhanced/commit/5b1198b03fbd6369c88faff9efc65916526657b8
Refer #33

Remove `OCIConnection#exec_with_returning` and

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb

This method call was removed at https://github.com/rsim/oracle-enhanced/commit/35c4aa10a6a96a014f42e560c0f3486c45a1b015 then restored for JRuby only at ac0297d3c1634d35342aea263c92af2506c1df48
Considered the original implementation at https://github.com/rsim/oracle-enhanced/commit/d4128fa41e169f41c5afa52a770e3dc98c9b418e , it should be called on both JRuby and CRuby

Restore calling `OCIConnection#bind_returning_param`

---

lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb

when value is a `Date` or `DateTime` class. This case has not been chosen now.

Update `JDBCConnection#bind_param` case condition

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

ORA-00900 "invalid SQL statement"
ORA-00904 "invalid identifier"
ORA-17008 "Closed Connection"
ORA-17008 is likely reported only with JRuby and JDBC driver.
This pull request addresses these 3 failures when tested with JRuby.
```ruby
$ ARCONN=oracle bin/test test/cases/migration/columns_test.rb:84
... snip ...
Using oracle
Run options: --seed 6074
F
Finished in 1.606378s, 0.6225 runs/s, 0.6225 assertions/s.
1) Failure:
ActiveRecord::Migration::ColumnsTest#test_rename_nonexistent_column [/home/yahonda/git/rails/activerecord/test/cases/migration/columns_test.rb:84]:
[ActiveRecord::StatementInvalid] exception expected, not
Class: <NativeException>
Message: <"java.sql.SQLSyntaxErrorException: ORA-00904: \"NONEXISTENT\": invalid identifier\n"> …
```

Add these errors to be recognized as `ActiveRecord::StatementInvalid`

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

```sql
ORA-02289: "sequence does not exist"
```
This pull request addresses the following failure with JRuby.
```ruby
$ ARCONN=oracle bin/test test/cases/migration_test.rb:577
Using oracle
Run options: --seed 35273
F
Finished in 3.232012s, 0.3094 runs/s, 0.3094 assertions/s.
1) Failure:
MigrationTest#test_create_table_with_custom_sequence_name [/home/yahonda/git/rails/activerecord/test/cases/migration_test.rb:577]:
[ActiveRecord::StatementInvalid] exception expected, not
Class: <NativeException>
Message: <"java.sql.SQLSyntaxErrorException: ORA-02289: sequence does not exist\n">
oracle/jdbc/driver/T4CTTIoer11.java:494:in `processError'
oracle/jdbc/driver/T4CTTIoer11.java:446:in `processError'
oracle/jdbc/driver/T4C8Oall.java:1054:in `processError' …
```

Add `ORA-02289` to be recognized as `ActiveRecord::StatementInvalid`

---

lib/active_record/connection_adapters/oracle_enhanced/type_metadata.rb

by implementing `OracleEnhanced::TypeMetadata#==` and other methods.
Refer https://github.com/rails/rails/commit/158c7eb1d61a28452e0aafd1e05314352eea2749
```ruby
$ ARCONN=oracle bin/test test/cases/base_test.rb:1188
Using oracle
Run options: --seed 59553
F
Finished in 39.866759s, 0.0251 runs/s, 0.3010 assertions/s.
1) Failure:
BasicsTest#test_clear_cache! [/home/yahonda/git/rails/activerecord/test/cases/base_test.rb:1188]:
No visible difference in the Array#inspect output.
You should look at the implementation of #== on Array or its members.
[#<ActiveRecord::ConnectionAdapters::OracleEnhanced::Column:0xXXXXXX @table_name="posts", @name="id", @collation=nil, @default_function=nil, @sql_type_metadata=#<ActiveRecord::ConnectionAdapters::SqlTypeMetadat …
```

Address `BasicsTest#test_clear_cache!` failure

---

guides/bug_report_templates/active_record_gem.rb
guides/bug_report_templates/active_record_gem_spec.rb

Use Bundler 1.15 to workaround bundler/bundler#6072
Related to rails/rails#31039
```ruby
$ ruby -v
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
$ bundler -v
Bundler version 1.16.0
$
```
```ruby
$ cd guides/bug_report_templates/
$ ruby active_record_gem.rb
... snip ...
/home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:28:in `block in setup': rake-12.2.1 is missing. Run `bundle install` to get it. (Bundler::GemNotFound)
from /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/2.4.0/forwardable.rb:229:in `each'
from /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/2.4.0/forwardable.rb:229:in `each'
from /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:26:in `map'
from …
```

Use Bundler 1.15 to workaround bundler/bundler#6072

---

lib/active_record/connection_adapters/oracle_enhanced/context_index.rb

This pull request has been created for some more discussion in advance in case rails/rails/#27947 merged to master.
It is easy to suppress `DEPRECATION WARNING: Dangerous query method` by adding `Arel.sql` but I am not sure if it is a better way to implement it.

Suppress `DEPRECATION WARNING: Dangerous query method`

---

lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

This PR translates `ORA-00060` into `ActiveRecord::Deadlocked` error.
Added an `ORA-00060` reproduction test case equivalent to activerecord/test/cases/adapters/mysql2/transaction_test.rb.
https://github.com/rails/rails/blob/8f2490b57f488ed60fc6e0a201ccd5e66811ab51/activerecord/test/cases/adapters/mysql2/transaction_test.rb#L36-L61
The following is a reproduce testing log.
```console
% bundle exec rspec ./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb:575
(snip)
1) OracleEnhancedAdapter Transaction Raises Deadlocked when a deadlock
is encountered
Failure/Error:
expect {
barrier = Concurrent::CyclicBarrier.new(2)
t1 = TestPost.create(title: "one")
t2 = TestPost.create(title: "two")
thread = Thread.new do
TestPost.transaction do
t1.lock!
barrier.wait
expected …
```

Translate `ORA-00060` into `ActiveRecord::Deadlocked` error

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

ORA-02449: unique/primary keys in table referenced by foreign keys
This pull request addresses this failure when tested with JRuby.
```ruby
$ ARCONN=oracle bin/test test/cases/migration/change_schema_test.rb:457
Using oracle
Run options: --seed 28400
F
Finished in 1.530418s, 0.6534 runs/s, 0.6534 assertions/s.
1) Failure:
ActiveRecord::Migration::ChangeSchemaWithDependentObjectsTest#test_create_table_with_force_cascade_drops_dependent_objects [/home/yahonda/git/rails/activerecord/test/cases/migration/change_schema_test.rb:457]:
[ActiveRecord::StatementInvalid] exception expected, not
Class: <NativeException>
Message: <"java.sql.SQLException: ORA-02449: unique/primary keys in table referenced by foreign keys\n">
oracle/jdbc/driver/T4CTTIoer11.java:494:in `processError' …
```

Add `ORA-02449` to be recognized as `ActiveRecord::StatementInvalid`

---

spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

Follow up of #1591.
This is my mistake 💦  This commit fixes the position of `after(:all)` used for spec of `ActiveRecord::Deadlocked`.

Fix `after(:all)` in oracle_enhanced_adapter_spec.rb

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

Follow up of https://github.com/rails/rails/commit/01fb0907b2dafcecf63eedb80408d4cbff5f4d23
And fix the following build error.
https://travis-ci.org/rsim/oracle-enhanced/builds/310949529
```console
% bundle exec rspec ./spec/active_record/connection_adapters/oracle_enhanced/structure_dump_spec.rb:167
Failures:
1) OracleEnhancedAdapter structure dump structure dump should dump unique keys
Failure/Error: super(table, name, unique, columns, orders: orders, type: type)
NoMethodError:
undefined method `size' for nil:NilClass
(snip)
1 example, 1 failure
```

Refactor index options dumping

---

.travis.yml

JRuby 9.1.15.0 has been released.
http://jruby.org/2017/12/07/jruby-9-1-15-0.html

CI against JRuby 9.1.15.0

---

.travis.yml

This PR backports #1608 to release18 branch.

Use latest Rubies on Travis CI

---

.travis.yml

because Ruby 2.5.0 does not have bundler by default.

Remove `--force` option for installing bundler

---

.travis.yml

https://www.ruby-lang.org/en/news/2017/12/25/ruby-2-5-0-released/

CI with Ruby 2.5.0

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/oracle_enhanced/type/boolean_spec.rb

Do not register `VARCHAR2(1)` sql type as `Type:Boolean` if `emulate_booleans_from_strings = true`
Users will need to set `attribute` explicitly as follows if `emulate_booleans_from_strings = true`
```ruby
class Post < ActiveRecord::Base
attribute :is_default, :boolean
end
```
Address #1621

Do not register `VARCHAR2(1)` sql type as `Type:Boolean`

---

.travis.yml

This reverts commit 81927d600d52aa7237642f23280a393685c539b0.
Since https://github.com/bundler/bundler/issues/6228 has been closed.

Revert "allow_railures for jruby-head until #1614 resolved"

---

.travis.yml

This is part of #1651. Wanted to make #1652 CI green first.

Do not run CI against Ruby 2.2, which will not be supported with Rails 6

---

spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

It should suppress this exception reported at  https://travis-ci.org/rsim/oracle-enhanced/jobs/342649225
```ruby
<Thread:0x00000000043db450@/home/travis/build/rsim/oracle-enhanced/spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb:583 run> terminated with exception (report_on_exception is true):
```

Suppress expected exceptions by `report_on_exception` = `false`

---

.travis.yml

http://jruby.org/2018/02/21/jruby-9-1-16-0.html
This pull request only goes to release52 branch. Rails master branch requires Ruby 2.4.1+ which will be compatible with current JRuby master branch.

CI with JRuby 9.1.16.0

---

spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

`report_on_exception` is available since Ruby 2.4
Refer https://github.com/rails/rails/commit/b1a9cee83082d6c7a58d87d06055c86fcdbc7644

Remove unnecessary `respond_to?(:report_on_exception)`

---

spec/active_record/connection_adapters/oracle_enhanced/context_index_spec.rb

Refer https://github.com/rails/rails/commit/5645149d3a27054450bd1130ff5715504638a5f5
This pull request suppresses these warnings:
```ruby
$ bundle exec rspec spec/active_record/connection_adapters/oracle_enhanced/context_index_spec.rb
==> Running specs with MRI version 2.6.0
==> Effective ActiveRecord version 6.0.0.alpha
.....DEPRECATION WARNING: update_attributes! is deprecated and will be removed from Rails 6.1 (called from block (3 levels) in <top (required)> at /home/yahonda/git/oracle-enhanced/spec/active_record/connection_adapters/oracle_enhanced/context_index_spec.rb:134)
DEPRECATION WARNING: update_attributes! is deprecated and will be removed from Rails 6.1 (called from block (3 levels) in <top (required)> at …
```

`update_attributes!` will be deprecated in Rails 6

---

spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

Follows up #1665
This pull request should suppress these deprecation warnings shown at https://travis-ci.org/rsim/oracle-enhanced/jobs/348521316
```ruby
DEPRECATION WARNING: update_attributes is deprecated and will be removed from Rails 6.1 (called from block (6 levels) in <top (required)> at /home/travis/build/rsim/oracle-enhanced/spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb:588)
DEPRECATION WARNING: update_attributes is deprecated and will be removed from Rails 6.1 (called from block (5 levels) in <top (required)> at /home/travis/build/rsim/oracle-enhanced/spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb:596)
```

`update_attributes` will be deprecated in Rails 6

---

lib/active_record/connection_adapters/oracle_enhanced/connection.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_definitions.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced/schema_dumper_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/schema_statements_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

Oracle enhanced adapter 6 drops support for db link
If users need to use database link, please consider to
- Use multiple database connections
- Create a view over the database link

Drop db link support

---

lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced/structure_dump.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb

Also updated a spec not to update `current_user` method
Since#742 most of method should use `current_schema` to find schema
objects.
This pull request should not be backported into release52 branch.
I believe it will not cause regressions but this may change some
untested/undefined behavior.

Use `SYS_CONTEXT('userenv', 'current_schema')` to find schema objects

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced/schema_statements_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

Use `SYS_CONTEXT('userenv', 'current_schema')` for owner not using owner value from `OracleEnhanced::Connection#describe`
This is a first step to remove `OracleEnhanced::Connection#describe`. `OracleEnhanced::Connection#describe` method executes SQL query for the data dictionary, which can be reduced.
Also `describe` method is owned by `OracleEnhanced::Connection`, not `OracleEnhanedAdapter`, therefore this method is not reachable from other modules.

Use `SYS_CONTEXT('userenv', 'current_schema')` for owner

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
spec/active_record/connection_adapters/oracle_enhanced/schema_statements_spec.rb

Follow up of #1668.
This PR removes the codes that seems to have forgotten to remove in the above.

Remove db link codes

---

.travis.yml

https://www.ruby-lang.org/en/news/2018/03/28/ruby-2-5-1-released/

CI with Ruby 2.5.1

---

.travis.yml

https://www.ruby-lang.org/en/news/2018/03/28/ruby-2-4-4-released/

CI against Ruby 2.4.4

---

.travis.yml

https://www.ruby-lang.org/en/news/2018/03/28/ruby-2-3-7-released/
https://www.ruby-lang.org/en/news/2018/03/28/ruby-2-2-10-released/

Use ruby 2.3.7 and 2.2.10 for CI at release52 branch

---

lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb

I ran into this issue with NLS date/timestamp formats recently. I hadn't configured any of
the [optional NLS parameters](https://github.com/rsim/oracle-enhanced/blob/master/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb#L118) and knew that `nls_date_format` and `nls_timestamp_format` were unsupported, but was still running into this catastrophic error:
```
OCIError: ORA-01830: date format picture ends before converting entire input string
```
It turned out that the machine I was running on had the `NLS_TIMESTAMP_FORMAT` environment variable set and oracle_enhanced was consuming it and using the non-standard format.
This is probably not a commonly-encountered situation, but it was very confusing and time-consuming to track down for me. This PR I think makes this …

Don't allow unsupported NLS parameters

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

Address #1673
Kind of restoring #1496 using instance variable `@do_not_prefetch_primary_key`
Oracle enhanced adapter 1.8 or older used to have `@@do_not_prefetch_primary_key`
and other class variables to cache schema information.
Starting from Oracle enhanced adapter 5.2,
it starts using Rails standard `rails db:schema:cache` .
But it does not look like cacheing sequence names for primary keys
since no bundled database adapters - sqlite3, mysql2 and postgresql use prefetch primary key,
then sequence name for the table may not be included in the schema cache, I guess.
Backporting #1699 to release52 branch

Memoize if the table needs to prefetch primary key

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced/schema_statements_spec.rb

Longer identifier has been supported by aliasing `table_alias_length` and `index_name_length` method defined in `ActiveRecord::ConnectionAdapters::OracleEnhanced::DatabaseLimits` to use `max_identifier_length` method newly creted in `ActiveRecord::ConnectionAdapters::OracleEnhanced::OracleEnhancedAdapter`. Because ActiveRecord::ConnectionAdapters::OracleEnhanced::DatabaseLimits does not know the database version.
Refer
https://docs.oracle.com/en/database/oracle/oracle-database/12.2/sqlrf/Database-Object-Names-and-Qualifiers.html#GUID-75337742-67FD-4EC0-985F-741C93D918DA
Not implemented in this commit:
* Support longer identifiers for column name, sequence name
* Use 30 byte identifier for Oracle database 12.2 for those who prefer old behavior.
Addresses #1594

Support longer identifier for Oracle database 12.2 or higher

---

spec/active_record/connection_adapters/oracle_enhanced/schema_statements_spec.rb

Follows up #1703 to validate longer identifier for column names.
> Support longer identifiers for column name, sequence name

Add spec for `add_column` to support longer identifier

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

to support shorter 30 bytes identifier for Oracle 12.2 or higher
Follows up #1703

Introduce `use_shorter_identifier`

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
spec/active_record/connection_adapters/oracle_enhanced/schema_statements_spec.rb

If users want to see materialized views, call `OracleEnhanced::SchemaStatements#materialized_views`
Addresses #1505

`OracleEnhanced::SchemaStatements#tables` excludes materialized views

---

Gemfile

Arel is part of Rails now https://github.com/rails/rails/pull/32097

Remove `rails/arel` from Gemfile

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

since these methods called via `to_sql` method under `unprepared_statement`
Fix #1678 Backports #1713 to release52 branch
Starting from Oracle enhanced adapter 5.2.0.beta1 most of the queries for the dictionary, such as all_sequences use bind variables by #1498 .
It should help shared memory usage however, which eventually means Oracle enhanced adapter 5.2+ only supports `prepared_statements: true`
as Rails default configuration but it does not support `prepared_statements: false`.
Even if `prepared_statements: true`, `to_sql` uses `unprepared_statement` to generate SQL statement. If the connection already knows which table is associated with which model object in advance, `to_sql` works fine but when `to_sql` executed first the connection needs to know these relation then call …

Use SQL literals for `column_definitions` and `pk_and_sequence_for`

---

guides/bug_report_templates/active_record_gem.rb
guides/bug_report_templates/active_record_gem_spec.rb

Arel is now bundled in the Active Record gem, and maintained in the rails/rails repository.
Related PR is #1711.

Remove `rails/arel` from bug report templates [skip ci]

---

.travis.yml

Refer
https://changelog.travis-ci.com/rubygems-updates-60220
> This update fixes failures with bundle exec commands, where the previous workaround was to add gem install bundler to your .travis.yml configuration file.
https://github.com/travis-ci/travis-ci/issues/8969#issuecomment-390330259
https://github.com/travis-ci/travis-ci/issues/9333#issuecomment-390330511
> I think I tracked down the issue to an older version of RubyGems in use by the current Ruby 2.5.1, 2.5.0, 2.4.4 archives (there may be others). I've repackaged the affected Linux archives so that they use RubyGems 2.7.7 (there should be a line in your build log gem --version inside the ruby --version fold; cf. https://travis-ci.com/BanzaiMan/vandamme/builds/73872255#L475). If applicable, please try restarting the affected job, …

Do not install bundler explicitly

---

.rubocop.yml
spec/active_record/connection_adapters/oracle_enhanced/schema_dumper_spec.rb

Follow up of rails/rails#32381.
In addition, this PR applies the following auto-correct.
```console
% rubocop -a
Inspecting 64 files
..........C.....................................................
Offenses:
spec/active_record/connection_adapters/oracle_enhanced/schema_dumper_spec.rb:22:5:
C: [Corrected] Performance/RedundantMerge: Use options[:force] = true
instead of options.merge! force: true.
options.merge! force: true
^^^^^^^^^^^^^^^^^^^^^^^^^^
64 files inspected, 1 offense detected, 1 offense corrected
```

Turn on performance based cops

---

lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb

This PR backports #1742 into release52 branch.
Follow up of rails/rails#31435.
```console
% bundle exec rspec
(snip)
/home/travis/build/rsim/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb:484:
warning: BigDecimal.new is deprecated
```
https://travis-ci.org/rsim/oracle-enhanced/jobs/409700715#L775
This is a warning found in JRuby, but this commit has made same changes to MRI (OCI connection) .

Suppress warning `BigDecimal.new` is deprecated

---

lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb
spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb

It actually reverts #1503
#1498 implemented prepared statements for dictionary queries. However #1713 restored non-prepared statements for `column_definitions` and `pk_and_sequence_for`, which likely have caused
longer elapsed time for these queries reported at #1720
Those who need 'cursor_sharing = exact' can specify its own value to .database.yml

Use cursor_sharing = force by default again

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

Add table_name search condition to `indexes(table_name)` method and restored one spec which has been removed at https://github.com/rsim/oracle-enhanced/pull/1672
Related to #1720

Add table_name search condition to `indexes(table_name)` method

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

rsim/oracle-enhanced#1490 removed Oracle enhanced adapter own column cache feature
to use Rails `db:schema:cache:dump`.  However, it caused slower performance
about metadata search, such as column information.
This commit restores Oracle enhanced adapter own column cache feature.
It used to be class level caching, it is connection level caching now
since it is much easier and cleaner than class level ones.
Related to rsim/oracle-enhanced#1720

Introduce column cache per connection

---

lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb
spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb

Stop using NativeException

---

lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb

This returns easier to understand error message
Before this error in default full rails engine
```An error occurred while loading ./spec/spec_name_spec.rb.
Failure/Error: ActiveRecord::Migration.maintain_test_schema!
LoadError:
load error: rails_helper -- java.lang.NullPointerException: null
```
After this
```An error occurred while loading ./spec/spec_name_spec.rb.
Failure/Error: ActiveRecord::Migration.maintain_test_schema!
RuntimeError:
password not set

Do not set nil value to java.util.Properties

---

lib/active_record/connection_adapters/oracle_enhanced/database_limits.rb

This pull request addresses these two failures to support https://github.com/rails/rails/pull/33799
```ruby
$ ARCONN=oracle bundle exec ruby -w -Itest test/cases/adapter_test.rb -n /length_is_deprecated/
... snip ...
Using oracle
Run options: -n /length_is_deprecated/ --seed 13009
.F
Failure:
ActiveRecord::AdapterTest#test_column_name_length_is_deprecated [test/cases/adapter_test.rb:306]:
Expected a deprecation warning within the block but received none
rails test test/cases/adapter_test.rb:305
F
Failure:
ActiveRecord::AdapterTest#test_table_name_length_is_deprecated [test/cases/adapter_test.rb:310]:
Expected a deprecation warning within the block but received none
rails test test/cases/adapter_test.rb:309
Finished in 0.020496s, 146.3696 runs/s, 146.3696 assertions/s.
3 runs, 3 …
```

Deprecated `table_name_length` and `column_name_length`

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Refer https://github.com/rails/rails/commit/59c3ed1b3f9
```ruby
$ ARCONN=oracle bundle exec ruby -w -Itest test/cases/adapter_test.rb -n test_foreign_key_violations_on_delete_are_translated_to_specific_exception
... snip ...
F
Failure:
ActiveRecord::AdapterForeignKeyTest#test_foreign_key_violations_on_delete_are_translated_to_specific_exception [test/cases/adapter_test.rb:368]:
[ActiveRecord::InvalidForeignKey] exception expected, not
Class: <ActiveRecord::StatementInvalid>
Message: <"OCIError: ORA-02292: integrity constraint (ARUNIT.FK_NAME) violated - child record found: DELETE FROM fk_test_has_pk WHERE pk_id = 1">
stmt.c:243:in oci8lib_260.so
/home/yahonda/.rbenv/versions/2.6.0-dev/lib/ruby/gems/2.6.0/gems/ruby-oci8-2.2. …
```

Handle ORA-02292 as `InvalidForeignKey`

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

Follow up of #1770.
```console
% bundle exec rspec ./spec/active_record/connection_adapters/oracle_enhanced/schema_statements_spec.rb
==> Running specs with MRI version 2.5.1
==> Effective ActiveRecord version 6.0.0.alpha
..............DEPRECATION WARNING: table_name_length is deprecated and
will be removed from Rails 6.1 (called from rename_table at
/home/vagrant/src/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb:249)
(snip)
Finished in 14.69 seconds (files took 0.59003 seconds to load)
77 examples, 0 failures, 2 pending
```
This PR replaces `table_name_length` with `DatabaseLimits::IDENTIFIER_MAX_LENGTH`. `DatabaseLimits::IDENTIFIER_MAX_LENGTH` is the value …

Suppress deprecated warning for `table_name_length`

---

.travis.yml

https://www.ruby-lang.org/en/news/2018/10/17/ruby-2-4-5-released/
https://www.ruby-lang.org/en/news/2018/10/17/ruby-2-5-2-released/

CI against Ruby 2.5.2 and 2.4.5

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Follow up of rails/rails#34232.
This PR adds a check to supported Oracle database version.

Add a check to supported Oracle database version

---

.travis.yml

https://www.ruby-lang.org/en/news/2018/10/18/ruby-2-5-3-released/

CI against Ruby 2.5.3

---

.travis.yml

This reverts commit 5fe95d42f48d134406ac9f607aecef6e0a5b5fb3.
Since #1737 has been resolved.

Revert "Add allow_railures for jruby-head until #1737 resolved"

---

.travis.yml

JRuby 9.2.1.0 has been released.
https://www.jruby.org/2018/11/06/jruby-9-2-1-0.html

CI against JRuby 9.2.1.0

---

.travis.yml

JRuby 9.2.4.0 has been released.
https://www.jruby.org/2018/11/13/jruby-9-2-4-0.html

CI against JRuby 9.2.4.0

---

.travis.yml

This pull request upgrades Ubuntu version to Xenial at Travis CI 
https://docs.travis-ci.com/user/reference/xenial/

Use Ubuntu Xenial at Travis CI

---

.travis.yml

JRuby 9.2.5.0 has been released.
https://www.jruby.org/2018/12/06/jruby-9-2-5-0

CI against JRuby 9.2.5.0

---

Gemfile

This pull request backports #1804 to release52 branch.

Use i18n 1.2 for JRuby now

---

.travis.yml

Kind of backporting #1806 to release52 and revert #1740 since #1737 had been addressed.

CI against Ruby 2.6 and bump other Ruby versions

---

.travis.yml

https://travis-ci.org/rsim/oracle-enhanced/jobs/475937653
```
$ bundle install
The program 'bundle' is currently not installed. To run 'bundle' please ask your administrator to install the package 'bundler'
The command "bundle install" failed and exited with 127 during .
```

Install bundler and fallback to 1.7.3 if Bundler 2 is not available

---

.rubocop.yml
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb
spec/active_record/oracle_enhanced/type/character_string_spec.rb

This cop does not support auto correct, fixed these offenses manually.
```ruby
$ rubocop -v
0.62.0
$ rubocop -a
Inspecting 65 files
........W.........W....................................W.........
Offenses:
spec/active_record/oracle_enhanced/type/character_string_spec.rb:33:5: W: Lint/UselessAssignment: Useless assignment to variable - item.
item = TestItem.create!
^^^^
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb:299:37: W: Lint/UselessAssignment: Useless assignment to variable - i.
@employee.create!(sort_order: i += 1, first_name: "Natasha", last_name: "Romanova")
^
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb:55:20: W: Lint/UselessAssignment: Useless assignment to variable - table_name. Use _ or _table_name as a variable name to …
```

Enable `Lint/UselessAssignment` cop

---

.rubocop.yml
lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb

Follow up of https://github.com/rails/rails/pull/34903.
This PR auto-corrects the following offense.
```console
% rubocop -a
Inspecting 66 files
...........................................................W......
Offenses:
lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb:29:17:
W: [Corrected] Lint/DeprecatedClassMethods: File.exists? is deprecated
in favor of File.exist?.
if File.exists?(file_path = File.join(dir, ojdbc_jar))
^^^^^^^
66 files inspected, 1 offense detected, 1 offense corrected
```

Enable `Lint/DeprecatedClassMethods` cop

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb

Follow up of https://github.com/rails/rails/commit/400ba786e1d154448235f5f90183e48a1043eece.

Remove deprecated `#insert_fixtures` method for Rails 6.0

---

lib/active_record/connection_adapters/oracle_enhanced/schema_definitions.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

Fixes #1817.
Follow up of https://github.com/rails/rails/commit/57015cdfa2083351f64a82f7566965172a41efcb.

Make `t.timestamps` with precision by default

---

.travis.yml

This pull request addresses the following error.
https://travis-ci.org/rsim/oracle-enhanced/jobs/484610915
```ruby
$ gem install bundler
ERROR:  Error installing bundler:
bundler requires Ruby version >= 2.3.0.
The command "gem install bundler" failed and exited with 1 during .
```

Fallback to bundler 1.7.3 if bundler 2 is not available

---

lib/active_record/connection_adapters/oracle_enhanced/schema_creation.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Follow up of https://github.com/rails/rails/pull/35212.
This PR fixes the following error.
```console
$ bundle exec rspec ./spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb:179
(snip)
Failures:
1) OracleEnhancedConnection default_timezone should respect
default_timezone = :utc than time_zone setting
Failure/Error: if supports_foreign_keys_in_create?
NoMethodError:
undefined method `supports_foreign_keys_in_create?' for
#<ActiveRecord::ConnectionAdapters::OracleEnhanced::SchemaCreation:0x0000000003ef9108>
Did you mean?  supports_foreign_keys?
```
https://travis-ci.org/rsim/oracle-enhanced/jobs/492524301#L932

Use `supports_foreign_keys?` instead of removed `supports_foreign_keys_in_create?`

---

.travis.yml

JRuby 9.2.6.0 has been released.
https://www.jruby.org/2019/02/11/jruby-9-2-6-0

CI against JRuby 9.2.6.0

---

lib/active_record/connection_adapters/oracle_enhanced/schema_definitions.rb

Oracle enhanced adapter :integer is mapped to `NUMBER(38)` sql type,
:bigint is mapped to `NUMBER(19)` sql type.
Unlike other database adapters whose :integer is mapped to `INT(4)`,
Oracle enhanced adapter :integer is larger than :bigint.
Oracle enhanced adapter `primary_key` is mapped to `NUMBER(38)`, not `NUMBER(19)`
`references` should be mapped to `NUMBER(38)` by using `:integer`.
```ruby
$ ARCONN=oracle bin/test test/cases/base_test.rb -n test_primary_key_and_references_columns_should_be_identical_type
Using oracle
Run options: -n test_primary_key_and_references_columns_should_be_identical_type --seed 56227
F
Failure:
BasicsTest#test_primary_key_and_references_columns_should_be_identical_type …
```

`references` column type should be :integer, not :bigint

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/oracle_enhanced/type/decimal_spec.rb

This patch to the `OracleEnhancedAdapte`r is necessary because of the way that the gem generates the SQL to create tables with decimal columns. Without the patch, if you were to create a migration that defined a table with a `decimal` column without specifiying a precision and scale such as:
class AddExampleTable < ActiveRecord::Migration[5.2]
def change
create_table :example do |t|
t.string :name
t.decimal :value
end
end
end
The `OracleEnhancedAdapter` would generate the following SQL:
CREATE TABLE example (
id NUMBER(5) PRIMARY KEY,
name VARCHAR2(15) NOT NULL,
value DECIMAL)
This is problematic because Oracle then translates the `DECIMAL` datatype to `NUMBER(18,0)` effectively making this an `INTEGER`.
Older versions of this gem used to correctly map `t.decimal` to the Oracle type …

fix mapping of decimal type to map to `NUMBER` instead of `DECIMAL`

---

Gemfile

Oracle enhanced adapter CI runs RuboCop. It would be nice to install RuboCop to the development environment.

Add RuboCop to Gemfile

---

README.md

Remove `cursor_sharing` information from README [skip ci]

---

spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

[MigrationTest#test_create_table_with_custom_sequence_name ](https://github.com/rails/rails/blob/50e01ec01a7658ba4542bb5f9b68223e98ce6180/activerecord/test/cases/migration_test.rb#L570-L602) is only executed for `OracleAdapter`, it would be nice to run this test at Oracle enhanced adapter.
As Oracle enhanced adapter with Oracle Database 12c supports longer identifier,
this pull request does not test 29 byte length table name and 33-byte length sequence name.
Will open a pull request at Rails to remove `MigrationTest#test_create_table_with_custom_sequence_name`

Add spec for custom sequence name

---

.travis.yml

* Ruby 2.6.2 Released
https://www.ruby-lang.org/en/news/2019/03/13/ruby-2-6-2-released/
* Ruby 2.5.4 Released
https://www.ruby-lang.org/en/news/2019/03/13/ruby-2-5-4-released/

Bump Ruby versions to 2.6.2 and 2.5.4

---

.travis.yml

* Ruby 2.5.5 Released
https://www.ruby-lang.org/en/news/2019/03/15/ruby-2-5-5-released/

CI against Ruby 2.5.5

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

This pull request supports optimizer hints feature implemented to Rails by https://github.com/rails/rails/pull/35615
Here are actual explain output with or without hints.
Note: `>` means IRB prompt.
* With FULL hint
```ruby
> post = TestPost.optimizer_hints("FULL (\"TEST_POSTS\")")
> post = post.where(id: 1)
> post.explain
=> EXPLAIN for: SELECT /*+ FULL ("TEST_POSTS") */ "TEST_POSTS".* FROM "TEST_POSTS" WHERE "TEST_POSTS"."ID" = :a1 [["id", 1]]
Plan hash value: 1913008706
--------------------------------------------------------------------------------
| Id  | Operation         | Name       | Rows  | Bytes | Cost (%CPU)| Time     |
--------------------------------------------------------------------------------
|   0 | SELECT STATEMENT  |            |     1 |    13 |     2   (0)| 00:00:01 …
```

Supports `supports_optimizer_hints?`

---

Gemfile

This pull request reverts commit 1a9c2754542ad2817c923113aa7a166de5925a2e by #1804

Revert "Use i18n 1.2 for JRuby now"

---

History.md

This pull request prepares Oracle enhanced adapter v6.0.0.beta1.

Prepare release v6.0.0.beta1 [skip ci]

---

.codeclimate.yml
Gemfile

Looks like `rubocop-0-66` channel is available at Code Climate.

Use RuboCop 0.66

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Follow up of https://github.com/rails/rails/pull/35795.
This PR fixes the following error.
```console
% cd path/to/oracle-enhanced
==> Running specs with MRI version 2.6.1
==> Effective ActiveRecord version 6.0.0.beta3
rake aborted!
NoMethodError: private method `check_version' called for
#<ActiveRecord::ConnectionAdapters::OracleEnhancedAdapter:0x0000000003bce0c8>
/home/vagrant/.rvm/gems/ruby-2.6.1/bundler/gems/rails-c9981ae6e022/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:813:in
`block in new_connection'
```
And this PR confirmed the following AR test.
```console
% cd path/to/rails/activerecord
% ARCONN=oracle be ruby -w -Itest test/cases/connection_adapters/schema_cache_test.rb
Using oracle …
```

Cache database version in schema cache

---

lib/active_record/connection_adapters/oracle_enhanced/column.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb

Follow up https://github.com/rails/rails/pull/35890.
This PR fixes the following error.
```consle
% cd path/to/oracle-enhanced
(snip)
Failures:
1) OracleEnhancedAdapter schema dump virtual columns should dump
correctly
Failure/Error: expect(output).to match(/t\.virtual
"full_name",(\s*)type: :string,(\s*)limit: 512,(\s*)as:
"\\"FIRST_NAME\\"\|\|', '\|\|\\"LAST_NAME\\""/)
expected "# This file is auto-generated from the current state of
the database. Instead\n# of editing this fil...e_name' for
#<ActiveRecord::ConnectionAdapters::OracleEnhanced::Column:0x0000000003a21bd0>\n\nend\n"
to match /t\.virtual "full_name",(\s*)type: :string,(\s*)limit:
512,(\s*)as: "\\"FIRST_NAME\\"\|\|', '\|\|\\"LAST_NAME\\""/
Diff:
@@ -1,2 +1,19 @@
-/t\.virtual "full_name",(\s*)type: …
```

Except `table_name` from column objects

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb

Follow up https://github.com/rails/rails/commit/f21bc468c35c295351309aada83ccbe44738e653.
This PR fixes the following error.
```console
(snip)
265) OracleEnhancedAdapter timestamp with timezone support / TIMESTAMP
WITH TIME ZONE values from ActiveRecord model should return Time value
from TIMESTAMP columns
Failure/Error: super
ArgumentError:
wrong number of arguments (given 4, expected 3)
#
/home/vagrant/.rvm/gems/ruby-2.6.2/bundler/gems/rails-7cb3e8b8efb1/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:490:in
`sql_for_insert'
#
./lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb:84:in
`sql_for_insert'
#
./lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb:94:in
`exec_insert'
```

Remove unused `sequence_name` in `sql_for_insert`

---

.travis.yml

This reverts commit d06a35ab4d9ab85d18b4a7a0e94be0fd2fde92cc.
Related to #1833 #1834

Revert "Add allow_railures for jruby-head until #1833 resolved"

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

Follow up https://github.com/rails/rails/pull/35970.
This PR fixes the following `TypeError: can't quote Hash`.
```consle
% cd path/to/rails/activerecord
% ARCONN=oracle be ruby -w -Itest test/cases/invertible_migration_test.rb -n test_migrate_revert_change_table_comment
Using oracle
Run options: -n test_migrate_revert_change_table_comment --seed 42508
E
Error:
ActiveRecord::InvertibleMigrationTest#test_migrate_revert_change_table_comment:
TypeError: can't quote Hash
/home/vagrant/src/rails/activerecord/lib/active_record/connection_adapters/abstract/quoting.rb:178:in
`_quote'
/home/vagrant/src/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/quoting.rb:93:in
`_quote'
/home/vagrant/src/rails/activerecord/lib/active_record/connection_adapters/abstract/quoting.rb:18:in …
```

Make `change_column_comment` and `change_table_comment` invertible

---

.codeclimate.yml
.rubocop.yml
Gemfile

* Bump RuboCop version to 0.67.x
https://rubygems.org/gems/rubocop/versions/0.67.0
* Use rubocop-0-67 channel
https://github.com/codeclimate/codeclimate/releases/tag/v0.85.2
* Bundle `rubocop-performance` gem
https://github.com/rubocop-hq/rubocop/blob/master/manual/migrate_performance_cops.md

Bump RuboCop version to 0.67

---

.travis.yml

* Ruby 2.6.3 Released
https://www.ruby-lang.org/en/news/2019/04/17/ruby-2-6-3-released/

CI against Ruby 2.6.3

---

History.md

https://weblog.rubyonrails.org/2019/4/24/Rails-6-0-rc1-released/

Prepare release v6.0.0.rc1 [skip ci]

---

lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb

Related with #1489.
In Active Record Oracle enhanced adapter 5.2, an Oracle error occurs when TCP keepalive time exceeds 600 seconds.
The following ORA-03113 error occurred every 10 minutes when I tried to upgrade from Rails 5.1.6.1 (activerecord-oracle_enhanced-adapter 1.8.2) to Rails 5.2.2 (activerecord-oracle_enhanced-adapter 5.2.5).
```console
stmt.c:243:in oci8lib_240.so: OCIError: ORA-03113: 通信チャネルでend-of-fileが検出されました (ActiveRecord::StatementInvalid)プロセスID: 24578
```
I think that TCP Keepalive parameters depend on an application purpose.
Therefore this PR allows users to change TCP keepalive parameters.
The default behavior has not changed from Active Record Oracle enhanced adapter 5.2 so that breaking changes don't occur.
TCP keepalive parameter names conform to ruby-oci8. …

Add TCP keepalive and TCP keepalive time configurations

---

lib/active_record/connection_adapters/oracle_enhanced/database_tasks.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced/database_tasks_spec.rb

I've got this idea from @ebeigarts in [this comment](https://github.com/rsim/oracle-enhanced/issues/103#issuecomment-2126138)
To change the permissions add the following line to the initializer of
the application:
```ruby
ActiveRecord::ConnectionAdapters::OracleEnhancedAdapter.permissions =
["create session", "create table", "create view",  "create sequence", "create trigger", "ctxapp"]
```
This is useful for when running `rails db:create` from a CI to build a
DB for testing. As it has the credentials and the connection ready, it
would be easier if the required permissions are granted in on go.
For example, when using `add_context_index`, permissions to
`create trigger`, `create procedure`, and `ctxapp` are required. But
these permissions are not included in this db create task.

Add support to change the permissions granted when creating DB

---

RUNNING_TESTS.md

The old branch was removed. There are two options now Oracle 19c or 18c.
I've updated the links to point to the latest version.

Fix links to rails-dev-box running on docker

---

.codeclimate.yml
.rubocop.yml
Gemfile

This pull request bump sRuboCop version to 0.71
https://github.com/rubocop-hq/rubocop/releases/tag/v0.71.0
* Install `rubocop-rails` gem because Rails cops will be removed from RuboCop 0.72
* Rename `Layout/FirstParameterIndentation` to `Layout/IndentFirstArgument` to support RuboCop 0.68.0
```ruby
Error: The `Layout/FirstParameterIndentation` cop has been renamed to `Layout/IndentFirstArgument`.
(obsolete configuration found in .rubocop.yml, please update it)
$
```
* Use `rubocop-0-71` channel at Code Climate
Refer https://github.com/codeclimate/codeclimate/releases/tag/v0.85.3

Bump RuboCop version to 0.71

---

.rubocop.yml
lib/active_record/connection_adapters/oracle_enhanced/connection.rb
lib/active_record/connection_adapters/oracle_enhanced/context_index.rb
lib/active_record/connection_adapters/oracle_enhanced/dbms_output.rb
lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/lob.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/procedures.rb
lib/active_record/connection_adapters/oracle_enhanced/quoting.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_creation.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced/structure_dump.rb
lib/active_record/connection_adapters/oracle_enhanced/type_metadata.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
lib/active_record/type/oracle_enhanced/boolean.rb
lib/active_record/type/oracle_enhanced/integer.rb
spec/active_record/connection_adapters/oracle_enhanced/procedures_spec.rb

Follow up https://github.com/rails/rails/pull/36472.
This PR enables `Layout/EmptyLinesAroundAccessModifier` cop with `EnforcedStyle: only_before`.

Enable `Layout/EmptyLinesAroundAccessModifier` cop

---

lib/active_record/connection_adapters/oracle_enhanced/type_metadata.rb

This pull request needs merged once #1896 merged.
Refer rails/rails#35891
This pulll request addresses 28 failures. Here is the one of them:
You can see entire failures at https://travis-ci.org/rsim/oracle-enhanced/jobs/547963138
```ruby
$ bundle exec rspec ./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb:62
==> Running specs with MRI version 2.6.3
==> Effective ActiveRecord version 6.1.0.alpha
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb"=>[62]}}
F
Failures:
1) OracleEnhancedAdapter cache table columns without column caching should identify virtual columns as such
Failure/Error: delegate :virtual, to: :sql_type_metadata, allow_nil: true
NoMethodError: …
```

Deduplicate various Active Record schema cache structures

---

lib/active_record/connection_adapters/oracle_enhanced/quoting.rb

Refer rails/rails#36637
This pull request addresses this kind of failures:
```ruby
$ bundle exec rspec ./spec/active_record/connection_adapters/oracle_enhanced/context_index_spec.rb:65
... snip ...
/home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/quoting.rb:73: warning: instance variable @quoted_table_names not initialized
FFFFFFFFFF/home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/quoting.rb:73: warning: instance variable @quoted_table_names not initialized
An error occurred in an `after(:context)` hook.
Failure/Error: @quoted_table_names[name] ||= [name.split(".").map { |n| quote_column_name(n) }].join(".")
NoMethodError:
undefined method `[]' for nil:NilClass
```

Share the column and table name quote cache between connections

---

Gemfile

This pull request addresses the following error. The latest version of simplecov drops support Ruby 2.3 or lower https://github.com/colszowka/simplecov/pull/729/files .
```
simplecov-0.17.0 requires ruby version >= 2.4.0
```
https://travis-ci.org/rsim/oracle-enhanced/jobs/558216175

Lock simplecov version for Ruby 2.2 and 2.3

---

History.md

Rails 6.0.0.rc2 has been released
https://rubygems.org/gems/rails/versions/6.0.0.rc2
This pull request has another commit which removes trailing spaces.

Prepare release for 6.0.0.rc2 [skip ci]

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

Follow up https://github.com/rails/rails/pull/36471.
Oracle enhanced adapter has no implementation because Oracle Database cannot detect `NoDatabaseError`.
Please refer to the following discussion for details.
https://github.com/rsim/oracle-enhanced/pull/1900
The following is an implementation example I gave up.
```diff
diff --git
a/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
b/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
index af99718..77a5b90 100644
--- a/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
+++ b/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
@@ -249,6 +249,12 @@ module ActiveRecord
ADAPTER_NAME
end
+      def self.database_exists?(config)
+ …
```

Add database_exists? method to connection adapters

---

History.md

Oracle enhanced adapter 6.0.0.rc3 is required to include #1903 .

Prepare release for 6.0.0.rc3 [skip ci]

---

.travis.yml

https://www.jruby.org/2019/08/12/jruby-9-2-8-0.html

CI against JRuby 9.2.8.0

---

.codeclimate.yml
.rubocop.yml
Gemfile

This pull request bumps RuboCop to 0.74.0 and uses the same `rubocop-performance` gem CodeClimate provided
* Rename `EnforcedStyle` of `Layout/IndentationConsistency` cop
from `rails` to `indented_internal_methods`
* Disable `Layout/SpaceAroundOperators` cop
Refer rails/rails#36943
*   Use rubocop-performance gem 1.3.x
Refer: https://github.com/codeclimate/codeclimate-rubocop/blob/channel/rubocop-0-74/Gemfile.lock#L51-L55

Bump RuboCop to 0.74.0

---

.travis.yml

* Ruby 2.6.4 Released
https://www.ruby-lang.org/en/news/2019/08/28/ruby-2-6-4-released/
* Ruby 2.5.6 Released
https://www.ruby-lang.org/en/news/2019/08/28/ruby-2-5-6-released/

CI against Ruby 2.6.4 and Ruby 2.5.6

---

Gemfile

This pull request bumps Rake version to 13.0.0.pre.1
https://github.com/ruby/rake/blob/master/History.rdoc#1300pre1

Use Rake 13.0.0.pre.1

---

.github/workflows/ruby.yml

This pull request implements GitHub Actions to run RuboCop.
* Use Ruby 2.6
* Download and Install Oracle Instant Client
* Update environment variables for Oracle Instant Client
* Execute `bundle exec rubocop`
* Not execute `bundle exec rspec` in this commit
* Use `--parallel` option for RuboCop

Enable GitHub Actions and run RuboCop

---

.codeclimate.yml
Gemfile
lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb

This pull request unlocks RuboCop gem versions including these commits:
* Disable `rubocop` plugin from .codeclimate.yml
* Use the latest`rubocop`, `rubocop-performance` and `rubocop-rails` gem because we can run the latest versions of them with GitHub Actions
* Perform RuboCop autocorrect using `rubocop-performance` 1.4.1
This pull request is making use of GitHub Actions enabled at #1925

Unlock RuboCop gem versions

---

.dependabot/config.yml

This pull request enables Dependabot to see if it works and helps Oracle enhanced adapter development.
Refer https://dependabot.com/docs/config-file/ to create with only required options.

Enabled Dependabot by creating .dependabot/config.yml

---

.travis.yml

This pull request bumps the OS version at Travis CI from 16.04 to 18.04.
https://docs.travis-ci.com/user/reference/bionic/

Use Ubuntu 18.04 (Bionic Beaver) at Travis CI

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Follow up of https://github.com/rails/rails/commit/d775176d3a20a5e02b4fbcd0ae8379b53238f787.
As far as I can see, Oracle supports Common Table Expression.
And this patch passed the following AR test.
```console
% ARCONN=oracle bundle exec ruby -w -Itest test/cases/adapter_test.rb -n
test_doesnt_error_when_a_read_query_with_a_cte_is_called_while_preventing_writes
Using oracle
Run options: -n
test_doesnt_error_when_a_read_query_with_a_cte_is_called_while_preventing_writes
--seed 45728
.
Finished in 0.014451s, 69.2015 runs/s, 69.2015 assertions/s.
1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
```

Add `supports_common_table_expressions?` for CTE testing

---

.rubocop.yml

Follow up of https://github.com/rails/rails/pull/37582.

Bump RuboCop to 0.76.0

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

Follow up of https://github.com/rails/rails/commit/d700456cb72bd38dcf6f540a3b7f6593879b456f, https://github.com/rails/rails/commit/e02b3d1b0ede87396122f90d773b9030ce9d469e, and https://github.com/rails/rails/commit/70afbf245f1038b91a664dcee98cb8dea61d9b91

create_table_definition and add_column take keyword arguments

---

.travis.yml

* Ruby 2.5.7 Released
https://www.ruby-lang.org/en/news/2019/10/01/ruby-2-5-7-released/
* Ruby 2.6.5 Released
https://www.ruby-lang.org/en/news/2019/10/01/ruby-2-6-5-released/

CI against Ruby 2.5.7 and Ruby 2.6.5

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

This pull request addresses `uninitialized constant ActiveRecord::ConnectionAdapters::AbstractAdapter::Quoting (NameError)`
Fix #1935
```ruby
$ ruby guides/bug_report_templates/active_record_gem.rb
Fetching https://github.com/rails/rails.git
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/............
Fetching gem metadata from https://rubygems.org/............
Resolving dependencies...
Using rake 13.0.0
Using concurrent-ruby 1.1.5
Using i18n 1.7.0
Using minitest 5.13.0
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using zeitwerk 2.2.1
Using activesupport 6.1.0.alpha from https://github.com/rails/rails.git (at master@a98b950)
Using builder 3.2.3
Using erubi 1.9.0
Using mini_portile2 2.4.0
Using nokogiri 1.10.5
Using rails-dom-testing …
```

Address `uninitialized constant ActiveRecord::ConnectionAdapters::AbstractAdapter::Quoting (NameError)

---

.rubocop.yml

This pull request updates .rubocop.yml to use RuboCop 0.77
https://github.com/rubocop-hq/rubocop/releases/tag/v0.77.0
* Update cop names as follows:
```ruby
Error: The `Layout/IndentFirstArgument` cop has been renamed to `Layout/FirstArgumentIndentation`.
(obsolete configuration found in .rubocop.yml, please update it)
The `Layout/TrailingBlankLines` cop has been renamed to `Layout/TrailingEmptyLines`.
(obsolete configuration found in .rubocop.yml, please update it)
The `Lint/StringConversionInInterpolation` cop has been renamed to `Lint/RedundantStringCoercion`.
(obsolete configuration found in .rubocop.yml, please update it)
$
```

Use RuboCop 0.77

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb

Fixes #1932.
This PR fixes an error when writing lobs.
This error seems to be caused by #1546. Rails 5.2 and 6.0 has been targeted.
#1932 discusses backporting to Rails 5.2 and Rails 6.0.

Fix an error when writing lobs

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb

This pull request backports #1962 to release60 branch as follows.
I used to cherry-pick the original commit, this time cherry-pick the merge commit with `-m 1` option now.
```
$ git cherry-pick -m 1 becf833
```

Backport #1962 to release60 branch

---

Gemfile
spec/spec_helper.rb

This pull request uninstalls SimpleCov.
This is triggered by the following error. Although I usually investigate these kind of errors,
We are not making use of SimpleCov to get test coverage then decided to uninstall SimpleCov
```
$ bundle
Fetching https://github.com/rails/rails.git
Fetching https://github.com/rsim/ruby-plsql.git
Fetching https://github.com/kubo/ruby-oci8.git
Fetching https://github.com/colszowka/simplecov.git
The dependency pry (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for java. To add those platforms to the bundle, run `bundle lock --add-platform java`.
The dependency pry-nav (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but …
```

Uninstall SimpleCov

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb
spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb

I added the `with_retry` method to the `OCIConnection` class, similar to `JDBCConnection#with_retry`.
All `exec_*` methods in the `DatabaseStatements` module call the `with_retry` method in order to enable the auto-retry functionality for ActiveRecord models.
Resolves #1956

fix: Auto retry only works for connection.exec()

---

lib/active_record/connection_adapters/oracle_enhanced/schema_creation.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_definitions.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

This PR fixes the following keyword arguments errors for Ruby 2.8.0-dev.
https://travis-ci.org/rsim/oracle-enhanced/jobs/633096860

Fix keyword arguments errors for Ruby 2.8.0-dev

---

.travis.yml

As of Jan 2020, ruby-head is Ruby 2.8.0 which does implement the new keyword arguments.
As far as I know, there is no plan to support Rails 5.2 then let's remove Ci against ruby-head.

No more ci against ruby-head for release52 aka Rails 5.2

---

.travis.yml

* Ruby 2.6.5 Released
https://www.ruby-lang.org/en/news/2019/10/01/ruby-2-6-5-released/
* Ruby 2.5.7 Released
https://www.ruby-lang.org/en/news/2019/10/01/ruby-2-5-7-released/
* JRuby 9.2.9.0 Released
https://www.jruby.org/2019/10/30/jruby-9-2-9-0.html

CI against latest rubies

---

spec/active_record/connection_adapters/oracle_enhanced/schema_dumper_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/schema_statements_spec.rb

This PR fixes the following build errors when using Ruby 2.8.0-dev.
```console
Failures:
1) OracleEnhancedAdapter schema dump tables should not include ignored
table names in schema dump
Failure/Error:
def create_table(table_name, id: :primary_key, primary_key: nil, force: nil, **options)
create_sequence = id != false
td = create_table_definition(
table_name, **options.extract!(:temporary, :options, :as, :comment, :tablespace, :organization)
)
if id && !td.as
pk = primary_key || Base.get_primary_key(table_name.to_s.singularize)
if pk.is_a?(Array)
ArgumentError:
wrong number of arguments (given 2, expected 1)
```
https://travis-ci.org/rsim/oracle-enhanced/jobs/640716588#L508-L531

Fix a build errors when using Ruby 2.8.0-dev

---

lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb
spec/active_record/connection_adapters/oracle_enhanced/schema_dumper_spec.rb

Includes `sync` option in `schema.rb` when dumping a context index.
Fixes #1987 
I didn't want to duplicate the test case I wrote in #1986, so this also includes that. I'm happy to split it out if you're rather see it separately.

Include sync option when dumping a context index

---

lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb
spec/active_record/connection_adapters/oracle_enhanced/schema_dumper_spec.rb

When dumping a table schema that contains both a regular index and a context index,
it would dump an error to `schema.rb`.
```
Could not dump table "posts" because of following ArgumentError
comparison of NilClass with String failed
```
The problem is when you had both types of indexes, the array would include a `nil`
which would blow up the sort.
Fixes #1985
I would love to see this backported to the 5.2 branch since that's where the app I ran into this issue is at.

Fix schema dump when table contains both a regular and context index

---

.travis.yml

* JRuby 9.2.10.0 Released
https://www.jruby.org/2020/02/18/jruby-9-2-10-0.html

CI against JRuby 9.2.10.0

---

.travis.yml

* JRuby 9.2.11.0 Released
https://www.jruby.org/2020/03/02/jruby-9-2-11-0.html

CI against JRuby 9.2.11.0

---

README.md

Follow up #1637.
This looks like it describes an upgrade from Rails 5.1 or older version.

Update UPGRADE section for Rails 5.2 [skip ci]

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb

I changed the API to accepts keyword arguments in rails/rails@f735a2167c

Use the new API for build_results

---

.travis.yml

* JRuby 9.2.11.1 Released
https://www.jruby.org/2020/03/25/jruby-9-2-11-1.html

CI against JRuby 9.2.11.1

---

.travis.yml

* Ruby 2.7.1 Released
https://www.ruby-lang.org/en/news/2020/03/31/ruby-2-7-1-released/
* Ruby 2.6.6 Released
https://www.ruby-lang.org/en/news/2020/03/31/ruby-2-6-6-released/
* Ruby 2.5.8 Released
https://www.ruby-lang.org/en/news/2020/03/31/ruby-2-5-8-released/

CI againt Ruby 2.7.1, 2.6.6 and 2.5.8

---

.rubocop.yml

Follow up of https://github.com/rails/rails/pull/38980.

Bump RuboCop to 0.82.0

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

This PR removes the wrong diff on #2006.
This diff is an upstream change made in https://github.com/rails/rails/commit/36ea108.
This PR reverts for a different commit reason than #2006.

Revert part of #2006

---

lib/arel/visitors/oracle.rb
lib/arel/visitors/oracle12.rb

`connection.in_clause_length` and related code will be removed from
Rails code base, so should be owned in the repo itself.
Ref https://github.com/rails/rails/pull/39057.

Import `visit_Arel_Nodes_{In,NotIn}` from Rails code base

---

lib/active_record/connection_adapters/oracle_enhanced/database_limits.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

`allowed_index_name_length` is deprecated and will be removed in the
future version of Rails.
See https://github.com/rails/rails/pull/39083.

Don't refer `allowed_index_name_length` directly

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Follow up to https://github.com/rails/rails/commit/bc99e40.

Should not rely on the global `Arel::Table.engine` in the framework

---

spec/spec_helper.rb

This PR suppresses the following `warning: already initialized constant`.
```console
% path/to/oracle-enhanced
(snip)
==> Running specs with MRI version 2.7.1
==> Effective ActiveRecord version 6.1.0.alpha
/home/vagrant/src/oracle-enhanced/spec/spec_helper.rb:113: warning:
already initialized constant
ActiveRecord::LogSubscriber::IGNORE_PAYLOAD_NAMES
/home/vagrant/.rvm/gems/ruby-2.7.1/bundler/gems/rails-348e142b26b4/activerecord/lib/active_record/log_subscriber.rb:5:
warning: previous definition of IGNORE_PAYLOAD_NAMES was here
```

Suppress `warning: already initialized constant`

---

spec/active_record/oracle_enhanced/type/national_character_string_spec.rb

Follow up to https://github.com/rails/rails/pull/39106.

Deprecate passing a column to `type_cast`

---

lib/arel/visitors/oracle.rb
lib/arel/visitors/oracle12.rb
spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

* Oracle limits lists to a maximum of 1,000 items. 
* rails/rails@72fd0bae5948c1169411941aeea6fef4c58f34a9 implements a new type of `in` operation which can be performed under certain circumstances.
* This caused the test "OracleEnhancedAdapter eager loading should load included association with more than 1000 records" to fail with ORA-01795.
* The solution was to implement `visit_Arel_Nodes_HomogeneousIn`.
* Fixed a typo while I was at it.

Limit number of expressions in a list during a "homogenous in" operation

---

lib/active_record/connection_adapters/oracle_enhanced/quoting.rb

Follow rails/rails#36448, and follow rails/rails#36420, rails/rails@1340498, and rails/rails@6607ecb required for that change.
This PR fixes the following rails/activerecord's errors.
```console
% cd rails/activerecord
% ARCONN=oracle bundle exec ruby -w -Itest test/cases/unsafe_raw_sql_test.rb
Using oracle
Run options: -n /test_order/ --seed 62550
..................DEPRECATION WARNING: Dangerous query method (method
whose arguments are used as raw SQL) called with non-attribute
argument(s): "\"POSTS\".\"TITLE\"". Non-attribute arguments will be
disallowed in Rails 6.1. This method should not be called with
user-provided values, such as request parameters or model
attributes. Known-safe values can be passed by wrapping them in
Arel.sql(). (called from block (3 levels) in run at …
```

Allow column name with function (e.g. `length(title)`) as safe SQL string

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
lib/active_record/connection_adapters/oracle_enhanced/lob.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb
spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb

RuboCop Performance 1.6.0 has been released.
https://github.com/rubocop-hq/rubocop-performance/releases/tag/v1.6.0
This PR suppresss new RuboCop's offenses.
```consle
% bundle exec rubocop
(snip)
Offenses:
lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb:45:39:
C: Performance/StartWith: Use String#start_with? instead of a regex
match anchored to the beginning of the string.
if (name == "EXPLAIN") && sql =~ /^EXPLAIN/
^^^^^^^^^^^^^^^^^
lib/active_record/connection_adapters/oracle_enhanced/lob.rb:21:15: C:
Performance/EndWith: Use String#end_with? instead of a regex match
anchored to the end of the string.
column.sql_type_metadata.sql_type =~ /LOB$/
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb: …
```

Suppress RuboCop's offenses

---

.rubocop.yml

Follow up to rails/rails#39409.
This PR enables `Performance/DeletePrefix` and `Performance/DeleteSuffix` cops.

Enable `Performance/DeletePrefix` and `Performance/DeleteSuffix` cops

---

lib/active_record/connection_adapters/oracle_enhanced/schema_creation.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_definitions.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
spec/active_record/connection_adapters/oracle_enhanced/schema_dumper_spec.rb

Follow up to rails/rails#39365.
This PR consists of the following two commits.
1. Default engine `ENGINE=InnoDB` is no longer dumped to make schema more agnostic (rails/rails@3c6be5e)
2. Separate primary key column options from table options (rails/rails@859681e)
The latter changes `create_table` format in the dumped schema file.

Follow rails/rails#39365

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

Follow up to https://github.com/rails/rails/commit/b9e5859.
This PR resolves the following error.
```console
bundle exec rspec spec/active_record/connection_adapters/oracle_enhanced/schema_dumper_spec.rb:389
(snip)
An error occurred in an `after(:context)` hook.
Failure/Error: index_name = index_name_for_remove(table_name,
column_name, options)
ArgumentError:
No indexes found on test_names with the options provided.
connection_adapters/abstract/schema_statements.rb:1356:in `index_name_for_remove'
migration.rb:911:in `block in method_missing'
migration.rb:879:in `block in say_with_time'
migration.rb:879:in `say_with_time'
migration.rb:900:in `method_missing'
in <top (required)>'
```
https://travis-ci.org/github/rsim/oracle-enhanced/jobs/691993596#L451

Make index options to kwargs

---

.github/workflows/ruby.yml

This pull request migrates from `actions/setup-ruby` to `ruby/setup-ruby` and bumps Oracle instant client version from 19.3 to 19.6.

Migrate to `ruby/setup-ruby` to use Ruby 2.7

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

This pull request implements ObjectSpace::WeakMap#values for JRuby.
This commit will be reverted when JRuby supports `ObjectSpace::WeakMap#values`.
Refer https://github.com/jruby/jruby/issues/6267#issuecomment-643546057

Implement ObjectSpace::WeakMap#values for JRuby

---

.github/workflows/test.yml
ci/network/admin/tnsnames.ora
ci/setup_accounts.sh

Here are some notable changes:
- Use `ubuntu-20.04` to install `oracle-database-xe-18c-1.0-1.x86_64.rpm`
- CI against Ruby 2.7, 2,6, 2,5 ruby-head (Ruby 2.8.0dev)
and `ruby-debug`, which is `ruby-head` but with assertions enabled (-DRUBY_DEBUG=1).
- Use Oracle Database 18c Express Edition (XE) as Oracle client
to workaround ORA-1805 error.
Refer https://github.com/rsim/oracle-enhanced/issues/2033
- Run Oracle Database 18c Express Edition (XE) as Docker container
https://hub.docker.com/r/quillbuilduser/oracle-18-xe
This pull request does not include CI against Jruby because:
- No JRuby support because it requires to support "Thin-style Service Name Syntax"
```
jdbc:oracle:thin:HR/hr@//localhost:5221/orcl
```
Refer "8.2.4 Thin-style Service Name Syntax" …

Run CI with GitHub Actions

---

.travis.yml

JRuby 9.2.12.0 has been released.
https://www.jruby.org/files/downloads/9.2.12.0/index.html

CI against JRuby 9.2.12.0

---

.github/workflows/test.yml
ci/setup_accounts.sh

To meet the same timezone file version between Oracle client and server.
Fixes #2033

Use Oracle Instant Client 18.5

---

.travis.yml

This pull request removes `allow_failures:` for `jruby-head` because the bundler inline issue can be addressed.
There are possible two workarounds for jruby-head.
- Bump Bundler version to 2.2.0.rc.1 RubyGems version to 3.1.4
- Remove Gemfile.lock before using bundle inline
In this pull request, I prefer the second one.
Refer https://github.com/rubygems/rubygems/issues/3796

Support `jruby-head` again

---

.travis.yml

* JRuby 9.2.13.0 Released
https://www.jruby.org/2020/08/03/jruby-9-2-13-0.html

CI against JRuby 9.2.13.0

---

lib/active_record/connection_adapters/oracle_enhanced/schema_creation.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_definitions.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
spec/active_record/connection_adapters/oracle_enhanced/schema_dumper_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/schema_statements_spec.rb

This PR backports these following commits to release60 branch.
- https://github.com/rsim/oracle-enhanced/commit/13abef9e7ebd81882fb1d5702d51a54f5152abf1
- https://github.com/rsim/oracle-enhanced/commit/a93bf5597367bb388f935519ef8f3d0c4f58a680
- https://github.com/rsim/oracle-enhanced/commit/fcd7278b0412d336d12ec620969973cc40718ebb
It suppresses Ruby 2.7's real kwargs warning for Rails 6.0.
@yahonda I would like to use this patch with Rails 6.0. Can you cut activerecord-oracle_enhanced-adapter 6.0.4?

Suppress Ruby 2.7's real kwargs warning for release60 branch

---

lib/active_record/connection_adapters/oracle_enhanced/connection.rb
lib/active_record/connection_adapters/oracle_enhanced/quoting.rb
spec/spec_helper.rb

Hello, please allow the `truffleruby` `RUBY_ENGINE`. I am also currently testing `ruby-plsql` and `ruby-oci8` gems and most tests pass with `truffleruby-head` version and the few failures I have seen will be worked on. Thank you.

Allow TruffleRuby RUBY_ENGINE

---

lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb
spec/active_record/connection_adapters/oracle_enhanced/schema_dumper_spec.rb

This pull request restores Schema Dumper behavior changed by #2019
because rails/rails#39365 does not intend to dump the default primary key configuration.
Related to rails/rails#39365
Follow up #2019

Restore Schema Dumper behavior changed by #2019

---

.github/workflows/test.yml
lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb
spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb
spec/spec_helper.rb

This pull request implements JDBC Thin-style service name syntax.
Oracle enhanced has supported Oracle SID syntax, Since Oracle service name is mandatory for Oracle pluggable database,
it's time to support service name connection syntax.
- SID syntax
```java
jdbc:oracle:thin:@myhost:1521:orcl
```
Refer
https://docs.oracle.com/cd/E11882_01/appdev.112/e13995/oracle/jdbc/OracleDriver.html
- Service name syntax
```java
jdbc:oracle:thin:@//127.0.0.1:1521/ORCLPDB1
```
Refer "8.2.4 Thin-style Service Name Syntax"
https://docs.oracle.com/en/database/oracle/oracle-database/18/jjdbc/data-sources-and-URLs.html#GUID-EF07727C-50AB-4DCE-8EDC-57F0927FF61A
Also, this pull request enables CI against JRuby versions.

Support JDBC service name syntax

---

.travis.yml

Ruby 2.7.2 has been released.
https://www.ruby-lang.org/en/news/2020/10/02/ruby-2-7-2-released/

CI against Ruby 2.7.2

---

Gemfile

This pull request uses Rails 6-1-branch for Oracle enhanced adapter release61.
Refer #1895 for Rails 6.0.

Use Rails 6-1-branch for Oracle enhanced adapter release61

---

Gemfile

Rake 13.0.0 has been released and no need to use pre version.
Kind of reverting #1924.

Use released version of rake

---

lib/active_record/connection_adapters/oracle_enhanced/connection.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced/structure_dump.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Add /*+ OPTIMIZER_FEATURES_ENABLE('11.2.0.2') */ hint to address slow SCHEMA queries
Migrating Oracle Database version to higher like 12c, I have experienced
some slowness mainly due to SCHEMA queries. This commit should address
this slowness.
I have tested multiple values of optimizer_features_enable from 19.1.0 to 11.2.0.2,
then there is a significant elapsed time of `bundle exec rspec` between
11.2.0.3 to 11.2.0.2.
- optimizer_features_enable = 11.2.0.3
Finished in 848 minutes 28 seconds (files took 0.61873 seconds to load)
- optimizer_features_enable = 11.2.0.2
Finished in 2 minutes 30 seconds (files took 0.61398 seconds to load)
Oracle Database 19c (19.3) on Docker
Intel NUC Kit NUC6i5SYH with 4 CPU and 32 GB memory
This initialization parameter value can be changed to instance level …

    Add /*+ OPTIMIZER_FEATURES_ENABLE('11.2.0.2') */ hint to address slow SCHEMA queries

---

lib/arel/visitors/oracle.rb
lib/arel/visitors/oracle12.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

Fixes #2023.
This PR fixes `ActiveRecord::StatementInvalid: OCIError: ORA-00907: missing right parenthesis` error when using assoc has `dependent: :delete_all` and `order`.
```ruby
has_many :assoc, -> { order(:foo) }, dependent: :delete_all
```
Oracle does not accept `ORDER BY` in `DELETE` and `UPDATE`'s subquery. This PR adds the following reproduction test and passes it.
```console
vagrant@rails-dev-box:~/src/oracle-enhanced$ bundle exec rspec
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb:187
==> Running specs with ruby version 2.7.2
==> Effective ActiveRecord version 6.1.0.rc1
Run options: include
{:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb"=>[187]}}
F
Failures:
1) …
```

`build_subselect` does not have ordering

---

.rubocop.yml
lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/quoting.rb
spec/active_record/connection_adapters/oracle_enhanced/context_index_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/schema_dumper_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/structure_dump_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

Follow up https://github.com/rails/rails/commit/a908d06c8539ac967aae7897e1b72279016f7dcc
```ruby
Inspecting 70 files
.............C.....C........................C....C.CC.................
Offenses:
lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb:116:41: C: [Corrected] Style/RedundantRegexpEscape: Redundant escape inside regexp literal
unless database.match?(/^(\:|\/)/)
^^
lib/active_record/connection_adapters/oracle_enhanced/quoting.rb:15:32: C: [Corrected] Style/RedundantRegexpEscape: Redundant escape inside regexp literal
if /\A[a-z][a-z_0-9\$#]*\Z/.match?(name)
^^
lib/active_record/connection_adapters/oracle_enhanced/quoting.rb:30:31: C: [Corrected] Style/RedundantRegexpEscape: Redundant escape inside regexp literal
when …
```

Enable  `Style/RedundantRegexpEscape` cop

---

lib/arel/visitors/oracle.rb
lib/arel/visitors/oracle12.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

This pull request removes `visit_Arel_Nodes_NotIn` and `visit_Arel_Nodes_In` visitors to use `visit_Arel_Nodes_HomogeneousIn`
`visit_Arel_Nodes_HomogeneousIn` has been implemented in Rails 6.1 via https://github.com/rails/rails/commit/72fd0bae594 and implemented for Oracle enhanced adapter via #2013 .
Refer #2008
Fix #2072

Remove `visit_Arel_Nodes_NotIn` and `visit_Arel_Nodes_In` visitors

---

lib/arel/visitors/oracle.rb
lib/arel/visitors/oracle12.rb

* Steps to reproduce
```ruby
$ ARCONN=oracle bin/test test/cases/bind_parameter_test.rb -n test_too_many_binds
Using oracle
Run options: -n test_too_many_binds --seed 56030
F
Failure:
ActiveRecord::BindParameterTest#test_too_many_binds [/home/yahonda/src/github.com/rails/rails/activerecord/test/cases/bind_parameter_test.rb:116]:
Expected: 0
Actual: 5
bin/test test/cases/bind_parameter_test.rb:109
Finished in 6.902430s, 0.1449 runs/s, 0.2898 assertions/s.
1 runs, 2 assertions, 1 failures, 0 errors, 0 skips
$
```
* Rails Active Record unit test is modified temporary not to use huge memory which
causes `ORA-27102: out of memory`
```diff
$ git diff
diff --git a/activerecord/test/cases/bind_parameter_test.rb b/activerecord/test/cases/bind_parameter_test.rb
index …
```

`NOT IN` clause needs separated by `AND`

---

History.md

This pull request's target branch is `release60` directly because Oracle enhanced adapter 6.1.0 has been released already.

Prepare release v6.0.5 [skip ci]

---

.github/workflows/ruby.yml
.github/workflows/test.yml

* Ruby 3.0.0 Released
https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/

CI against Ruby 3.0.0

---

.github/workflows/test.yml

Refer https://github.com/seattlerb/minitest/pull/861
https://github.com/seattlerb/minitest/pull/862

Exclude `ruby-head` and `ruby-debug` until minitest allows Ruby 3.1

---

guides/bug_report_templates/active_record_gem_spec.rb

* Without this commit
```ruby
$ ruby active_record_gem_spec.rb
Fetching https://github.com/rails/rails.git
... snip ...
Using rails 6.2.0.alpha from https://github.com/rails/rails.git (at master@afc79e3)
$
```
* With this commit
```ruby
$ ruby active_record_gem_spec.rb
Fetching https://github.com/rails/rails.git
... snip ...
Using rails 6.2.0.alpha from https://github.com/rails/rails.git (at master@afc79e3)
-- create_table(:posts, {:force=>true})
D, [2021-01-01T17:27:35.727438 #554514] DEBUG -- :    (20.9ms)  DROP TABLE "POSTS"
D, [2021-01-01T17:27:35.733266 #554514] DEBUG -- :    (5.4ms)  DROP SEQUENCE "POSTS_SEQ"
D, [2021-01-01T17:27:35.748060 #554514] DEBUG -- :    (14.4ms)  CREATE TABLE "POSTS" ("ID" NUMBER(38) NOT NULL PRIMARY KEY)
D, [2021-01-01T17:27:35.751081 #554514] DEBUG -- : …
```

Require `rspec/autorun` to run one line spec file

---

guides/bug_report_templates/active_record_gem_spec.rb

Reverts rsim/oracle-enhanced#2098

Revert "Require `rspec/autorun` to run one line spec file"

---

.travis.yml

This pull request bumps Ruby versions to the latest patch release and remove CI against ruby-head at release60 branch.

Bump Ruby versions to the latest patch release and remove CI against ruby-head

---

lib/active_record/connection_adapters/oracle_enhanced/structure_dump.rb
spec/active_record/connection_adapters/oracle_enhanced/structure_dump_spec.rb

FK constraints are mistakenly not being included in SQL structure dumps (`rails db:structure:dump`).
Due to a bug that I believe was introduced quite a while ago (in #1641, fixing #1625), the DDL describing foreign keys is being discarded in favour of the DDL describing views.
I believe this was missed because the test coverage of the FK dumping tests only the standalone method that does this (`#structure_dump_fk_constraints`), rather than the main `#structure_dump` method.
This PR ensures that both the view DDL and the foreign key DDL gets included when a structure dump is performed, and adjusts the specs accordingly.
I could only get a limited Oracle enviroment working, but was able to run the appropriate specs:
```
$ bundle exec rspec …
```

Ensure FKs are properly included in structure dumps

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

This pull request backports #2097 to release60 branch.

Fix write_lobs Invalid byte sequence in UTF-8 (#2097)

---

.rubocop.yml
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

This pull request enables `Layout/SpaceBeforeBrackets` cop, which has not been enabled at rails/rails repository. Actually, Rails code does not have any offenses detected by this cop then I have no plan to open a pull request to Rails repository to enable it.
This cop should work with RuboCop 1.8 which includes https://github.com/rubocop-hq/rubocop/pull/9291
```ruby
Inspecting 71 files
...........................C...........................................
Offenses:
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:495:39: C: [Corrected] Layout/SpaceBeforeBrackets: Remove the space before the opening brackets.
@do_not_prefetch_primary_key [table_name] = do_not_prefetch = !has_primary_key?(table_name, owner, desc_table_name)
^
71 files inspected, 1 …
```

Enable `Layout/SpaceBeforeBrackets` cop

---

.travis.yml

This pull request tidies up Travis CI configuration.

Tidy up Travis CI configuration

---

lib/active_record/connection_adapters/oracle_enhanced/connection.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

Since #2055 added /*+ OPTIMIZER_FEATURES_ENABLE('11.2.0.2') */ hint to most of the SCHEMA queries and there is a performance regression reported for `OracleEnhanced::Connection#describe` method which performs query to all_synonyms.
Fix #2090

Remove /*+ OPTIMIZER_FEATURES_ENABLE('11.2.0.2') */ hint for all_synonyms

---

lib/active_record/connection_adapters/oracle_enhanced/structure_dump.rb

Currently, when dumping column comments, `user_tab_columns` is used. This misses comments which are in the current schema, when the current user is not the owner.
This PR dumps column comments from `all_tab_cols` instead, filtering `owner` to the `current_schema`. This is in line with the approach taken for the rest of the objects extracting during the structure dump.

structure dump: read column comments from all_tab_cols

---

lib/active_record/connection_adapters/oracle_enhanced/connection.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced/structure_dump.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

Bind variables are used for more volatile columns owner and table name.
For our larger OLTP systems it is essential to run them with cursor_sharing=exact.
In this case dictionary access without bind variables leads to significant longer CI pipeline runtime as well as production load.

Usage of bind variables for volatile filter conditions (3)

---

.github/workflows/test.yml

Ruby 3.0 version specification in YAML should be string `'3.0'` instead of float `3.0`. It will be `3` instead of the expected `3.0`.
Before: `test / build (3)` -> After: `test / build (3.0)`

Tweak representation of build matrix

---

.github/workflows/test.yml

This pull request changes to run all jobs even if any one gets failed.
Due to #2118 CI against JRuby has been failing. If any jog gets failed,
other remaining jobs will not run by default.

Configure `continue-on-error: true` to run all CI

---

.rubocop.yml

Follow https://github.com/rails/rails/commit/458f19a0f7c296a8d01c97a6b86821bceb130327
This PR suppresses the following `SuggestExtensions` message.
```console
% bundle exec rubocop
(snip)
70 files inspected, no offenses detected
Tip: Based on detected gems, the following RuboCop extension libraries
might be helpful:
* rubocop-rake (http://github.com/rubocop-hq/rubocop-rake)
* rubocop-rspec (http://github.com/rubocop-hq/rubocop-rspec)
You can opt out of this message by adding the following to your config (see
https://docs.rubocop.org/rubocop/extensions.html#extension-suggestions for more options):
AllCops:
SuggestExtensions: false
```
I think Oracle enhanced adapter will not add its own 3rd party gems because the adapter coding style is based on Rails.

Opt out of `SuggestExtensions` message

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
lib/active_record/connection_adapters/oracle_enhanced/dbms_output.rb

Follow https://github.com/rails/rails/pull/40037.

Allow Adapter#select_all to be performed asynchronously from a background thread pool

---

.travis.yml

- "JRuby 9.2.15.0 Released"
https://www.jruby.org/2021/02/24/jruby-9-2-15-0.html
The current master branch does not support JRuby yet.

CI against JRuby 9.2.15.0 on release61 branch

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
lib/active_record/connection_adapters/oracle_enhanced/quoting.rb
lib/arel/visitors/oracle.rb
lib/arel/visitors/oracle12.rb

Resolves https://github.com/rsim/oracle-enhanced/issues/2152 and follow https://github.com/rails/rails/pull/41577.
The tests that fail below have not yet been resolved.
https://github.com/rails/rails/commit/6ee96a8f42d6b13bffd46342248f447d9f289288.

Avoid extra `BindParam` allocation to generate placeholder in queries

---

lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb

This pull request unfreeze config object to workaround the error
with JNDI connection.
As of right now Oracle enhanced adapter master branch does not
support JRuby and no JNDI specs are available this commit does not have
any tests. Instead this change has been verified by the reporter.
Fix #2139

Address `FrozenError (can't modify frozen Hash):` error

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

The commit 530e4173ee50ca13cd8b69a4c4c5fcb1bb392eb6 introduced the
option to replace the default permissions defined by the adapter
but, mistakenly removed "ulimited tablespace" from the default
list

Add missing default granted permission "ulimited tablespace"

---

activerecord-oracle_enhanced-adapter.gemspec

Fix #2163
- Without this change - ojdbc8.jar file is included in the gem file.
```
$ cp /usr/lib/oracle/19.8/client64/lib/ojdbc8.jar lib/.
$ bundle exec rake build
activerecord-oracle_enhanced-adapter 7.0.0.alpha built to pkg/activerecord-oracle_enhanced-adapter-7.0.0.alpha.gem.
$ ls -lh pkg/activerecord-oracle_enhanced-adapter-7.0.0.alpha.gem
-rw-rw-r-- 1 yahonda yahonda 4.0M Apr  1 12:14 pkg/activerecord-oracle_enhanced-adapter-7.0.0.alpha.gem
cd pkg
$ gem unpack activerecord-oracle_enhanced-adapter-7.0.0.alpha.gem
Unpacked gem: '/home/yahonda/src/github.com/rsim/oracle-enhanced/pkg/activerecord-oracle_enhanced-adapter-7.0.0.alpha'
$ ls -l activerecord-oracle_enhanced-adapter-7.0.0.alpha/lib/
total 4252
drwxrwxr-x 4 yahonda yahonda    4096 Apr  1 12:14 active_record
-rw-rw-r-- 1 yahonda …
```

Prevent from including ojdbc8.jar file to gem file

---

lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb

Oracle provides separate JDBC version for Java 11 and above (ojdbc11.jar).
This change allows application start if only ojdbc11.jar is provided.
It forces usage of ojdbc11.jar instead of ojdbc8.jar if Java 11+ is used and ojdbc11.jar available.

Support use of ojdbc11.jar

---

.travis.yml

Allow-failure CI against jruby-head for release61 branch

---

.travis.yml

https://www.jruby.org/2021/03/29/jruby-9-2-17-0.html

CI against JRuby 9.2.17.0 at release61 branch

---

.github/workflows/test.yml

Install Oracle JDBC driver ojdbc11.jar
https://www.oracle.com/database/technologies/appdev/jdbc-ucp-21-1-c-downloads.html
Follow up #2155

Install Oracle JDBC driver ojdbc11.jar for GitHub Actions

---

lib/arel/visitors/oracle.rb

Address undefined method `to_i' for #<ActiveModel::Attribute::WithCastValue
```ruby
$ bundle exec rspec ./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb:404
==> Running specs with ruby version 3.0.1
==> Effective ActiveRecord version 7.0.0.alpha
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb"=>[404]}}
F
Failures:
1) OracleEnhancedAdapter using offset and limit should return the records starting from offset n with offset(n)
Failure/Error:
collector << ") raw_sql_
WHERE rownum <= #{offset.expr.to_i + limit}
NoMethodError:
undefined method `to_i' for #<ActiveModel::Attribute::WithCastValue:0x0000560c802ff318 @name="OFFSET", @value_before_type_cast=0, …
```

Address undefined method `to_i' for #<ActiveModel::Attribute::WithCastValue

---

.travis.yml

- Ruby 3.0.1 Released
https://www.ruby-lang.org/en/news/2021/04/05/ruby-3-0-1-released/
- Ruby 2.7.3 Released
https://www.ruby-lang.org/en/news/2021/04/05/ruby-2-7-3-released/

CI against Ruby 3.0.1 and 2.7.3

---

.rubocop.yml
lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb

Follow https://github.com/rails/rails/commit/bbbc861

Enable `Performance/MapCompact` cop

---

lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb

The original exception cause is hidden up to now if there's an exception while loading JDBC driver
For example providing ojdbc11.jar for Java 1.8 leads to the following error even if a JDBC driver file is provided:
NameError:cannot link Java class oracle.jdbc.OracleDriver oracle/jdbc/OracleDriver has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

get root cause if something went wrong with jdbc.OracleDriver

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

Follow https://github.com/rails/rails/pull/42075.
This PR supports single SQL statement syntax of Oracle for `remove_columns` and fixes the CI build error.
```console
(snip)
Failures:
1) OracleEnhancedAdapter schema definition alter columns with column
cache should remove column when using change_table
Failure/Error: expect(TestPost.columns_hash["title"]).to be_nil
expected: nil
got:
#<ActiveRecord::ConnectionAdapters::OracleEnhanced::Column:0x0000000003f99680
@name="title", @sql_typ...on=nil, @scale=nil>, @null=false,
@default=nil, @default_function=nil, @collation=nil,
@comment=nil>
`block in <module:Support>'
`notify_failure'
`fail_with'
`handle_failure'
`block in handle_matcher'
`with_matcher'
`handle_matcher'
`to'
`block (3 levels) in <top (required)>'
(snip)
2) …
```

Optimize remove_columns to use a single SQL statement when supported

---

lib/active_record/connection_adapters/oracle_enhanced/procedures.rb

This commit addresses the following failures since rails/rails#42355 .
`DEPRECATION WARNING` have not been fixed yet.
```ruby
$ bundle exec rspec spec/active_record/connection_adapters/oracle_enhanced/procedures_spec.rb
==> Running specs with ruby version 3.0.1
==> Effective ActiveRecord version 7.0.0.alpha
..FFDEPRECATION WARNING: `ActiveRecord::Base.partial_writes=` is deprecated and will be removed in Rails 7.1. Use `partial_updates=` and `partial_inserts=` instead. (called from block (2 levels) in <top (required)> at /home/yahonda/src/github.com/rsim/oracle-enhanced/spec/active_record/connection_adapters/oracle_enhanced/procedures_spec.rb:214)
FDEPRECATION WARNING: `ActiveRecord::Base.partial_writes=` is deprecated and will be removed in …
```

Address "NoMethodError: undefined method `partial_writes?'"

---

spec/active_record/connection_adapters/oracle_enhanced/procedures_spec.rb

Follow rails/rails#42355 and rsim/oracle-enhanced#2188.
This PR suppresses `partial_writes` deprecation warning.

Suppress `partial_writes` deprecation warning

---

lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/quoting.rb
spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb
spec/active_record/oracle_enhanced/type/timestamp_spec.rb

Follow https://github.com/rails/rails/commit/c6e4dbeebbfa4ea2b6d50a2ffb75f707b68aabf4.

Make `default_timezone` a module instance variable

---

.travis.yml

* JRuby 9.2.19.0 Released
https://www.jruby.org/2021/06/15/jruby-9-2-19-0.html

CI against JRuby 9.2.19.0

---

.github/workflows/test.yml
.travis.yml
guides/bug_report_templates/active_record_gem_spec.rb

Fixes #2100
* With this fix
```ruby
$ cd guides/bug_report_templates/
$ ruby active_record_gem_spec.rb
... snip ...
-- create_table(:posts, {:force=>true})
D, [2021-01-05T22:54:08.522170 #238157] DEBUG -- :    (21.9ms)  DROP TABLE "POSTS"
D, [2021-01-05T22:54:08.527701 #238157] DEBUG -- :    (5.1ms)  DROP SEQUENCE "POSTS_SEQ"
D, [2021-01-05T22:54:08.535820 #238157] DEBUG -- :    (7.8ms)  CREATE TABLE "POSTS" ("ID" NUMBER(38) NOT NULL PRIMARY KEY)
D, [2021-01-05T22:54:08.538683 #238157] DEBUG -- :    (2.6ms)  CREATE SEQUENCE "POSTS_SEQ" START WITH 1
-> 0.2223s
-- create_table(:comments, {:force=>true})
D, [2021-01-05T22:54:08.705173 #238157] DEBUG -- :    (18.4ms)  DROP TABLE "COMMENTS"
D, [2021-01-05T22:54:08.709548 #238157] DEBUG -- :    (4.1ms)  DROP SEQUENCE "COMMENTS_SEQ"
D, …
```

Address `guides/bug_report_templates/active_record_gem_spec.rb` error

---

.rubocop.yml
lib/active_record/connection_adapters/oracle_enhanced/context_index.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

This pull request enables `Layout/ClosingParenthesisIndentation` cop.
```ruby
Inspecting 70 files
........C..............C..............................................
Offenses:
lib/active_record/connection_adapters/oracle_enhanced/context_index.rb:163:17: C: [Correctable] Layout/ClosingParenthesisIndentation: Indent ) to column 14 (not 16)
} BEGIN
^
lib/active_record/connection_adapters/oracle_enhanced/context_index.rb:197:19: C: [Correctable] Layout/ClosingParenthesisIndentation: Indent ) to column 16 (not 18)
}
^
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb:672:23: C: [Correctable] Layout/ClosingParenthesisIndentation: Indent ) to column 12 (not 22)
)
^
70 files inspected, 3 offenses detected, 3 offenses auto-correctable
```
Refer …

Enable `Layout/ClosingParenthesisIndentation` cop

---

spec/active_record/connection_adapters/oracle_enhanced/context_index_spec.rb

This pull request suppresses these deprecation warnings.
```ruby
$ bundle exec rspec spec/active_record/connection_adapters/oracle_enhanced/context_index_spec.rb
==> Running specs with ruby version 3.0.1
==> Effective ActiveRecord version 7.0.0.alpha
..........DEPRECATION WARNING: As of Rails 7.1, destroy_all will no longer return the collection of objects that were destroyed. To transition to the new behaviour set the following in an initializer: Rails.application.config.active_record.destroy_all_in_batches = true (called from block (3 levels) in <top (required)> at /home/yahonda/src/github.com/rsim/oracle-enhanced/spec/active_record/connection_adapters/oracle_enhanced/context_index_spec.rb:209)
.DEPRECATION WARNING: As of Rails 7.1, destroy_all …
```

Suppress DEPRECATION WARNING by setting ActiveRecord::Base.destroy_all_in_batches = true

---

spec/active_record/connection_adapters/oracle_enhanced/schema_statements_spec.rb

Follow up to https://github.com/rubocop/rubocop/pull/9910.
This PR suppresses and corrects the following RuboCop's offense.
```console
% bundle exec rubocop -a
Inspecting 70 files
..................................................C...................
Offenses:
spec/active_record/connection_adapters/oracle_enhanced/schema_statements_spec.rb:1125:13:
C: [Corrected] Layout/SpaceAroundOperators: Surrounding space missing for operator <<.
class <<@conn
^^
spec/active_record/connection_adapters/oracle_enhanced/schema_statements_spec.rb:1131:13:
C: [Corrected] Layout/SpaceAroundOperators: Surrounding space missing for operator <<.
class <<@conn
^^
70 files inspected, 2 offenses detected, 2 offenses corrected
```

Suppress RuboCop's offense

---

spec/active_record/connection_adapters/oracle_enhanced/context_index_spec.rb

Reverts rsim/oracle-enhanced#2194

Revert "Suppress DEPRECATION WARNING by setting ActiveRecord::Base.destroy_all_in_batches = true"

---

.travis.yml

These Rubies have been released.
- https://www.ruby-lang.org/en/news/2021/07/07/ruby-3-0-2-released/
- https://www.ruby-lang.org/en/news/2021/07/07/ruby-2-7-4-released/

CI against Ruby 3.0.2 and 2.7.4

---

.github/workflows/ruby.yml
lib/active_record/connection_adapters/emulation/oracle_adapter.rb
lib/active_record/connection_adapters/oracle_enhanced/column.rb
lib/active_record/connection_adapters/oracle_enhanced/connection.rb
lib/active_record/connection_adapters/oracle_enhanced/database_limits.rb
lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/lob.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/procedures.rb
lib/active_record/connection_adapters/oracle_enhanced/quoting.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_definitions.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced/structure_dump.rb
lib/active_record/connection_adapters/oracle_enhanced/type_metadata.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

https://github.com/rubocop/rubocop/releases/tag/v1.19.0
* Disable parallel option since it is enabled by default since RuboCop 1.19.0
* Make Layout/LeadingCommentSpace aware of #:nodoc
https://github.com/rubocop/rubocop/pull/9964

Support RuboCop 1.19.0

---

.github/workflows/test.yml

This pull request runs `gvenzl/oracle-xe` Oracle Database XE Docker image.
Refer
https://hub.docker.com/r/gvenzl/oracle-xe
https://geraldonit.com/2021/08/15/oracle-xe-docker-images/

Use gvenzl/oracle-xe docker image

---

.github/workflows/test.yml
lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
lib/active_record/connection_adapters/oracle_enhanced/jdbc_quoting.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_quoting.rb
lib/active_record/connection_adapters/oracle_enhanced/quoting.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

This pull request supports  `Define adapter type maps statically when possible` https://github.com/rails/rails/pull/42773 in Active Record Oracle enhanced adapter. 
Also, to make CI green this pull request needs these additional commits.
* Use Oracle Instant Client 21.4
* Rename `_quote` to `quote`
* Rename `_type_cast` to `type_cast`

Define adapter type maps statically when possible

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb

Follow up to https://github.com/rails/rails/pull/43097.
While working on this PR, I noticed a lack of follow up to `execute_batch`.
The resources related to `execute_batch` are:
- https://github.com/rails/rails/commit/0ad70eb2d063cab577a559f6c3d28e787ca1dca8
- https://github.com/rails/rails/commit/21f0855dd6ee624429f92d0a67d5d95fa75ff9cc
- https://github.com/rails/rails/pull/37707
Anyway, following up to `execute_batch` will be a different task than this PR.

Refactor ActiveRecord::QueryLogs hook point

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

Follow up to https://github.com/rails/rails/pull/38967.
The `if_exists` option has been introduced since Rails 6.1.

Add `if_exists` option to `remove_index`

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
spec/active_record/oracle_enhanced/type/custom_spec.rb

As described in #2200, presently only `ActiveRecord::Type::Serialized`
attributes are serialized before being written to database by `#write_lobs`.
It was introduced with 75ed13e6a7c42024ff4d57642a1a06f2bdfedc99
Any other attributes are just converted to string by `value.to_s`.
My understanding is that all attributes should go through standard serialization regardless their type. Especially any custom attributes.
Otherwise instead of writing whatever serialized form of attribute is, database record would become `"#<MyCustomAttributeType:0x000000000bdb6590>\",\"whaever garbage...` or some other string representation that was not intended to end up inside the database.
With this update all attributes get serilized in the standard way.
/fixes #2200

all attributes serialized before writing

---

.github/workflows/ruby.yml
.github/workflows/test.yml

* Ruby 3.1.0 Released
https://www.ruby-lang.org/en/news/2021/12/25/ruby-3-1-0-released/

CI against Ruby 3.1 at GitHub Actions

---

.travis.yml

* Ruby 3.0.3 Released
https://www.ruby-lang.org/en/news/2021/11/24/ruby-3-0-3-released/
* Ruby 2.7.5 Released
https://www.ruby-lang.org/en/news/2021/11/24/ruby-2-7-5-released/
`gem update --system` added to workaround this error.
- `require': superclass mismatch for class StringIO (TypeError)

Bump Ruby versions at Travis CI

---

guides/bug_report_templates/active_record_gem.rb
guides/bug_report_templates/active_record_gem_spec.rb

While testing #2240, bug report templates fails as follows.
https://github.com/rsim/oracle-enhanced/runs/4769573945?check_suite_focus=true
```
/opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/bundler-2.3.4/lib/bundler/runtime.rb:309:in `check_for_activated_spec!': You have already activated digest 3.0.0, but your Gemfile requires digest 3.1.0. Since digest is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports digest as a default gem. (Gem::LoadError)
```
`digest` gem is required `net-imap`, `net-pop` and `net-smtp` gem for
`actionmailbox` and `actionmailer` since
https://github.com/rails/rails/pull/44083 . To workaround this failure
this commit changes to require `activerecord` in bug report templates.
* …

Require 'activerecord', not 'rails' not to attempt to install digest

---

activerecord-oracle_enhanced-adapter.gemspec

Add `ruby-oci8` as dependency only for CRuby

---

README.md

[skip ci] No need to install `ruby-oci8` separately in Gemfile

---

lib/arel/visitors/oracle.rb
lib/arel/visitors/oracle12.rb
lib/arel/visitors/oracle_common.rb
spec/active_record/oracle_enhanced/type/character_string_spec.rb

Oracle documentation suggests to use `UPPER()` when case-insensitive search is desired. I have used that here. Without it the comparison is only case-sensitive unlike MySQL and Postgres where it can be one or the other by user choice.
Probably upgrade notes should point out that by default matching is case-insensitive. If anybody used it as case-sensitive without passing the `case_sensitive` parameter to `#matches`, then they can be surprised by this change.

support LIKE case-insensitive matching

---

RUNNING_TESTS.md

docker-oracle-xe-11g has been removed from docker hub.
Change link to docker-oracle-xe-11g-r2
https://github.com/wnameless/docker-oracle-xe-11g

Fix broken link

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Running `ARCONN=oracle bundle exec ruby -Itest ./test/cases/finder_test.rb -n test_find_with_order_on_included_associations_with_construct_finder_sql_for_association_limiting_and_is_distinct` in Rails 6.1.4.4 will result in an error.
```
ARCONN=oracle bundle exec ruby -Itest ./test/cases/finder_test.rb -n test_find_with_order_on_included_associations_with_construct_finder_sql_for_association_limiting_and_is_distinct
Using oracle
Warning: NLS_LANG is not set. fallback to US7ASCII.
Run options: -n test_find_with_order_on_included_associations_with_construct_finder_sql_for_association_limiting_and_is_distinct --seed 32511
F
Failure:
FinderTest#test_find_with_order_on_included_associations_with_construct_finder_sql_for_association_limiting_and_is_distinct [./test/cases/finder_test.rb:1503]: …
```

Fix columns_for_distinct when using Rails 6.1

---

History.md

The target branch is `release61` directly because the master branch already releases 7.0.z.

Prepare release v6.1.6 [skip ci]

---

.travis.yml

* Ruby 3.1.0 Released
https://www.ruby-lang.org/en/news/2021/12/25/ruby-3-1-0-released/

CI against Ruby 3.1 at Travis CI

---

lib/arel/visitors/oracle_common.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb
spec/active_record/oracle_enhanced/type/raw_spec.rb
spec/active_record/oracle_enhanced/type/text_spec.rb

support LOB equality

---

spec/active_record/oracle_enhanced/type/custom_spec.rb

Follow up #2203
This commit addresses these two failures.
```ruby
$ bundle exec rspec ./spec/active_record/oracle_enhanced/type/custom_spec.rb
==> Running specs with ruby version 3.1.1
==> Effective ActiveRecord version 7.1.0.alphaFF
Failures:
1) OracleEnhancedAdapter custom types handling should serialize LOBs when creating a record
Failure/Error: Base64.encode64 value.raw
NameError:
uninitialized constant TestEmployee::AttributeSignature::Base64
Base64.encode64 value.raw
^^^^^^
2) OracleEnhancedAdapter custom types handling should serialize LOBs when updating a record
Failure/Error: Base64.encode64 value.raw
NameError:
uninitialized constant TestEmployee::AttributeSignature::Base64
Base64.encode64 value.raw
^^^^^^
Finished in 2.1 seconds (files …
```

Addres `uninitialized constant TestEmployee::AttributeSignature::Base64`

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/jdbc_quoting.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_quoting.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb
spec/active_record/oracle_enhanced/type/dirty_spec.rb

Follow up https://github.com/rails/rails/pull/44530.

Rename the raw connection ivar to `@raw_connection`

---

.rubocop.yml
lib/active_record/connection_adapters/oracle_enhanced/connection.rb

Related to rails/rails#44555
```ruby
$ bundle exec rubocop -A
.......C................................................................
Offenses:
lib/active_record/connection_adapters/oracle_enhanced/connection.rb:104:37: C: [Corrected] Style/MapToHash: Pass a block to to_h instead of calling map.to_h.
columns.each_with_index.map { |x, i| [x, row[i]] }.to_h if row
^^^
72 files inspected, 1 offense detected, 1 offense corrected
$
```

Enable `Style/MapToHash` cop

---

.github/workflows/linting.yml
.github/workflows/ruby.yml
.github/workflows/test.yml
.rubocop.yml
.travis.yml
.yamllint.yml

Refer to https://github.com/rubocop/rubocop/pull/10392

Support linting YAML files

---

Gemfile

debug gem requires Ruby 2.6.0 which is satisified
with Active Record Oracle enhanced adapter master branch which already
requires Ruby 2.7.

Use `debug` gem to replace `byebug`

---

.rubocop.yml
Gemfile
spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/database_tasks_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/schema_dumper_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/schema_statements_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/structure_dump_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

Enabled these "style" cops for now.
```
RSpec/EmptyLineAfterExampleGroup
RSpec/EmptyLineAfterHook
RSpec/EmptyLineAfterSubject
RSpec/HooksBeforeExamples
```
```ruby
...........................................C..C...CCCC..................
Offenses:
spec/active_record/connection_adapters/emulation/oracle_adapter_spec.rb:17:3: C: [Corrected] RSpec/EmptyLineAfterHook: Add an empty line after after.
end
^^^
spec/active_record/connection_adapters/emulation/oracle_adapter_spec.rb:18:3: C: [Corrected] RSpec/HooksBeforeExamples: Move after above the examples in the group.
after(:all) do ...
^^^^^^^^^^^^^^
spec/active_record/connection_adapters/emulation/oracle_adapter_spec.rb:23:1: C: [Corrected] Layout/EmptyLinesAroundBlockBody: Extra empty line …
```

Introduce RuboCop RSpec

---

.rubocop.yml
spec/active_record/connection_adapters/oracle_enhanced/structure_dump_spec.rb

This cop actually finds the actual repeated examples below. So let's
remove them.
```ruby
....................................................C...................
Offenses:
spec/active_record/connection_adapters/oracle_enhanced/structure_dump_spec.rb:219:5: C: RSpec/RepeatedExample: Don't repeat examples within an example group.
it "should dump table comments" do ...
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spec/active_record/connection_adapters/oracle_enhanced/structure_dump_spec.rb:226:5: C: RSpec/RepeatedExample: Don't repeat examples within an example group.
it "should dump column comments" do ...
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spec/active_record/connection_adapters/oracle_enhanced/structure_dump_spec.rb:233:5: C: RSpec/RepeatedExample: Don't …
```

Enable `RSpec/RepeatedExample` cop

---

.rubocop.yml
spec/active_record/connection_adapters/oracle_enhanced/dbms_output_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/schema_statements_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

This pull request enables `RSpec/RepeatedDescription` cop.
These offenses are fixed manually.
```ruby
...............................................C...C.C..................
Offenses:
spec/active_record/connection_adapters/oracle_enhanced/dbms_output_spec.rb:50:3: C: RSpec/RepeatedDescription: Don't repeat descriptions within an example group.
it "should log dbms output lines to the rails log" do
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spec/active_record/connection_adapters/oracle_enhanced/dbms_output_spec.rb:60:3: C: RSpec/RepeatedDescription: Don't repeat descriptions within an example group.
it "should log dbms output lines to the rails log" do
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
```

Enabled `RSpec/RepeatedDescription` cop

---

activerecord-oracle_enhanced-adapter.gemspec

Follow up https://github.com/rails/rails/commit/9195b7f and https://github.com/rails/rails/commit/1fde031.
This product can tell gem users that it has been released using MFA.
For example, users can see it with `REQUIRES MFA ACCOUNTS` on the Rails gem page:
https://rubygems.org/gems/rails
It's up to @yahonda as the lead maintainer to decide whether or not to take this.
There are other items that can be set in the `s.metadata`, but that is not the purpose of this PR.

Require MFA to release

---

.travis.yml

* Ruby 3.1.1 Released
https://www.ruby-lang.org/en/news/2022/02/18/ruby-3-1-1-released/

CI against Ruby 3.1.1 at Travis CI

---

lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb

Additional connect properties for JDBC connection in adapter config (database.yml).
This allows to configure several additional JDBC connect properties, especially network encryption and network checksumming (like requested in #2058) by:
```
adapter: oracle_enhanced
jdbc_connect_properties:
'oracle.net.encryption_client': REQUIRED
'oracle.net.crypto_checksum_client': REQUIRED
```

Additional connect properties for JDBC connection in adapter config

---

.travis.yml

These Rubies have been released.
- https://www.ruby-lang.org/en/news/2022/04/12/ruby-3-1-2-released/
- https://www.ruby-lang.org/en/news/2022/04/12/ruby-3-0-4-released/
- https://www.ruby-lang.org/en/news/2022/04/12/ruby-2-7-6-released/

CI against Ruby 3.1.2, 3.0.4, and 2.7.6

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
spec/active_record/connection_adapters/oracle_enhanced/schema_statements_spec.rb
spec/active_record/oracle_enhanced/type/dirty_spec.rb

This patch makes unique constraints to also
specify index name it should affect.
Otherwise it picks the first index that it finds that
contains that column name, even if it is shared with other columns and it
is not unique.
I included in the pull request two other test updates if you don't mind.

unique constraint to also specify index

---

.github/workflows/test.yml

Reverts rsim/oracle-enhanced#2130
As a side effect, setting `continue-on-error: true` marks the status "Success" even if the Jobs fails .  
Refer to https://github.com/rsim/oracle-enhanced/actions/runs/2606963371

Revert "Configure `continue-on-error: true` to run all CI"

---

RUNNING_TESTS.md

rsim/oracle-enhanced repository was migrated and is now building on travis-ci.com.

Update link address of Travis from travis.org to travis.com

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/oracle_enhanced/type/integer_spec.rb

This appears to fix issue #2256. I believe it should have the same memory implications as the intention in #2199. The type maps are loaded once when they are first called. Only one instance of the mapping is ever created.
Fortunately this was enough to solve the problem, but if there were a need, this could easily be worked into the clear_cache! API to reset it at a later point in the application just by setting the @type_map to nil.
(clean patch against the master branch, nothing from the release70 here)

Lazy load type mappings

---

.github/workflows/test.yml

Enable running specs on CI against TruffleRuby.

CI: Add fast-fail: false

---

lib/active_record/connection_adapters/oracle_enhanced/quoting.rb

This commit addresses the following offense.
```ruby
...................C....................................................
Offenses:
lib/active_record/connection_adapters/oracle_enhanced/quoting.rb:29:33: C: [Corrected] Style/RedundantRegexpEscape: Redundant escape inside regexp literal
when /^[a-z][a-z_0-9$#\-]*$/i
^^
72 files inspected, 1 offense detected, 1 offense corrected
$
```

Address `Style/RedundantRegexpEscape` offense

---

.github/workflows/test.yml

https://github.blog/changelog/2022-08-09-github-actions-ubuntu-22-04-is-now-generally-available-on-github-hosted-runners/

Use Ubuntu 22.04

---

.github/workflows/rubocop.yml

This pull request renames GitHub workflow name from Ruby to RuboCop. Renamed the file name as follows.
```
$ git mv ruby.yml rubocop.yml
```

Rename GitHub workflow name from Ruby to RuboCop

---

.github/workflows/test.yml

This pull request adds CI against Ruby 3.2 at GitHub Actions.

CI against Ruby 3.2

---

.github/workflows/rubocop.yml

This pull request bumps Oracle Instant Client 21.9.0.0.0 for RuboCop
Follow up #2320

Use Oracle Instant Client 21.9.0.0.0 for RuboCop

---

.github/workflows/rubocop.yml

This pull request uses Ruby 3.2 for RuboCop workflow
Follow-up #2321

Use Ruby 3.2 for RuboCop workflow

---

.github/workflows/test.yml
.travis.yml
Gemfile
lib/active_record/connection_adapters/oracle_enhanced/dbms_output.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

This pull request supports rails/rails#44576
Fix #2306

Support rails/rails#44576

---

Gemfile

This pull request ensures unit tests run successfully before rails/rails#44591 is merged. 
It should fail since this commit is merged https://github.com/rails/rails/commit/deec3004d8d85443dc4f3f5fd22ab86b10adb58b then the previous commit https://github.com/rails/rails/commit/0e9267767f19065fa513038253179ad6b05c29ab is used tentatively.

Make sure unit tests run successfully before rails/rails#44591 is merged

---

ci/setup_accounts.sh

This pull request do not call `spec/support/alter_system_user_password.sql` at GitHub Actions
It is not necessary for GitHub Actions.

Not running spec/support/alter_system_user_password.sql at GitHub Actions

---

.github/workflows/test_11g.yml
ci/network/admin/tnsnames.ora
spec/active_record/oracle_enhanced/type/timestamp_spec.rb

This pull request enables Oracle Database 11g CI using GitHub Actions
- Skip timezone-related tests which are expected to fail as ORA-01805 error
- Keep the .travis.yml for the time being, it will be removed later
- Skip bug report templates until Oracle enhanced adapter supports the latest Rails main branch

Run Oracle Database 11g CI using GitHub Actions

---

.travis.yml

- Ruby 3.0 and Ruby 2.7 are dropped because it is not compatible with Ubuntu 22.04 (Jammy Jellyfish) that ships with OpenSSL 3 and OpenSSL 3 support is available only for Ruby 3.1 or higher
Refer to https://bugs.ruby-lang.org/issues/18658
> We decided to not backport openssl-3.x gem into ruby_2_7 and ruby_3_0 branches. Because it affects with OpenSSL 1.0.x.
CI against Oracle Database 11g will be migrated to GitHub Actions via https://github.com/rsim/oracle-enhanced/pull/2327
that runs all Ruby versions supported by Rails main branch, so removing Ruby 2.7 and 3.0 here should be safe.

Use Ubuntu 22.04 (Jammy Jellyfish) at Travis CI

---

.github/workflows/rubocop.yml
.github/workflows/test.yml
.github/workflows/test_11g.yml

This pull request uses Oracle Instant Client Version 21.10.0.0.0 (Requires glibc 2.14)

Use Oracle Instant Client Version 21.10.0.0.0

---

.github/workflows/test.yml
.github/workflows/test_11g.yml

because `Run RSpec` did not finish after 5h 55m running. https://github.com/rsim/oracle-enhanced/actions/runs/4963761266/jobs/8883291465

Disable `truffleruby-head` from our CI

---

lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced/structure_dump.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

This pull request removes `OPTIMIZER_FEATURES_ENABLE('11.2.0.2')` hint
This hint caused slowness #2179, and I decided to remove this hint.
There are no significant elapsed time changes with/without this hint in our CI:
* With `OPTIMIZER_FEATURES_ENABLE('11.2.0.2')` hint
- test that runs Oracle Database 23c XE
https://github.com/rsim/oracle-enhanced/actions/runs/4963761266/jobs/8883291198?pr=2337
> Finished in 5 minutes 43 seconds (files took 0.70408 seconds to load)
- test_11g that runs Oracle Database 11g XE
https://github.com/rsim/oracle-enhanced/actions/runs/4963761261/jobs/8883291209?pr=2337
> Finished in 17 minutes 39 seconds (files took 0.6625 seconds to load)
* Without `OPTIMIZER_FEATURES_ENABLE('11.2.0.2')` hint
- test that runs Oracle Database 23c XE …

Remove `OPTIMIZER_FEATURES_ENABLE('11.2.0.2')` hint

---

.github/workflows/test.yml
.github/workflows/test_11g.yml

Revisit when we can resume CI against JRuby.
Refeer to https://github.com/rsim/oracle-enhanced/pull/2035 rubygems/rubygems#3796

Remove workaround for jruby-head

---

lib/active_record/connection_adapters/oracle_enhanced/quoting.rb

This pull request supports rails/rails#48773.
As of right now, Oracle enhanced adapter master branch has not support the latest commit of Rails main branch yet,
this commit has been made for release70 branch first the cherry-picked to master branch without testing.
```ruby
$ bundle exec rspec ./spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb:234 # OracleEnhancedConnection default_timezone should respect default_timezone = :utc than time_zone setting
==> Running specs with ruby version 3.2.2
==> Effective ActiveRecord version 7.0.6
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb"=>[234]}}
F
An error occurred in an `after(:context)` hook.
Failure/Error: …
```

Make ActiveRecord's quoted name caches thread-safe on JRuby/TruffleRuby

---

.github/workflows/rubocop.yml
.github/workflows/test.yml

This pull request uses Oracle Instant Client Version 21.11.0.0.0.

Use Oracle Instant Client Version 21.11.0.0.0

---

.github/workflows/rubocop.yml
.github/workflows/test.yml
.github/workflows/test_11g.yml
.travis.yml

This pull request adds CI against Ruby 3.3
* Ruby 3.3.0 Released
https://www.ruby-lang.org/en/news/2023/12/25/ruby-3-3-0-released/
* Fallback to update RubyGems version to 3.4.22 if update to the latest version fails for Ruby 2.7

CI against Ruby 3.3

---

Gemfile

This commit bumps Rails version to https://github.com/rails/rails/commit/0e92677
Here is the difference between the current master branch and this commit. https://github.com/rails/rails/compare/8551e64e2411811f26d210601abdba6e13d8798c...0e92677

Bump Rails version to https://github.com/rails/rails/commit/0e92677

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_quoting.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb

Introduce the _connection method, which returns whichever is defined between @unconfigured_connection or @raw_connection.
See rails commit: https://github.com/rails/rails/commit/deec3004d8d85443dc4f3f5fd22ab86b10adb58b
and issue #2329

Add _connection method (1)

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_quoting.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb

Directly related to #2329 and the previous pr #2367 for the `raw_connection` method specifically calling `verify!` should ensure that the @raw_connection is configured and set.
This is stacked on top of #2367

Ensure `raw_connection` has a @raw_connection set (2)

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_quoting.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb
spec/spec_helper.rb

Improve MockLogger - level/limited missing method
Rails commit bd19d1baf1 [1] added a check of logger.level which was not
supported by the MockLogger.
This commit adds a mock level method. And limits the missing_method to
respond only to logging calls, so any other calls will raise a
NoMethodError to make future debugging easier.
[1]
https://github.com/rails/rails/commit/bd19d1baf1cb006f3e9f16afac1c7b4e693f111c
Stacked on #2368

    Improve MockLogger - level/limited missing method (3)

---

Gemfile
lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_quoting.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/database_tasks_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/schema_statements_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/structure_dump_spec.rb
spec/spec_helper.rb

Support Rails 7.1's Independent SchemaMigration object.
The SchemaMigration object no longer inherits from ActiveRecord::Base.
See "Move SchemaMigration to an independent object"
https://github.com/rails/rails/commit/436277da88507f9aae0874e62f3e61a8546b9683
Several methods were renamed, and are no longer available as class
methods on SchemaMigration, but as an instance of SchemaMigration
per connection.
The object per connection seems to remove the need to `reset_table_name`
in the tests. That method is not available on the new object.
Stacked on #2369

Support Rails 7.1's Independent SchemaMigration object  (4)

---

Gemfile
lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_quoting.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_definitions.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/database_tasks_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/schema_statements_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/structure_dump_spec.rb
spec/spec_helper.rb

Support Rails 7.1 ColumnDefinition validations.
Rails commit e6da3ebd6c6 [1] introduces ColumnDefinition validations for
the keywords used in database commands. This commit adds the additional
keywords supported by this gem.
[1] https://github.com/rails/rails/commit/e6da3ebd6c65af23d134a9e01145f26600912008
Stacked on #2370

Support Rails 7.1 ColumnDefinition validations  (5)

---

Gemfile
lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_quoting.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_definitions.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
lib/arel/visitors/oracle.rb
lib/arel/visitors/oracle12.rb
spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/database_tasks_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/schema_statements_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/structure_dump_spec.rb
spec/spec_helper.rb

Rails 7.1 use the visitor pattern when building the in clause.
See https://github.com/rails/rails/commit/07d2407beef5479751062d97d775edb4e1614684
Both `table_name` and `column_name` were removed in favor of doing
o.left in the visitor pattern. This is just mimicking the adjustments
from upstream.
Stacked on #2371

Rails 7.1 use the visitor pattern when building the in clause  (6)

---

Gemfile
lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_quoting.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_definitions.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
lib/arel/visitors/oracle.rb
lib/arel/visitors/oracle12.rb
spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/database_tasks_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/schema_statements_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/structure_dump_spec.rb
spec/spec_helper.rb

Rails now defaults to its own index name shortening (limited to 62 bytes).
This change overrides the rails max to exceed this gems shortening
method in order to preserve the historical behavior.
names
See https://github.com/rails/rails/commit/3682aa1016e187398a7ae65e521f24f38b710d2b
So the shortening of index names that was added to rails itself
was almost immediately changed to use an 'idx_' prefix instead of an 'ix_'
prefix.
See https://github.com/rails/rails/commit/59f2b06493bed2c036f6b527e743198416ee1237
However, now that rails does shortening. It is an opportunity to
consider simplifying this library and just using that.
Stacked on #2374

Override the max_index_name_size to keep local shortening algorithm.  (8)

---

Gemfile
lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_quoting.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_definitions.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
lib/arel/visitors/oracle.rb
lib/arel/visitors/oracle12.rb
spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/database_tasks_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/schema_statements_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/structure_dump_spec.rb
spec/spec_helper.rb

Add allow_retry kwarg to execute
This extends the existing class level auto_retry functionality to
optionally allow an allow_retry boolean kwarg to allow retry of specific
queries.
This PR preserves the requirement that `autocommit?` be enabled, which is the
safer choice.
```
def with_retry(allow_retry: false) # :nodoc:
should_retry = (allow_retry || self.class.auto_retry?) && autocommit?
```
See issue #2310
Stacked on #2372

Add allow_retry kwarg to execute (7)

---

Gemfile
lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_quoting.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_definitions.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
lib/arel/visitors/oracle.rb
lib/arel/visitors/oracle12.rb
spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/database_tasks_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/schema_statements_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/structure_dump_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb
spec/spec_helper.rb

Fix deprecation warning about serializer keywords
DEPRECATION WARNING: Passing the class as positional argument is deprecated and will be removed in Rails 7.2.
Please pass the class as a keyword argument:
serialize :serialized, type: Array
(called from <class:TestSerializedColumn> at /home/andy/src/oracle-enhanced/spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb:446)
Stacked on #2374

Fix deprecation warning about serializer keywords (9)

---

Gemfile
lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_quoting.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_definitions.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
lib/arel/visitors/oracle.rb
lib/arel/visitors/oracle12.rb
lib/arel/visitors/oracle_common.rb
spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/database_tasks_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/schema_statements_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/structure_dump_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb
spec/spec_helper.rb

Add alias to internal_exec_query
In rails commit https://github.com/rails/rails/commit/942785fb8b03772dde338cc241af8e5de4d2efbc
A method `internal_exec_query` is introduced as the implementation for
exec_query. For now this just aliases one to the other.
Stacked on #2375

Add alias to internal_exec_query (11)

---

Gemfile
lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_quoting.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_definitions.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
lib/arel/visitors/oracle.rb
lib/arel/visitors/oracle12.rb
lib/arel/visitors/oracle_common.rb
spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/database_tasks_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/schema_statements_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/structure_dump_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb
spec/spec_helper.rb

Switch to Arel::Table.name instead of removed alias table_name.
Rails removed the table_name alias to Arel::Table.name
See https://github.com/rails/rails/commit/1d98bc563a8a7faf26238eaaa54a3257a95d644d

Switch to Arel::Table.name instead of removed alias table_name. (10)

---

Gemfile
lib/active_record/connection_adapters/oracle_enhanced/column.rb
lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_quoting.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_definitions.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
lib/arel/visitors/oracle.rb
lib/arel/visitors/oracle12.rb
lib/arel/visitors/oracle_common.rb
spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/database_tasks_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/schema_statements_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/structure_dump_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb
spec/spec_helper.rb

Make insert return an array, and include the id_value if super returns nil
ActiveRecord::ConnectionAdapters::OracleEnhanced::DatabaseStatements#insert
The super here is not returning the id_value if it is available (as it used
to). Furthermore ActiveRecord::Persistence#_create_record expects an
array of values.
I don't think this is the right change. In fact I think that the original abstract
ActiveRecord::ConnectionAdapters::DatabaseStatements#insert
may not be handling id_value correctly. The method appears to sometimes return
an array, and other times return a singular id_value.
However, I do think this highlights the crux of supporting rails 7.1 in this library as with this little tweak, all the tests passing against rails 7-1-stable.
This fixes #2380

Make insert return an array, and include the id_value if super returns nil (12)

---

RUNNING_TESTS.md
spec/spec_config.yaml.template

The CI suite uses `gvenzl/oracle-free:latest` see commit ceaa818fa911d93f100dc27855c4fefcda9ddb11. This PR updates the RUNNING_TESTS.md "Create by yourself" section to use the same image, and adjusts the spec_config.yaml.template to match.
There is also some incidental cleanup here:
- Correct a spelling typo.
- Remove the prompt prefix in code blocks to make them easier to copy.

Update test instructions to match CI docker image.

---

.github/workflows/rubocop.yml
.github/workflows/test.yml

This pull request updates the Oracle Instant Client version to 23.5.0.0.0 to use same Oracle database / client version.

Use Oracle Instant Client 23.5.0.0.0

---

spec/active_record/connection_adapters/oracle_enhanced/schema_statements_spec.rb

```ruby
$ bundle exec rspec ./spec/active_record/connection_adapters/oracle_enhanced/schema_statements_spec.rb:330
==> Running specs with ruby version 3.3.4
==> Effective ActiveRecord version 7.1.3.4
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced/schema_statements_spec.rb"=>[330]}}
F
Failures:
1) OracleEnhancedAdapter schema definition add index should raise error if too large index name cannot be shortened
Failure/Error:
expect(@conn.index_name("test_employees", column: ["first_name", "middle_name", "last_name"])).to eq(
("idx_on_first_name_middle_name_last_name_ee1d3958bc"))
expected: "idx_on_first_name_middle_name_last_name_ee1d3958bc"
got: …
```

Address `OracleEnhancedAdapter schema definition add index should raise error if too large index name cannot be shortened` failure

---

.github/workflows/test_11g.yml

This commit addresses the following error at https://github.com/rsim/oracle-enhanced/actions/runs/10371233946/job/28711049632#step:7:30
```shell
Run sudo alien -i oracle-instantclient-basic-21.10.0.0.0-1.x86_64.rpm
Warning: Skipping conversion of scripts in package oracle-instantclient-basic: postinst postrm
Warning: Use the --scripts parameter to include the scripts.
dpkg --no-force-overwrite -i oracle-instantclient-basic_21.10.0.0.0-2_amd64.deb
Selecting previously unselected package oracle-instantclient-basic.
(Reading database ... 267026 files and directories currently installed.)
Preparing to unpack oracle-instantclient-basic_21.10.0.0.0-2_amd64.deb ...
Unpacking oracle-instantclient-basic (21.10.0.0.0-2) ...
Setting up oracle-instantclient-basic (21.10.0.0.0-2) ...
Processing …
```

Install Oracle Instant Client using zip file

---

.github/workflows/test_11g.yml
spec/active_record/oracle_enhanced/type/timestamp_spec.rb

This pull request skips specs if the Oracle server and client versions do not match
https://github.com/rsim/oracle-enhanced/actions/runs/10371897254/job/28713269701?pr=2387
```
OCIError: ORA-01805: possible error in date/time operation
```

Skip tests if database and client versions do not match

---

spec/active_record/oracle_enhanced/type/timestamp_spec.rb

Skip specs correctly if `DATABASE_SERVER_AND_CLIENT_VERSION_DO_NOT_MATCH` set to true
This commit skips failing specs correctly if `DATABASE_SERVER_AND_CLIENT_VERSION_DO_NOT_MATCH` set to true
Follow up #2389
```ruby
$ export DATABASE_SERVER_AND_CLIENT_VERSION_DO_NOT_MATCH="true"
$ bundle exec rspec ./spec/active_record/oracle_enhanced/type/timestamp_spec.rb
==> Running specs with ruby version 3.3.5
/home/yahonda/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/bundler/gems/rails-cefd9e9942c5/activesupport/lib/active_support/logger_silence.rb:5: warning: logger was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add logger to your Gemfile or gemspec to silence this warning.
==> Effective …
```

Skip specs correctly if `DATABASE_SERVER_AND_CLIENT_VERSION_DO_NOT_MATCH` set to true

---

activerecord-oracle_enhanced-adapter.gemspec

This pull request updates add_runtime_dependency not to install Active Record 7.2 yet.

Update add_runtime_dependency not to install Active Record 7.2 yet

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb

This commit implements `build_explain_clause(options = [])` that is no-op to remove the warning below because Oracle Database does not support something like `explain analyze` in MySQL.
```ruby
$ bundle exec rspec spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb:356
==> Running specs with ruby version 3.3.5
/home/yahonda/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/bundler/gems/rails-cefd9e9942c5/activesupport/lib/active_support/logger_silence.rb:5: warning: logger was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add logger to your Gemfile or gemspec to silence this warning.
==> Effective ActiveRecord version 7.1.4
Run options: include …
```

Support `build_explain_clause(options = [])`

---

Gemfile

This commit removes unused entries from Gemfile.

Remove unused entries from Gemfile

---

.github/workflows/rubocop.yml
.github/workflows/test.yml

This commit bumps the Oracle Instant Client Version to 23.6.0.0.0

Use Oracle Instant Client Version 23.6.0.0.0

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb

This PR fixes #2432
[`ActiveRecord.connection.verify!`](https://api.rubyonrails.org/v7.1/classes/ActiveRecord/ConnectionAdapters/AbstractAdapter.html#method-i-verify-21) fails on Rails 7.1.0+ when reconnection is needed, because **Rails 7.1 added an optional argument** `restore_transactions: false` to the [`#reconnect!`](https://api.rubyonrails.org/v7.1/classes/ActiveRecord/ConnectionAdapters/AbstractAdapter.html#method-i-reconnect-21) method which is used e.g. inside the [`#verify!`](https://api.rubyonrails.org/v7.1/classes/ActiveRecord/ConnectionAdapters/AbstractAdapter.html#method-i-verify-21)
This change has been implemented in https://github.com/rails/rails/pull/44573 and it appeared in Rails `7.1.0beta1` for the first time.
**Oracle Enhanced Driver Implementation** …

Add optional argument to reconnect for Rails 7.1+ compatibility

---

.github/workflows/rubocop.yml
Gemfile
lib/active_record/connection_adapters/oracle_enhanced/quoting.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
lib/arel/visitors/oracle_common.rb
spec/active_record/connection_adapters/emulation/oracle_adapter_spec.rb

This commit runs RuboCop in GitHub Actions.
- Create `:rubocop` group in Gemfile
Add `BUNDLE_ONLY` available since Bundler 2.3.19
https://github.com/rubygems/rubygems/blob/master/bundler/CHANGELOG.md#2319-july-27-2022
- Use Ruby 3.4
- No need to install Oracle Instant Client to run RuboCop
- Address these offenses as a separate commit
```ruby
Inspecting 73 files
...................W.......C..............CC.............................
Offenses:
lib/active_record/connection_adapters/oracle_enhanced/quoting.rb:49:13: C: [Corrected] Layout/IndentationWidth: Use 2 (not 32) spaces for indentation.
"\"#{name.upcase}\""
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/active_record/connection_adapters/oracle_enhanced/quoting.rb:50:43: C: [Corrected] Layout/ElseAlignment: Align else …
```

Run RuboCop in GitHub Actions

---

.github/workflows/rubocop.yml

This environment variable is not necessary anymore since #2439

Remove `LD_LIBRARY_PATH` from rubocop.yml

---

.github/workflows/test.yml
.github/workflows/test_11g.yml
lib/active_record/connection_adapters/oracle_enhanced/context_index.rb
lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
lib/active_record/connection_adapters/oracle_enhanced/dbms_output.rb
lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb

Building on top of #2424 this adds support for existing oracle_enhanced functionality to Rails 8.0. It may not fully support new Rails 8.0 features; For example there seems to be retry logic in rails now, and the oracle enhanced adapter is still doing its own thing.
- Add `write_query?` implementation (mimicking postgres) to support the ability to prevent writes to a database - https://github.com/rails/rails/commit/f39d72d5267baed1000932831cda98503d1e1047
- Replace the local implementation of execute, exec_query and its alias internal_exec_query with the new interface defined here https://github.com/rails/rails/commit/fd24e5bfc9540fc00764a59ddf39a993bbd63ba2 of `raw_execute`, `cast_result`, and `affected_rows`. To support the affected_rows count this also had to add a `row_count` method …

Support Rails 8.0

---

.github/workflows/ruby_head.yml

This pull request adds CI against Ruby master branch:
- It runs on a daily schedule, so it should not require pull requests to pass this test
head - Ruby master branch
debug - `head` with assertions enabled `-DRUBY_DEBUG=1`
- YJIT enabled
Refer https://github.com/railsdoc/railsdoc.github.io/pull/173
- Add `RUBYOPT: "-W2 --debug-frozen-string-literal"` to show warnings
https://docs.ruby-lang.org/en/master/ruby/options_md.html#label-W-3A+Set+Warning+Policy
https://github.com/ruby/ruby/pull/11893
- Use Oracle Instant client permanent links    
> Permanent links to the latest packages

CI against ruby-head

---

.github/workflows/ruby_head.yml

This pull request adds `workflow_dispatch` to allow ruby_head action run manually.
https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/manually-running-a-workflow

Add `workflow_dispatch` to allow ruby_head action run manually

---

ci/setup_accounts.sh

This pull request addresses the following ORA-01031 error.
```sql
GRANT EXECUTE ON dbms_lock TO ruby
*
ERROR at line 1:
ORA-01031: insufficient privileges
Help: https://docs.oracle.com/error-help/db/ora-01031/
```

Address ORA-01031: insufficient privileges

---

.github/workflows/ruby_head.yml

This commit adds `ruby-asan` to CI
https://github.com/ruby/setup-ruby
> ruby-asan is the same as ruby-head but with AddressSanitizer (ASan) enabled, helpful for finding memory issues in native extensions.
> Native extensions are automatically compiled with AddressSanitizer when using ruby-asan. ruby-asan is currently only available on ubuntu-24.04.
`ruby-asan` can be added since the CI migrates to the `ubuntu-latest` via #2450

Add `ruby-asan` to CI

---

spec/active_record/connection_adapters/oracle_enhanced/compatibility_spec.rb

This commit suppresses the following migration standard output.
```ruby
$ bundle exec rspec spec/active_record/connection_adapters/oracle_enhanced/compatibility_spec.rb:21
==> Running specs with ruby version 3.4.4
==> Effective ActiveRecord version 8.0.2
Run options: include {locations: {"./spec/active_record/connection_adapters/oracle_enhanced/compatibility_spec.rb" => [21]}}
==  : migrating ===============================================================
-- rename_table(:test_employees, :new_test_employees)
-> 0.2045s
==  : migrated (0.2045s) ======================================================
==  : reverting ===============================================================
-- rename_table(:new_test_employees, :test_employees)
-> 0.2033s
==  : …
```

Suppress messages for the "should rename table on 7_0 and below" spec

---

History.md

This pull request marks History.md as no longer updated and points to GitHub releases, as maintaining both is redundant.

Mark History.md as no longer updated and point to GitHub releases

---

.travis.yml

This pull request updates .travis.yml to run "/ TIMESTAMP WITH TIME ZONE values from ActiveRecord model" only.
This test has been disabled at test_11g.yml via https://github.com/rsim/oracle-enhanced/pull/2389 Once this test can be run with GitHub Actions, we can disable Travis CI.

Update .travis.yml to run "/ TIMESTAMP WITH TIME ZONE values from ActiveRecord model"
