lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Address ORA-00932: inconsistent datatypes: expected NUMBER got DATE

---

.gitignore
lib/active_record/connection_adapters/oracle_enhanced_dirty.rb
spec/active_record/connection_adapters/oracle_enhanced_dirty_spec.rb
spec/spec_config.yaml.template
spec/spec_helper.rb

Fixes https://github.com/rsim/oracle-enhanced/issues/545

Rails42 GHI545

---

lib/active_record/connection_adapters/oracle_enhanced_column.rb

This pull request addresses #573.

Support 'Y' as true and 'N' as false in Rails 4.2

---

lib/active_record/connection_adapters/oracle_enhanced/column_dumper.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Migrate from ActiveRecord::ConnectionAdapters::OracleEnhancedColumnDumper
to ActiveRecord::ConnectionAdapters::OracleEnhanced::ColumnDumper

Migrate to ActiveRecord::ConnectionAdapters::OracleEnhanced::ColumnDumper

---

lib/active_record/connection_adapters/oracle_enhanced/context_index.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

This pull request migrates from OracleEnhancedContextIndex to OracleEnhanced::ContextIndex
It is necessary to prepare another refactoring for schema_dumper.

Migrated from OracleEnhancedContextIndex to OracleEnhanced::ContextIndex

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

Also removed Rails 4.0 compatibility since this branch will support Rails 4.2
Refer https://github.com/rails/rails/commit/e185ba24c83bc87fec3de808311c68b15a6ff16d

Refactor add_index and add_index_options

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
lib/active_record/oracle_enhanced/type/integer.rb

Oracle enhanced adapter implements NUMBER(p,0) sql_type as a Integer.
Then NUMBER(p,0), p as precision can take equal to 38.
This value range is larger than ActiveRecord::Type::Integer max_value.
This pull request addresses following failures.
```ruby
$ ARCONN=oracle ruby -Itest test/cases/schema_dumper_test.rb -n /integer/
Using oracle
Run options: -n /integer/ --seed 61224
FF
Finished in 19.973679s, 0.1001 runs/s, 0.3004 assertions/s.
1) Failure:
SchemaDumperTest#test_schema_dump_includes_limit_constraint_for_integer_columns [test/cases/schema_dumper_test.rb:144]:
Expected /c_int_5.*limit: 5/ to match "# encoding: UTF-8\n# This file is auto-generated from the current state of the database. Instead\n# of editing this file, please use the migrations feature of Active Record to\n# …
```

ActiveRecord::OracleEnhanced::Type::Integer for max_value to take 38 digits

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced/structure_dump.rb

to follow Rails module configuration

Move dump_schema_information to SchemaStatements

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

This pull request is to prepare Rails native foreign key constraint which supports to create foreign key for a column with :unique index.

Rails42 add unique index creates unique constraint

---

spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb

This pull request updates one of Oracle enhanced unit test spec. 
Refer https://github.com/rails/rails/commit/8768305f20d12c40241396092a63e0d56269fefe
and https://github.com/rails/rails/pull/15606

Do not dump default foreign key name

---

spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb

Update foreign key names for add_foreign_key with table_name_prefix

---

activerecord-oracle_enhanced-adapter.gemspec

It's may save some developer time like [ruby-china discussed](https://ruby-china.org/topics/26161).

Prevent Rails 4.2 using version 15 series.

---

lib/active_record/connection_adapters/oracle_enhanced/schema_definitions.rb

Necessary method for Rails 5 support

Use OracleEnhanced::ColumnDefinition

---

activerecord-oracle_enhanced-adapter.gemspec

To avoid #651 or similar errors.

Requires activerecord 4.2.1 or higher

---

lib/active_record/connection_adapters/oracle_enhanced/column.rb
lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Refer https://github.com/rails/rails/commit/158c7eb1

Initial support for sql_type_metadata

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb

Fix serialized value becomes from yaml to string once saved

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb

Not to execute `type_cast` method twice.

Use type_casted_binds

---

spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

Add minimal specs for ActiveRecord::Base.limit() and .order().

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb

Use type_cast_for_database to serialize correctly

---

lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb

also uses Module#prepend to prepare deprecated alias_method_chain

Move to ActiveRecord::ConnectionAdapters::OracleEnhanced::SchemaDumper

---

lib/active_record/connection_adapters/oracle_enhanced/column_dumper.rb

to prepare deprecated alias_method_chain

ColumnDumper uses Module#prepend 

---

Gemfile

Refer https://github.com/rails/journey/issues/68

Remove journey which is already part of Rails

---

.gitignore

Kind of backport #699 into master

Ignore .rbenv-gemsets

---

Gemfile

fixing bundler dependency conflict with head of rails vs arel 6.0

---

lib/active_record/oracle_enhanced/type/integer.rb
lib/active_record/oracle_enhanced/type/raw.rb
lib/active_record/oracle_enhanced/type/timestamp.rb

https://github.com/rails/rails/commit/9cc8c6f3730df3d94c81a55be9ee1b7b4ffd29f6

Move ActiveRecord::Type to ActiveModel

---

lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb

https://github.com/rails/rails/pull/21928

Require ruby-oci8 2.2.0 or higher

---

lib/active_record/connection_adapters/oracle_enhanced/column_dumper.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb
lib/active_record/connection_adapters/oracle_enhanced/structure_dump.rb
spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_structure_dump_spec.rb

This pull request merges #734 to rails5 btranch

Include table/column comments in schema and structure dumps for rails5

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Refer https://github.com/rails/rails/commit/dcd39949 which is part of https://github.com/rails/rails/pull/21609

Support `#views`

---

README.md
RUNNING_TESTS.md
lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/structure_dump.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced_connection_spec.rb
spec/spec_helper.rb

This pull request introduce `schema` options to Oracle enhanced adapter discussed and requested in #169. I have cherry-picked @PMACS commits and rebased to work with current master branch.

Support schema option in database config

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Refer https://github.com/rails/rails/pull/11258

Remove deprecated `distinct` method

---

lib/active_record/connection_adapters/oracle_enhanced/quoting.rb

refer https://github.com/rails/rails/commit/03f6e235a32b4ba540db11586b66416e780bc3d7

type_cast arity change

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

Support t.foreign_key use the same `to_table` twice

---

spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

Refer https://github.com/rails/rails/pull/20450

Skip "Relation#count does not support finder options anymore in Rails"

---

lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb

Follow up #795 for JDBC connections.

Support bind_params for JDBC connections

---

lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb

Refer https://github.com/rails/rails/commit/b06f64c3480cd389d14618540d62da4978918af0

Add deprecation warning for `bind_param`

---

lib/active_record/connection_adapters/oracle_enhanced/column.rb

Refer https://github.com/rsim/oracle-enhanced/pull/811/commits/e2f23d24fa616498f8659bcf2a587b78bea0e1d3

Remove `self.string_to_raw` from Column which is not called anymore

---

spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb

Skip one Oracle enhanced unit test which conflict with ActiveRecord

---

activerecord-oracle_enhanced-adapter.gemspec

https://github.com/rails/rails/tree/v5.0.0.beta4

Rails 5.0.0.beta4 has been released

---

lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb

This pull request addresses these 4 failures by using ActiveRecord::SchemaDumper#ignored? not in Oracle enhanced `ignore_table?`.
```ruby
ARCONN=oracle bundle exec ruby -W -w -I"lib:test" test/cases/schema_dumper_test.rb -n test_schema_dump_with_table_name_prefix_and_suffix
ARCONN=oracle bundle exec ruby -W -w -I"lib:test" test/cases/schema_dumper_test.rb -n test_schema_dump_with_regexp_ignored_table
ARCONN=oracle bundle exec ruby -W -w -I"lib:test" test/cases/schema_dumper_test.rb -n test_schema_dump_with_string_ignored_table
ARCONN=oracle bundle exec ruby -W -w -I"lib:test" test/cases/schema_dumper_test.rb -n test_schema_dump
```
All failures are due to `ar_internal_metadata` table is dumped. 
```ruby
$ ARCONN=oracle bundle exec ruby -W -w -I"lib:test" test/cases/schema_dumper_test.rb …
```

Use ActiveRecord::SchemaDumper#ignored?

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

Refer https://github.com/rails/rails/pull/24685

Use Abstract adapter `dump_schema_information` implementation

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

This is part of supporting dumping composite primary key
Refer https://github.com/rails/rails/pull/21614
This pull request addresses this error.
```ruby
$ ARCONN=oracle bundle exec ruby -W -w -I"lib:test" test/cases/primary_keys_test.rb -n test_composite_primary_key
... snip ...
E
Finished in 0.040752s, 24.5389 runs/s, 0.0000 assertions/s.
1) Error:
CompositePrimaryKeyTest#test_composite_primary_key:
NoMethodError: undefined method `primary_keys' for #<ActiveRecord::ConnectionAdapters::OracleAdapter:0x0055dec57eef60>
Did you mean?  primary_key
test/cases/primary_keys_test.rb:261:in `test_composite_primary_key'
1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
$
```

Implement primary_keys to prepare dumping composite primary key

---

lib/active_record/connection_adapters/oracle_enhanced/column_dumper.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb

This pull request addresses a following failure.
```ruby
$ ARCONN=oracle bundle exec ruby -W -w -I"lib:test" test/cases/primary_keys_test.rb -n test_schema_dump_primary_key_includes_type_and_options
... snip ...
F
Finished in 6.234420s, 0.1604 runs/s, 0.3208 assertions/s.
1) Failure:
PrimaryKeyAnyTypeTest#test_schema_dump_primary_key_includes_type_and_options [test/cases/primary_keys_test.rb:239]:
Expected /create_table "barcodes", primary_key: "code", id: :string, limit: 42/ to match "# This file is auto-generated from the current state of the database. Instead\n# of editing this file, please use the migrations feature of Active Record to\n# incrementally modify your database, and then regenerate this schema definition.\n#\n# Note that this schema.rb definition is the authoritative …
```

Dump type and options for non default primary keys

---

lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb

refer https://github.com/rsim/oracle-enhanced/pull/860
https://github.com/rails/rails/pull/21614/
```ruby
$ ARCONN=oracle bundle exec ruby -W -w -I"lib:test" test/cases/primary_keys_test.rb -n test_collectly_dump_composite_primary_key
... snip ...
WARNING: Rails does not support composite primary key.
barcodes has composite primary key. Composite primary key is ignored.
F
Finished in 25.789512s, 0.0388 runs/s, 0.0776 assertions/s.
1) Failure:
CompositePrimaryKeyTest#test_collectly_dump_composite_primary_key [test/cases/primary_keys_test.rb:273]:
Expected /create_table "barcodes", primary_key: \["region", "code"\]/ to match "# This file is auto-generated from the current state of the database. Instead\n# of editing this file, please use the …
```

Dump composite primary keys

---

spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb

Follow up for #868 
* Remove `emulate_dates_by_column_name` from specs
* Remove `emulate_dates` from specs

Do not set emulate_dates_by_column_name or emulate_dates in specs

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Deprecate `set_boolean_columns` and `set_string_columns`

---

Gemfile

Refer https://github.com/jruby/jruby/wiki/UsingTheJRubyDebugger

Install ruby-debug for jruby

---

.travis/oracle/README.md
.travis/oracle/download.js
.travis/oracle/install.sh

Refer https://github.com/cbandy/travis-oracle/tree/v2.0.1

Upgrade travis-oracle to Version 2.0.1

---

activerecord-oracle_enhanced-adapter.gemspec

including https://github.com/rails/arel/pull/430 and https://github.com/rails/arel/pull/422

Arel 7.1.0 or higher version is required

---

README.md

Add default mapping information about Oracle `DATE` to Rails `Date`

---

lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/jdbc_quoting.rb

This pull request addresses #910 and #911 Due to some spec removed like #922 line numbers has changed.

Support CLOB for JRuby

---

spec/active_record/connection_adapters/oracle_enhanced_connection_spec.rb

Not giving `bind_param` a 3rd argument `column`

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Remove TODO comment since Oracle DATE type can be mapped Rails Datetime

---

lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb

Use OracleEnhanced::SchemaDumper#tables and #table only if they have Oracle enhanced specific features

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

`self.is_date_column?`
`is_date_column?`
`self.is_integer_column?`
`self.is_boolean_column?`

Remove `is_?` deprecated methods

---

lib/active_record/connection_adapters/oracle_enhanced/quoting.rb

Remove `quote_date_with_to_date` and `quote_timestamp_with_to_timestamp`

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb

Make `exec_{insert,update}` signatures consistent

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

Use Rails `self.ignored_columns` instead.

Remove `self.ignore_table_columns`

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

ref rails/rails#26019
This pull request addresses this error:
```ruby
2.3.1 [ 5-0-stable ~/git/rails/activerecord]$ bundle exec rake test_oracle
/home/yahonda/.rbenv/versions/2.3.1/bin/ruby -w -I"lib:test" -I"/home/yahonda/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib" "/home/yahonda/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/rake_test_loader.rb" "test/cases/relations_test.rb" "test/cases/collection_cache_key_test.rb" "test/cases/explain_subscriber_test.rb" "test/cases/multiparameter_attributes_test.rb" "test/cases/associations/nested_through_associations_test.rb" "test/cases/associations/eager_singularization_test.rb" "test/cases/associations/inverse_associations_test.rb" "test/cases/associations/has_many_associations_test.rb" …
```

Address `create_table': undefined method `each_pair' for []:Array (NoMethodError)

---

activerecord-oracle_enhanced-adapter.gemspec
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
lib/active_record/oracle_enhanced/type/boolean.rb
spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb

to handle "N" as false when `emulate_booleans_from_strings` set to true
This pull request addresses #979

Add `ActiveRecord::OracleEnhanced::Type::Boolean`

---

guides/bug_report_templates/README.md
guides/bug_report_templates/active_record_gem.rb
guides/bug_report_templates/active_record_gem_spec.rb

This pull request adds two executable test cases. It is very helpful to provide executable test cases to address issues.

Add executable test cases using Minitest or RSpec

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

Try to fix issue  #798 `NoMethodError: undefined method `write' for nil:NilClass for serialized column`

:bug: undefined method for serialized column fix 

---

README.md

Refer https://github.com/rsim/oracle-enhanced/issues/993
#1009 closed by removing the source branch by mistake then made some fix and opening another one.

Add UPGRADE section : Upgrade Rails 4.2 or older version to Rails 5

---

.travis.yml
spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb

Also it changes TZ environment variable at Travis `'Europe/Riga'` same value as defined in `CONNECTION_WITH_TIMEZONE_PARAMS`
Address #1001

Use `default_timezone = :local` to handle `TIMESTAMP WITH LOCAL TIME ZONE`

---

spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb

Removed a invalid spec about TIMESTAMP column

---

.travis.yml
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb
spec/support/create_oracle_enhanced_users.sql

This request backports #1028 to release16 branch. It also needs 044dcc4d4cdff2161973d18f1e205ac453352575

Backport alter primary key rebuild tablespace

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

This pull request addresses #1070.

`supports_fetch_first_n_rows_and_offset?` considers `use_old_oracle_visitor`

---

lib/active_record/oracle_enhanced/type/text.rb

Move `ActiveModel::Type::Text` to `ActiveRecord::Type::Text`

---

spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

Pending until further investigation made for #908

---

.travis.yml

Use Ubuntu Trusty 14.04 and bundler caching at Travis CI environment.

Use Ubuntu Trusty at travis

---

spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_context_index_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_dirty_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_procedures_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb

Refer https://github.com/rails/rails/commit/e030f26ad3d

`clear_cache!` always exists at least since Rails 4.0

---

.travis.yml

$ travis-lint
- has multiple "language" entries, keeping last entry

Address travis.yml has multilpe language entries

---

Gemfile
Rakefile
spec/spec_helper.rb

RCov does not work on Ruby 1.9+ anymore.

Use SimpleCov

---

.rspec

Refer https://relishapp.com/rspec/rspec-core/v/3-5/docs/command-line/warnings-option-run-with-warnings-enabled

Enable RSpec `--warnings` option

---

activerecord-oracle_enhanced-adapter.gemspec

Refer https://github.com/rails/arel/pull/462

Bump Arel to 8.0

---

Gemfile
activerecord-oracle_enhanced-adapter.gemspec

Use Arel 8

---

spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

Pending until further investigation made for #908 for release17 branch

---

.travis.yml

Use JRuby 9.1.7.0 for release17 branch

---

lib/active_record/connection_adapters/oracle_enhanced/jdbc_quoting.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

This pull request addresses #1149 which just reproduces with release17 branch.

Address #1149 `TypeError: can't cast Java::JavaSql::Timestamp`

---

lib/active_record/connection_adapters/oracle_enhanced/schema_creation.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_definitions.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb

Refer https://github.com/rails/rails/pull/27890
@yahonda Could you test the PR?

Switch to keyword args for `type_to_sql`

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

Address add_column gets `ArgumentError: wrong number of arguments`

---

.rubocop.yml
lib/active_record/connection_adapters/oracle_enhanced/column.rb

Add `Style/EmptyLinesAroundMethodBody`

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

This method will be used for ColumnDumper.
refer rails/rails#22589

Introduce `supports_virtual_columns?`

---

.rspec
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_connection_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_context_index_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_cpk_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_database_tasks_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_dbms_output_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_dirty_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_emulate_oracle_adapter_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_procedures_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_structure_dump_spec.rb

Require `spec_helper` automatically in `*_spec.rb`.

Specify `--require spec_helper` in .rspec

---

lib/active_record/connection_adapters/oracle_enhanced/structure_dump.rb

Composite foreign keys are not supported

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Support schema option for views

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Refer https://github.com/rails/rails/commit/5973a984c36 and rails/rails#27503
Addresses #1179

table_exists? only checks tables, does not check views

---

Gemfile

Kind of reverting #899 pry and pry-nav are doing good enough for JRuby

Remove ruby-debug

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Oracle12 visitor is also available for 12.2

Oracle Database 12.2.0.1 has been released

---

lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb

http://www.oracle.com/technetwork/database/enterprise-edition/jdbc-faq-090281.html#0000_00

Oracle Database 12c Release 2 bundles new ojdbc8.jar

---

spec/active_record/connection_adapters/oracle_enhanced_dirty_spec.rb

http://api.rubyonrails.org/classes/ActiveModel/Dirty.html#method-i-changed-3F

No need to check if `changed?` defined

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

`:statement_limit` default value changed from 250 to 1000
Refer https://github.com/rails/rails/commit/6c6eeda54d0

Use Abstract StatementPool

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb

Fix `select_all` with legacy `binds`

---

lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb
spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb

This pull request back ports #1254 to release18 branch.

Fix the BINARY_FLOAT column type returns nil in JRuby

---

lib/active_record/connection_adapters/oracle_enhanced/jdbc_quoting.rb

This pull request backports #1272 to release18 branch.

Let abstract adapter type cast Date, DateTime and Time for JRuby at release18 branch

---

spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

There are a couple of changes in specs:
- NUMBER did not have explicit precision when it is created by "CREATE TABLE" statement
- `test_employees` table had a primary key but no corresponding sequence created by "CREATE SEQUENCE" statement
By running `create_table` migration `test_employees_seq` sequence created and `pk_and_sequence_for` also returns sequence name

Use Rails migration for creating table at "table columns"

---

spec/active_record/connection_adapters/oracle_enhanced_procedures_spec.rb

- custom primary key name `employee_id` to default `id` by default
- custom sequence name `test_employees_s` to default `test_employees_seq`

Use Rails migration for creating table at procedure specs

---

lib/active_record/connection_adapters/oracle_enhanced/schema_definitions.rb
lib/active_record/connection_adapters/oracle_enhanced/structure_dump.rb

Follow the new interface of AR::ConnectionAdapters::IndexDefinition#initialize

---

activerecord-oracle_enhanced-adapter.gemspec

Collapse a file specification in gemspec

---

activerecord-oracle_enhanced-adapter.gemspec

Reduce tasks of release work

---

History.md

Kind of backporting #1300 into release18

Prepare release v1.8.0.rc2

---

activerecord-oracle_enhanced-adapter.gemspec

Include VERSION file in gem

---

.travis.yml

as CI environment
https://docs.travis-ci.com/user/customizing-the-build#Building-Specific-Branches

Do not build nextval branch until Oracle 12.2 is available

---

.travis.yml

Use Ubuntu 12.04

---

lib/active_record/connection_adapters/oracle_enhanced/context_index.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

`execute` can run multiple lines SQL statements.

Remove `compress_lines`

---

History.md

Prepare release v1.8.1 [ci skip]

---

lib/active_record/oracle_enhanced/type/json.rb

Use ActiveRecord::Type::Json

---

.travis.yml

http://jruby.org/2017/06/15/jruby-9-1-12-0.html

CI against JRuby 9.1.12.0

---

README.md

Add upgrade section for `:statement_limit` value at Rails 5.1 [skip ci]

---

.rubocop.yml

Follow Rails implementation rails/rails#29748 No offenses found so far.

Enable Layout/EmptyLineAfterMagicComment cop

---

.rubocop.yml
lib/active_record/connection_adapters/oracle_enhanced/structure_dump.rb
spec/active_record/connection_adapters/oracle_enhanced_dirty_spec.rb

Follow up of https://github.com/rails/rails/pull/29810.

Enable `Layout/FirstParameterIndentation` cop

---

lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb

Since `ActiveRecord::SchemaDumper` is not adapter specific Oracle enhanced adapter handles if it is Oracle enhanced adapter or not by using @connection.respond_to?(:method_name).
These `:method_name` have been chosen which is only used for Oracle enhanced adapter,
such as `:materialized_views`.
In future, if any other database adapter implements the same method name, this logic will be broken.
(i.e. postgresql adapter implements `materialized_views`.)
Then this commit handles by using `@connection.adapter_name`.
This default value can be `OracleEnhanced` or `Oracle` if `emulate_oracle_adapter: true`.

Handle `ActiveRecord::SchemaDumper` by adapter_name

---

lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb

Remove `ActiveRecord::ConnectionAdapters::OracleEnhanced::SchemaDumper::TableInspect`

Remove `OracleEnhanced::SchemaDumper::TableInspect`

---

lib/active_record/connection_adapters/oracle_enhanced/quoting.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_connection_spec.rb

I'm still seeing those 5 failures on my local copy of the repo, but those were failing when I checked the project out from master.

Fix #1408 check for schema name when validating table name

---

.github/stale.yml

This reverts commit f7a5c33d3c1e1216bb6f2e6b8a8e15e6ba11a026.

Revert "Limit to only `issues`"

---

.travis.yml
.travis/oracle/install.sh

Backport #1413 to release17 branch

Setting `disk_asynch_io` to `false` to address slow unit tests to release17 branch

---

.travis.yml
.travis/oracle/install.sh

Backport #1413 to release16 branch.

Setting `disk_asynch_io` to `false` to address slow unit tests to release16 branch

---

.rubocop.yml

Follow up of rails/rails#30210.

Enable `context_dependent` of Style/BracesAroundHashParameters cop

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb

Follow up of rails/rails#29944.

Restore the ability that SQL with binds for `insert`

---

lib/active_record/connection_adapters/oracle_enhanced/column_dumper.rb

Refer https://github.com/rails/rails/commit/8170419b0a0e7abbfb2c64c84f641c0a39c163d0

`prepare_column_options` is now private

---

History.md

Backport #1434 to release18 branch

Prepare release v1.8.2 [ci skip]

---

lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb

Refer https://github.com/rails/rails/commit/51b017652a4725f51e6ee01737f52ff63d5b8424

Remove unused returning value `stream`

---

lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

to have similar implementation with abstract SchemaDumper

Introduce `OracleEnhanced::SchemaStatements#table_options`

---

lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/jdbc_quoting.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_quoting.rb
lib/active_record/connection_adapters/oracle_enhanced/quoting.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_creation.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_definitions.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
lib/active_record/oracle_enhanced/type/national_character_text.rb
spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_structure_dump_spec.rb

Added support for NCLOB datatype. Closed the previous pull request (#1428) and squashed all changes in single commit in this new pull request.

Support for NCLOB datatype

---

lib/active_record/connection_adapters/oracle_enhanced/column.rb

It was already removed in #963, there is a leftover.

Remove `OracleEnhancedAdapter.emulate_dates`

---

spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb

Remove `set_boolean_columns` from `oracle_enhanced_data_types_spec.rb`

---

spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb

Remove `set_string_columns` from `oracle_enhanced_data_types_spec.rb`

---

spec/active_record/connection_adapters/oracle_enhanced/schema_dumper_spec.rb
spec/spec_helper.rb

to dump the table necessary in specs

Introduce `SchemaDumpingHelper#dump_table_schema`

---

lib/active_record/connection_adapters/oracle_enhanced/connection.rb
lib/active_record/connection_adapters/oracle_enhanced/dbms_output.rb
lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb

Also renamed these three classes under `OracleEnhanced` module:
Rename `OracleEnhancedJDBCConnection` to `OracleEnhanced::JDBCConnection`
Rename `OracleEnhancedOCIConnection` to `OracleEnhanced::OCIConnection`
Rename `OracleEnhancedConnectionException` to `OracleEnhanced::ConnectionException`

Rename `OracleEnhancedConnection` to `OracleEnhanced::Connection`

---

spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

Move "OracleEnhancedAdapter establish connection" specs

---

.travis.yml

Backport #1484 into release18 branch

Bump ruby versions to 2.4.2, 2.3.5 and 2.2.8 at Travis

---

spec/active_record/connection_adapters/oracle_enhanced/context_index_spec.rb

Use `SchemaDumpingHelper#dump_table_schema` at context_index_spec

---

spec/active_record/connection_adapters/oracle_enhanced/schema_dumper_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

Remove specs for column cache featurs dropped in #1490

---

guides/bug_report_templates/active_record_gem.rb
guides/bug_report_templates/active_record_gem_spec.rb

Replace :github source with https

---

Gemfile

Follow up for rails/rails#30109.

Simplify `git_source` in Gemfile

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Refer https://github.com/rails/rails/pull/28052

Change `schema_creation` to private

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

Change `create_table_definition` and `fetch_type_metadata` to private

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Refactor `columns` by separating into `column_definitions` and `new_column_from_field`
Also removed `new_columns` method
Refer https://github.com/rails/rails/pull/28487
https://github.com/rails/rails/pull/28052

Refactor `columns` 

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

It has been removed from Rails https://github.com/rails/rails/commit/213796fb4936dce1da2f0c097a054e1af5c25c2c

Remove `combine_bind_parameters`

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Also removed invalid comments about ignored coluns

Clean up `column_definitions` method

---

lib/active_record/connection_adapters/oracle_enhanced/connection.rb
lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_definitions.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Remove unnecessary `ActiveRecord::ConnectionAdapters` from `ActiveRecord::ConnectionAdapters:OracleEnhanced`

Remove unnecessary `ActiveRecord::ConnectionAdapters`

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

and move `ActiveRecord::Type.register` inside OracleEnhancedAdapter class

Move up require for types

---

lib/active_record/connection_adapters/oracle_enhanced/dbms_output.rb

`ActiveRecord::ConnectionAdapters::AbstractAdapter#log` is a `private`

---

.codeclimate.yml

Follow up for rails/rails#30874.

Use `rubocop-0-50` channel on Code Climate

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Remove deprecations for 5.2

---

lib/active_record/connection_adapters/oracle_enhanced/structure_dump.rb

Not using begin .. rescue block.
Also format sql statement into one line.

Call `virtual_columns_for` when `supports_virtual_columns?` returns true

---

lib/active_record/connection_adapters/oracle_enhanced/structure_dump.rb

and add necessary notes at structure_dump.rb

Log multi lines SQL statements into one line

---

lib/active_record/connection_adapters/oracle_enhanced/connection.rb

Rename `OracleEnhanced::Connection#select_value` to `_select_value` and `OracleEnhanced::Connection#select_one` to `_select_one`
and make them private to avoid other methods all them.
Since #1560 they are only called from `OracleEnhanced::Connection#describe`
Usually `ActiveRecord::ConnectionAdapters::DatabaseStatements#select_value`
and `ActiveRecord::ConnectionAdapters::DatabaseStatements#select_one` should be used.
`OracleEnhanced::Connection#describe` is planned to refactor in the next
major version of Oracle enhanced adapter, likely 6.0 or later.

Rename `OracleEnhanced::Connection#select_value` to `_select_value`

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

synonyms are part of data_sources [skip ci]

---

.rubocop.yml
spec/active_record/connection_adapters/oracle_enhanced/database_tasks_spec.rb

Enable and apply `Style/Semicolon`

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

[skip ci] Add `schema` option in the comment

---

.codeclimate.yml

Follow up for rails/rails#31111.

Use `rubocop-0-51` channel on Code Climate

---

.rubocop.yml

Refer https://github.com/rails/rails/commit/7ce8a6af1b8fdbc9ee553bda3fd725bea169c2f3

Enable `Style/DefWithParentheses` rubocop rule

---

spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

Skip failed spec explained at #1599

---

.rubocop.yml

Refer https://github.com/rails/rails/commit/2b35826389005bdb0af85a4ebb1f0ec213174d13

Enable `Layout/SpaceBeforeComma`

---

.rubocop.yml
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/type/oracle_enhanced/national_character_text.rb
lib/active_record/type/oracle_enhanced/text.rb
spec/active_record/connection_adapters/oracle_enhanced/structure_dump_spec.rb
spec/active_record/oracle_enhanced/type/national_character_text_spec.rb
spec/active_record/oracle_enhanced/type/text_spec.rb

Refer: https://github.com/rails/rails/commit/245c1dafa8bab409fbcd780a996c619240df7143

Enable `Layout/LeadingCommentSpace` cop

---

.travis.yml

These Rubies has been released.
- https://www.ruby-lang.org/en/news/2017/12/14/ruby-2-2-9-released/
- https://www.ruby-lang.org/en/news/2017/12/14/ruby-2-3-6-released/
- https://www.ruby-lang.org/en/news/2017/12/14/ruby-2-4-3-released/

Use latest Rubies on Travis CI

---

guides/bug_report_templates/active_record_gem.rb
guides/bug_report_templates/active_record_gem_spec.rb

This reverts commit 33caae0b9cafad35b57c76157a131fc43f02cf7a.
Refer #1590

Revert "Use Bundler 1.15 to workaround bundler/bundler#6072"

---

.rubocop.yml
lib/active_record/connection_adapters/oracle_enhanced/context_index.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb

Enable autocorrect for `Lint/EndAlignment` cop

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb

This implementation actually performs conventional fixture insert
Fixes #1632

Support `insert_fixtures_set`

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb

Deprecated `insert_fixtures`

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced/schema_statements_spec.rb

Refer #1595 for the background of this change

Change `default_sequence_start_value` from 10000 to 1

---

README.md

Add README and UPGRADE sections for Rails 5.2 to release52 

---

lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb

Remove `OCI8#describe` to use `OracleEnhanced::Connection#describe`

---

lib/active_record/connection_adapters/oracle_enhanced/structure_dump.rb

from `structure_dump_db_stored_code` to prepare #1625

Extract `structure_dump_views` and `structure_dump_synonyms`

---

lib/active_record/connection_adapters/oracle_enhanced/structure_dump.rb
spec/active_record/connection_adapters/oracle_enhanced/structure_dump_spec.rb

rake db:structure:dump extracts views by default

---

.rubocop.yml
lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_creation.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced/structure_dump_spec.rb

Refer: https://github.com/rails/rails/commit/89bcca59e91fa9da941de890012872e8288e77b0

Remove `strip_heredoc`

---

spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

This pull request backports #1655 to `release52` branch.

Suppress expected exceptions by `report_on_exception` = `false`

---

.rubocop.yml
.travis.yml
activerecord-oracle_enhanced-adapter.gemspec

Rails 6 requires Ruby 2.4.1+

---

.rubocop.yml

Refer https://github.com/rails/rails/commit/9c0c90979a759a41628e0cd9d73821b0b34d03fc

Enable `Style/ColonMethodCall` cop

---

History.md

This pull request backports #1635 to release52 branch.

Prepare release v5.2.0.rc1 [skip ci]

---

History.md

This pull request backports #1690 to release52 branch.

Prepare release v5.2.0 [skip ci]

---

README.md

This reverts commit c5ff54d6f890c6bb05ac14ed39cdef6b457773e0.

Revert "Rails 5.2 is still RC [skip ci]"

---

README.md

Follow up of #1637.
@yahonda Thank you for releasing Oracle enhanced adapter 5.2.0 🎉

Update README for Rails 5.2 [skip ci]

---

History.md

Backport #1701 to release52 branch.

Prepare release v5.2.1 [skip ci]

---

spec/active_record/connection_adapters/oracle_enhanced/quoting_spec.rb

Remove specs testing valid_table_name for database link

---

.rubocop.yml

Refer rails/rails#32681 and follow up #1698

Use `Layout/EndAlignment` cop to support RuboCop 0.54

---

.travis.yml

http://jruby.org/2018/04/23/jruby-9-1-17-0.html

CI with JRuby 9.1.17.0

---

.codeclimate.yml

not to show faiures at #1715
Refer rails/rails#31292

Restore old Code Climate behavior

---

History.md

Backport #1718 to release52 branch

Prepare release v5.2.2 [skip ci]

---

.rubocop.yml

Follow up of https://github.com/rails/rails/commit/a77447f.

Enable `Lint/StringConversionInInterpolation` cop

---

.travis.yml

This pull request backports #1725 into release52 branch.

Do not install bundler explicitly

---

.rubocop.yml
spec/active_record/connection_adapters/emulation/oracle_adapter_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/context_index_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/procedures_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/quoting_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/schema_dumper_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/schema_statements_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/structure_dump_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb
spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb
spec/active_record/oracle_enhanced/type/boolean_spec.rb
spec/active_record/oracle_enhanced/type/json_spec.rb
spec/active_record/oracle_enhanced/type/national_character_string_spec.rb
spec/active_record/oracle_enhanced/type/timestamp_spec.rb

Follow up of rails/rails#33350.

Enable `Layout/EmptyLinesAroundBlockBody` cop

---

.codeclimate.yml

Follow up of rails/rails#33278.

Use `rubocop-0-58` channel

---

.rubocop.yml
lib/active_record/connection_adapters/oracle_enhanced/connection.rb
lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
lib/active_record/connection_adapters/oracle_enhanced/database_tasks.rb
lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/quoting.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

This pull request enables three performance cops enabled at Rails by rails/rails#32695

Introduced StartWith, EndWith and RegexpMatch cops

---

.travis.yml

This pull request backports #1739 to release52 branch.

Add allow_railures for jruby-head until #1737 resolved

---

.travis.yml

This pull request backports #1728 to release52 branch.

CI against JRuby 9.2.0.0

---

lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb
spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb

This pull request backports #1745 to release52 branch.

Use cursor_sharing = force by default again

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

Kind of backporting #1747 to release52 branch

Add table_name search condition to `indexes(table_name)` method

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

This pull request backports #1744 to release52 branch.

Introduce column cache per connection

---

.rubocop.yml

refer https://github.com/rails/rails/commit/51bdbc2d0198c666cd62d1404c18da477e5cbfbc
There are no offenses yet.

Enable `Lint/UriEscapeUnescape` cop

---

.rubocop.yml
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb

refer https://github.com/rails/rails/commit/b2c1e29c14b91b290b30c928c63253d1555e0fd9

Enable Style/ParenthesesAroundCondition cop

---

lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb
spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb

Remove NativeException

---

.rubocop.yml
lib/active_record/connection_adapters/oracle_enhanced/context_index.rb
lib/active_record/connection_adapters/oracle_enhanced/quoting.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_creation.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced/structure_dump.rb
spec/active_record/connection_adapters/oracle_enhanced/context_index_spec.rb
spec/active_record/connection_adapters/oracle_enhanced/schema_statements_spec.rb

This pull request enables performance `Performance/UnfreezeString` cop. 
It will be merged if https://github.com/rails/rails/pull/32971/ is merged to Rails.
As this cop does not support autocorrect, I'd like to prepare this pull request in advance.
@koic Would you review this pull request and have some comments. Do not merge it yet.

Enable performance unfreeze string cop

---

guides/bug_report_templates/active_record_gem.rb
guides/bug_report_templates/active_record_gem_spec.rb

Related to https://github.com/rails/rails/pull/34335

Update bug report templates

---

lib/active_record/connection_adapters/oracle_enhanced/schema_definitions.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

Follow up of https://github.com/rails/rails/commit/b04c6339640d87b680f1975f3686fed0d885b1bc.

Refactor to initialize `TableDefinition` by kwargs

---

.codeclimate.yml

Related to https://github.com/rails/rails/pull/34406

Use `rubocop-0-60` channel

---

lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb
lib/active_record/connection_adapters/oracle_enhanced/quoting.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
lib/active_record/type/oracle_enhanced/character_string.rb
spec/active_record/oracle_enhanced/type/character_string_spec.rb
spec/active_record/oracle_enhanced/type/national_character_string_spec.rb

the problem with processing with char column is fixed

fix Handling with char-column problem

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

This pull request implements https://github.com/rails/rails/pull/34468/

Redact SQL in errors

---

History.md

This pull request backports #1792 to release52 branch.

Prepare release v5.2.4 [skip ci]

---

.rubocop.yml

Refer https://github.com/rails/rails/commit/f907b418aecfb6dab4e30149b88a8593ddd321b9

Enable `Layout/SpaceAfterSemicolon` cop

---

.rubocop.yml
.travis.yml
activerecord-oracle_enhanced-adapter.gemspec

Refer https://github.com/rails/rails/pull/34754

Rails 6 requires Ruby 2.5

---

.rubocop.yml

Follow up of rails/rails#34764.

Enable `Style/RedundantBegin` cop

---

.rubocop.yml

Follow up of https://github.com/rails/rails/commit/6d959017bd05c775d35045401292828c92b7dcc7.

Enable `Lint/ShadowingOuterLocalVariable` cop

---

.codeclimate.yml

Refer https://github.com/rails/rails/pull/34981

Bump RuboCop to 0.63.0

---

.rubocop.yml

Related to https://github.com/rails/rails/commit/7ebfb319ffbfc1f9d3dc5439052ae06019bf4290

Enable `Lint/ErbNewArguments` cop

---

.travis.yml

backporting #1824 to release52

CI against JRuby 9.2.6.0

---

.travis.yml

This pull request backports #1834 to release52 branch.

Add allow_railures for jruby-head until #1833 resolved

---

History.md

This pull request backports #1837 into release52.

Prepare release v5.2.5 [skip ci]

---

.rubocop.yml

Refer https://github.com/rails/rails/commit/4353adab89bab252521e0e191d0177ece1538fbb

Enable `Lint/AmbiguousOperator` and `Lint/AmbiguousRegexpLiteral` cops

---

.rubocop.yml

Refer https://github.com/rails/rails/commit/6b8daad0383a40bb397644d0a1f8b35808611d6e

Enable `Performance/ReverseEach` cop

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Refer https://github.com/rails/rails/commit/a67841eb61f808a965da0d61ea47e2d9810436b0

Ensure `clear_cache!` clears the prepared statements cache

---

spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

Add another spec to support optimizer hints using `/*+ */`

---

.rubocop.yml

Enable `Layout/SpaceBeforeComment` cop

---

.travis.yml

https://www.jruby.org/2019/04/09/jruby-9-2-7-0.html

CI against JRuby 9.2.7.0

---

.codeclimate.yml

Use newer Code Climate analysis model, version 2

---

.travis.yml

Add allow_railures for jruby-head until #1875 resolved

---

lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb

This pull request backports #1874 to release60 branch.

Add TCP keepalive and TCP keepalive time configurations

---

History.md

Fix version number at History.md [skip ci]

---

lib/active_record/connection_adapters/oracle_enhanced/schema_definitions.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

This pull request refactors create_table`'s options separation
Refer https://github.com/rails/rails/commit/c3ca9b00e3c5f839311c55549f25f7afe8120f9d

Refactor `create_table`'s options separation

---

lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

Follow up https://github.com/rails/rails/pull/36371.

Move schema cache to pool

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

Refer https://github.com/rails/rails/commit/5cab344494c340ea82a35b46efa06b94f0b7730b
It is required for passing spec with master in rails/rails after
https://github.com/rails/rails/commit/c5ecc338e863e771adcbcd87d5c23ae5e7ca7894.

Clear schema cache when a table is created/dropped/renamed

---

lib/active_record/connection_adapters/oracle_enhanced/quoting.rb

This pull request backports #1901 to release60 branch.

Share the column and table name quote cache between connections

---

History.md

This pull request backports #1904 to release60 branch

Prepare release for 6.0.0.rc2 [skip ci]

---

History.md

This pull request backports #1908 into release60 branch.

Prepare release for 6.0.0.rc3 [skip ci]

---

History.md

This pull request backports #1915 to release60 branch.

Prepare release v6.0.0 [skip ci]

---

README.md

This pull request backports #1916 to release60 branch.

Update README for 6.0 [skip ci]

---

.travis.yml

This pull request backports #1921 to release60 branch.

CI against Ruby 2.6.4 and Ruby 2.5.6

---

.rubocop.yml

Follow up https://github.com/rails/rails/pull/37121.

Disable `Style/BracesAroundHashParameters` cop

---

.github/workflows/ruby.yml

This pull request removes unnecessary PATH and LD_LIBRARY_PATH environment variables
cc @cjbj

Remove unnecessary PATH and LD_LIBRARY_PATH environment variables

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

Resolves #1929.
Follow rails/rails#37168.

Accept columns passed with options in remove_index

---

.github/workflows/ruby.yml

This pull request schedules GitHub Actions daily, every day at 12 AM UTC.
https://help.github.com/en/articles/workflow-syntax-for-github-actions#onschedule

Run GitHub Actions daily

---

.travis.yml

https://www.jruby.org/2019/10/30/jruby-9-2-9-0

CI against JRuby 9.2.9.0

---

.travis.yml

This pull request runs the bug templates at CI. It will help the bug template actually works.

Run bug report template at CI

---

.rubocop.yml

Refer https://github.com/rails/rails/commit/9b8fb3fc042c1b541a4bf0ef795aaff849c2de16

Enable `Layout/ClosingHeredocIndentation` cop

---

spec/active_record/connection_adapters/oracle_enhanced/database_tasks_spec.rb

This pull request skips known failures until #1943 is resolved to avoid new failures.

Skip known failures until #1943 is resolved

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb

Updated manually because there is a git conflict to backport #1962 to release52.

Backport #1962 to release52 branch

---

Gemfile
spec/spec_helper.rb

Kind of backporting #1968 into release52 branch

Uninstall SimpleCov

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb
spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb

This PR adds the auto-retry bugfix (#1976) to the release52 branch.

Backport #1976 to release52

---

.rubocop.yml

Follow up of https://github.com/rails/rails/pull/38539.

Enable `Style/HashTransformKeys` cop and `Style/HashTransformValues` cop

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb

Follow https://github.com/rails/rails/pull/38713.

Use `build_result` instead of `ActiveRecord::Result.new`

---

.rubocop.yml
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

Follow up to rails/rails#38992.

Enable `Rails/IndexBy` and `Rails/IndexWith` cops

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb

Follow up to https://github.com/rails/rails/commit/817389d.

Make remaining migration options to kwargs

---

ci/setup_accounts.sh

This pull request uses environment variables for sqlplus.

Use environment variables for sqlplus

---

.rubocop.yml
lib/active_record/connection_adapters/oracle_enhanced/quoting.rb

Follow https://github.com/rails/rails/pull/40436.
This PR enables `Layout/SpaceAroundOperators` cop.

Enable `Layout/SpaceAroundOperators` cop

---

guides/bug_report_templates/active_record_gem.rb
guides/bug_report_templates/active_record_gem_spec.rb

This pull request updates bug report templates for Oracle enhanced adapter 6.1.

Update bug report templates for Oracle enhanced adapter 6.1

---

README.md

Remove draft status when Rails 6.1 is ready.

Update README for 6.1 [skip ci]

---

.github/stale.yml

Do not mark `wontfix` is `upstream` label attached

---

.rubocop.yml

Enable `Lint/DuplicateRequire` cop

---

lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb

This pull request backports #2097 to release61 branch.

Fix write_lobs Invalid byte sequence in UTF-8 (#2097)

---

.travis.yml
.travis/oracle/download.sh
.travis/oracle/install.sh
.travis/setup_accounts.sh

Reverts rsim/oracle-enhanced#2060

Revert "Disable Travis CI"

---

.travis.yml

Until this error is resolved
https://travis-ci.com/github/rsim/oracle-enhanced/jobs/471296127#L517

Allow failures for JRuby

---

History.md

This pull request is opened for release60 branch directly.

Prepare release v6.0.6 [skip ci]

---

Gemfile
guides/bug_report_templates/active_record_gem.rb
guides/bug_report_templates/active_record_gem_spec.rb

This pull request follows Rails default branch name change.

Update Rails default branch name change

---

.rubocop.yml

Follow https://github.com/rails/rails/commit/ba97e9f918bc2ffe8ed351a0e0b8d75b67d26086.

Disable `Lint/ShadowingOuterLocalVariable` cop

---

.rubocop.yml

Follow https://github.com/rails/rails/commit/6515d6985d2b537486bd9d1faa95212a508dc42c

Enable `Performance/BindCall` cop

---

lib/active_record/connection_adapters/oracle_enhanced/database_tasks.rb

Database tasks | Fixed ORA-01935: missing user or role name with config read issue

---

spec/active_record/connection_adapters/oracle_enhanced/database_tasks_spec.rb

This reverts commit 76e476bab0b922d3a10504c792aea048f4780b0b.

Revert "Skip known failures until #1943 is resolved"

---

lib/active_record/connection_adapters/oracle_enhanced/database_tasks.rb

This pull request backport #2135 to release61.

Fixed ORA-01935: missing user or role name with config read issue

---

.rubocop.yml

Follow https://github.com/rails/rails/pull/41440.
This PR disables `Layout/FirstArgumentIndentation` cop.

Disable `Layout/FirstArgumentIndentation` cop

---

.rubocop.yml
lib/active_record/connection_adapters/oracle_enhanced/quoting.rb
lib/active_record/connection_adapters/oracle_enhanced/structure_dump.rb
spec/active_record/connection_adapters/oracle_enhanced/context_index_spec.rb

Follow https://github.com/rails/rails/commit/c4b944a

Enable `Performance/StringReplacement` cop

---

.rubocop.yml

Refer https://github.com/rails/rails/commit/c0c77e28adfcef5d9dd2e1b0ec00758a81db427d

Enable `Layout/EndOfLine` cop

---

.rubocop.yml

Follow https://github.com/rails/rails/pull/42083.

Enable `Performance/SelectMap` cop

---

lib/active_record/connection_adapters/oracle_enhanced/schema_creation.rb

Follow https://github.com/rails/rails/commit/ecd4c846bad64e96791181305302251a7bfd304f.

Refactor schema creation to extract `new_foreign_key_definition`

---

.github/workflows/test.yml

Address syntax failure of #2184

---

.github/workflows/ruby.yml

Use Oracle Instant Client 21.1.0.0.0

---

.rubocop.yml
lib/active_record/connection_adapters/oracle_enhanced/procedures.rb

Follow up to https://github.com/rails/rails/pull/43170.

Enable `Style/ExplicitBlockArgument` cop

---

.rubocop.yml

Follow up to https://github.com/rails/rails/pull/43374.

Enable `Lint/DuplicateMethods` cop

---

lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
spec/active_record/connection_adapters/oracle_enhanced/schema_statements_spec.rb

Follow up to https://github.com/rails/rails/pull/41722.

Always use OpenSSL constants for Digest operations

---

.rubocop.yml

Follow up of https://github.com/rails/rails/pull/44343.

Enable `Lint/EnsureReturn` cop

---

.github/workflows/linting.yml
.github/workflows/ruby.yml
.github/workflows/test.yml

https://github.com/actions/checkout/releases/tag/v3.0.0

Use `actions/checkout` version 3

---

.dependabot/config.yml

https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/keeping-your-actions-up-to-date-with-dependabot

Keep GitHub Actions updated with Dependabot

---

.github/workflows/ruby.yml
.github/workflows/test.yml
guides/bug_report_templates/active_record_gem.rb
guides/bug_report_templates/active_record_gem_spec.rb

Use Oracle Instant Client 21.6.0.0.0

---

.github/workflows/test.yml

Please add TruffleRuby to CI to test for compatibility.

Test TruffleRuby in CI

---

lib/active_record/connection_adapters/oracle_enhanced/schema_creation.rb

This pull request supports use_foreign_keys? via rails/rails#45301.

Support use_foreign_keys? via rails/rails#45301

---

lib/active_record/connection_adapters/oracle_enhanced/quoting.rb

Follow up https://github.com/rails/rails/pull/44010.

Accept nested functions in Dangerous Query Methods

---

.rubocop.yml

Follow up https://github.com/rails/rails/pull/45631

Enable `Style/RedundantCondition` cop

---

.travis.yml

https://github.com/rvm/rvm/pull/5306/files

CI against Ruby 3.2.1 at Travis-CI

---

.github/workflows/test.yml

https://www.oracle.com/jp/database/technologies/instant-client/linux-x86-64-downloads.html

Use Oracle Instant Client 21.9.0.0.0

---

lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb
lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb
lib/active_record/connection_adapters/oracle_enhanced/structure_dump.rb
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

There were some unremoved hints via #2337

Remove OPTIMIZER_FEATURES_ENABLE('11.2.0.2') hint take 2

---

Gemfile
lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

This pull request supports https://github.com/rails/rails/commit/8551e64e2411811f26d210601abdba6e13d8798c that is part of https://github.com/rails/rails/pull/44591

Support `Simplify adapter construction; defer connect until first use`

---

.travis.yml

https://rubies.travis-ci.org/ubuntu/22.04/x86_64/ruby-3.3.5

Use Ruby 3.3.5 at Travis CI

---

.rubocop.yml

This commit enables `Lint/Debugger` cop
Refer to https://github.com/rails/rails/pull/51804

Enable `Lint/Debugger` cop

---

.rubocop.yml

This commit enables `Layout/ElseAlignment` cop
Refer to https://github.com/rails/rails/pull/46191

Enable `Layout/ElseAlignment` cop

---

.rubocop.yml

This commit enables `Lint/SafeNavigationChain` cop
Refer to https://github.com/rails/rails/pull/50655

Enable `Lint/SafeNavigationChain` cop
